import type { ScraperSource } from './types';

export const SOURCES_PACIFIC_OCEANIA: ScraperSource[] = [

  // ── Pacific Regional Organizations ────────────────────────────────────────
  { id: 'pac-pifs-events', organization: 'Pacific Islands Forum', url: 'https://www.forumsec.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [13, 17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-pif-leaders', organization: 'Pacific Forum Leaders', url: 'https://www.forumsec.org/pacific-leaders/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13, 17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-spc-events', organization: 'Pacific Community (SPC)', url: 'https://www.spc.int/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 13], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-sprep-events', organization: 'SPREP', url: 'https://www.sprep.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [13, 14], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-pifs-giz', organization: 'PRIF Pacific', url: 'https://www.pacificregionalinfrastructure.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [9], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-pacer-events', organization: 'PACER Plus', url: 'https://www.pacerplus.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8, 17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-sopac-events', organization: 'Pacific Community Geoscience', url: 'https://gsd.spc.int/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11, 13], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-ffa-events', organization: 'Pacific Islands Forum Fisheries Agency', url: 'https://www.ffa.int/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [14, 8], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-spto-events', organization: 'South Pacific Tourism Organisation', url: 'https://www.spto.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8], region: 'Pacific', language: 'en', requires_auth: false },

  // ── Pacific Climate ────────────────────────────────────────────────────────
  { id: 'pac-pccc-events', organization: 'Pacific Climate Change Centre', url: 'https://www.sprep.org/pacific-climate-change-centre', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [13], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-prism-events', organization: 'PRISM Pacific', url: 'https://prism.spc.int/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-cop-pacific', organization: 'Pacific COP Delegation', url: 'https://www.forumsec.org/climate/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-gcca-pacific', organization: 'GCCA+ Pacific', url: 'https://www.gcca.eu/regions/pacific', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-pcf-events', organization: 'Pacific Catastrophe Risk Fund', url: 'https://www.pcrafi.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13, 11], region: 'Pacific', language: 'en', requires_auth: false },

  // ── Australia ──────────────────────────────────────────────────────────────
  { id: 'pac-dfat-events', organization: 'DFAT Australia', url: 'https://www.dfat.gov.au/news/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-ausaid-events', organization: 'AUSAID Development', url: 'https://www.dfat.gov.au/international-relations/themes/development', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17, 1], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-anu-events', organization: 'Australian National University', url: 'https://www.anu.edu.au/about/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-devpolicycentre', organization: 'Development Policy Centre', url: 'https://devpolicy.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17, 1], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-lowy-events', organization: 'Lowy Institute', url: 'https://www.lowyinstitute.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16, 17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-aspi-events', organization: 'ASPI', url: 'https://www.aspi.org.au/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-aiia-events', organization: 'AIIA', url: 'https://www.internationalaffairs.org.au/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17, 16], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-unimelb-events', organization: 'University of Melbourne', url: 'https://events.unimelb.edu.au/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 3], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-usyd-events', organization: 'University of Sydney', url: 'https://www.sydney.edu.au/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-uq-events', organization: 'University of Queensland', url: 'https://events.uq.edu.au/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 3], region: 'Pacific', language: 'en', requires_auth: false },

  // ── New Zealand ────────────────────────────────────────────────────────────
  { id: 'pac-mfat-events', organization: 'MFAT New Zealand', url: 'https://www.mfat.govt.nz/en/media-and-resources/news-and-events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-nzaid-events', organization: 'New Zealand Aid', url: 'https://www.mfat.govt.nz/en/aid-and-development/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17, 1], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-univ-auckland', organization: 'University of Auckland', url: 'https://www.auckland.ac.nz/en/events.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-vuw-events', organization: 'Victoria University Wellington', url: 'https://www.wgtn.ac.nz/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 16], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-devnet-nz', organization: 'DevNet NZ', url: 'https://devnet.org.nz/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Pacific', language: 'en', requires_auth: false },

  // ── Pacific Island Countries ───────────────────────────────────────────────
  { id: 'pac-fiji-govt', organization: 'Fiji Government', url: 'https://www.fiji.gov.fj/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-solomon-govt', organization: 'Solomon Islands Government', url: 'https://www.solomons.gov.sb/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13, 16], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-vanuatu-govt', organization: 'Vanuatu Government', url: 'https://www.gov.vu/en/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-samoa-govt', organization: 'Samoa Government', url: 'https://www.samoagovt.ws/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-png-govt', organization: 'Papua New Guinea Government', url: 'https://www.pm.gov.pg/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13, 15], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-tonga-govt', organization: 'Tonga Government', url: 'https://www.gov.to/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13], region: 'Pacific', language: 'en', requires_auth: false },

  // ── Pacific Ocean and Marine ───────────────────────────────────────────────
  { id: 'pac-picsea-events', organization: 'Pacific Ocean Alliance', url: 'https://pacifococeanalliance.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [14], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-ioc-pacific', organization: 'IOC UNESCO Pacific', url: 'https://www.ioc-tsunami.org/index.php/pacific', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [14], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-pn-ocean', organization: 'Pacific Network on Ocean', url: 'https://www.pnaoceans.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [14], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-aims-events', organization: 'AIMS', url: 'https://www.aims.gov.au/research/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [14, 13], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-iucn-oceania', organization: 'IUCN Oceania', url: 'https://www.iucn.org/regions/oceania/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [14, 15], region: 'Pacific', language: 'en', requires_auth: false },

  // ── Pacific Health ─────────────────────────────────────────────────────────
  { id: 'pac-who-pacific', organization: 'WHO Western Pacific', url: 'https://www.who.int/westernpacific/news/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-phc-events', organization: 'Pacific Health Forum', url: 'https://www.spc.int/events?category=health', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-cue-health', organization: 'CPHHA', url: 'https://www.commonwealthhealth.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3], region: 'Pacific', language: 'en', requires_auth: false },

  // ── Pacific Education and Youth ────────────────────────────────────────────
  { id: 'pac-usp-events', organization: 'University of the South Pacific', url: 'https://www.usp.ac.fj/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-upng-events', organization: 'University of Papua New Guinea', url: 'https://www.upng.ac.pg/index.php/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-youthpacific', organization: 'Pacific Youth Council', url: 'https://www.pacificyouth.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 8], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-pacificyouthconf', organization: 'Pacific Youth Conference', url: 'https://www.forumsec.org/youth/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Pacific', language: 'en', requires_auth: false },

  // ── Pacific Governance and Democracy ──────────────────────────────────────
  { id: 'pac-undp-pacific', organization: 'UNDP Pacific', url: 'https://www.undp.org/pacific/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16, 1], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-pran-events', organization: 'Pacific Regional Action Network', url: 'https://www.pacifichumanrights.net/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-commonwealth-pacific', organization: 'Commonwealth Pacific', url: 'https://thecommonwealth.org/pacific/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17, 16], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-ifes-pacific', organization: 'IFES Pacific Elections', url: 'https://www.ifes.org/regions/asia-pacific', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Pacific', language: 'en', requires_auth: false },

  // ── Pacific Disasters and Resilience ──────────────────────────────────────
  { id: 'pac-pdmc-events', organization: 'Pacific Disaster Centre', url: 'https://www.pdc.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11, 13], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-crew-events', organization: 'CREW Pacific', url: 'https://www.crew.ac.uk/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-drr-pacific', organization: 'Pacific DRR Platform', url: 'https://www.undrr.org/regions/asia-pacific-and-pacific', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11, 13], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-ifrc-pacific', organization: 'IFRC Pacific', url: 'https://www.ifrc.org/where-we-work/asia-pacific', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3, 11], region: 'Pacific', language: 'en', requires_auth: false },

  // ── Pacific Economy and Trade ──────────────────────────────────────────────
  { id: 'pac-adb-pacific', organization: 'ADB Pacific', url: 'https://www.adb.org/where-we-work/pacific', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8, 17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-world-bank-pacific', organization: 'World Bank Pacific', url: 'https://www.worldbank.org/en/region/eap/pacificislands', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8, 17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-apec-events', organization: 'APEC', url: 'https://www.apec.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8, 17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-pftac-events', organization: 'PFTAC', url: 'https://www.pftac.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8, 17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-pacifictrade-events', organization: 'Pacific Trade and Invest', url: 'https://pacifictradeinvest.com/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8, 17], region: 'Pacific', language: 'en', requires_auth: false },

  // ── Pacific Agriculture and Food ───────────────────────────────────────────
  { id: 'pac-fao-pacific', organization: 'FAO Pacific', url: 'https://www.fao.org/asiapacific/news/detail-news/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-lrd-events', organization: 'Land Resources Division SPC', url: 'https://lrd.spc.int/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 15], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-pacer-food', organization: 'Pacific Food Security', url: 'https://www.spc.int/lrd/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Pacific', language: 'en', requires_auth: false },

  // ── Indigenous Pacific ─────────────────────────────────────────────────────
  { id: 'pac-indigenous-pacific', organization: 'Pacific Indigenous Network', url: 'https://www.forumsec.org/indigenous-peoples/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10, 15], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-maori-events', organization: 'Te Puni Kōkiri', url: 'https://www.tpk.govt.nz/en/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-atsi-events', organization: 'AIATSIS', url: 'https://aiatsis.gov.au/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10], region: 'Pacific', language: 'en', requires_auth: false },

  // ── Pacific Island Nation Governments ────────────────────────────────────
  { id: 'pac-fiji-govt', organization: 'Fiji Government', url: 'https://www.fiji.gov.fj/news-events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-png-govt', organization: 'Papua New Guinea Government', url: 'https://www.pm.gov.pg/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-samoa-govt', organization: 'Samoa Government', url: 'https://www.gov.ws/news-events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-tonga-govt', organization: 'Tonga Government', url: 'https://www.gov.to/news/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-vanuatu-govt', organization: 'Vanuatu Government', url: 'https://www.vanuatu.travel/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-solomon-govt', organization: 'Solomon Islands Government', url: 'https://www.mof.gov.sb/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-kiribati-govt', organization: 'Kiribati Government', url: 'https://www.kiribati.gov.ki/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13, 17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-fsm-govt', organization: 'Micronesia Government', url: 'https://www.fsmgov.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-palau-govt', organization: 'Palau Government', url: 'https://www.palaugov.pw/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [14, 17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-marshalls-govt', organization: 'Marshall Islands Government', url: 'https://www.rmigovernment.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13, 17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-nauru-govt', organization: 'Nauru Government', url: 'https://www.naurugov.nr/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13, 17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-tuvalu-govt', organization: 'Tuvalu Government', url: 'https://www.tuvaluislands.com/government/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13, 17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-niue-govt', organization: 'Niue Government', url: 'https://www.gov.nu/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-cookislands-govt', organization: 'Cook Islands Government', url: 'https://www.mfaici.gov.ck/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-nz-mfat', organization: 'New Zealand MFAT', url: 'https://www.mfat.govt.nz/en/aid-and-development/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-au-dfat', organization: 'Australia DFAT Pacific', url: 'https://www.dfat.gov.au/news/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Pacific', language: 'en', requires_auth: false },

  // ── Pacific Regional Health ────────────────────────────────────────────────
  { id: 'pac-who-wpro', organization: 'WHO Western Pacific', url: 'https://www.who.int/westernpacific/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-pho-events', organization: 'Pacific Public Health Surveillance', url: 'https://www.spc.int/phs/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-phap-events', organization: 'Pacific Health Advisory Panel', url: 'https://www.pacifichealthsummit.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-ohchr-pacific', organization: 'OHCHR Pacific', url: 'https://www.ohchr.org/en/countries/pacific', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-unicef-pacific', organization: 'UNICEF Pacific', url: 'https://www.unicef.org/pacificislands/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-undp-pacific', organization: 'UNDP Pacific', url: 'https://www.undp.org/pacific/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-unfpa-pacific', organization: 'UNFPA Pacific', url: 'https://pacific.unfpa.org/en/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3, 5], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-hiv-pacific', organization: 'Pacific HIV Programme', url: 'https://www.unaids.org/en/regionscountries/regions/asiapacific', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3], region: 'Pacific', language: 'en', requires_auth: false },

  // ── Pacific Climate ────────────────────────────────────────────────────────
  { id: 'pac-sprep-events', organization: 'SPREP Pacific Environment', url: 'https://www.sprep.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [13, 14], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-gcf-pacific', organization: 'GCF Pacific', url: 'https://www.greenclimate.fund/countries/pacific', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-coalition-islands', organization: 'Pacific Coalition Climate', url: 'https://www.pccsp.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-pccsp-events', organization: 'Pacific Climate Change Science', url: 'https://www.pacificclimatechangecentre.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-pwsc-events', organization: 'Pacific Water and Sanitation', url: 'https://www.oecd.org/oceania/topics/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [6, 13], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-rising-nations', organization: 'Rising Nations Climate', url: 'https://www.risingnations.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-pifs-climate', organization: 'PIFS Climate Finance', url: 'https://www.forumsec.org/climate/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13, 17], region: 'Pacific', language: 'en', requires_auth: false },

  // ── Pacific Education ──────────────────────────────────────────────────────
  { id: 'pac-usp-events', organization: 'University of the South Pacific', url: 'https://www.usp.ac.fj/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-pnguot-events', organization: 'PNG University of Technology', url: 'https://www.unitech.ac.pg/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 9], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-pace-net', organization: 'PACE Pacific Education', url: 'https://www.pace-net.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-un-escap-pacific', organization: 'ESCAP Pacific', url: 'https://www.unescap.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-proe-events', organization: 'PROE Pacific Regional Organization', url: 'https://www.proe.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Pacific', language: 'en', requires_auth: false },

  // ── Pacific Youth ──────────────────────────────────────────────────────────
  { id: 'pac-pif-youth', organization: 'Pacific Youth Forum', url: 'https://www.forumsec.org/youth/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 8], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-pycf-events', organization: 'Pacific Youth Climate Forum', url: 'https://www.pacificyouthclimate.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13, 4], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-pasai-events', organization: 'PASAI Pacific Audit', url: 'https://www.pasai.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16, 17], region: 'Pacific', language: 'en', requires_auth: false },

  // ── Australian and New Zealand Civil Society ──────────────────────────────
  { id: 'pac-acfid-events', organization: 'ACFID Australia', url: 'https://www.acfid.asn.au/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-council-intl-dev-nz', organization: 'CID New Zealand', url: 'https://www.cid.org.nz/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-oxfam-aus', organization: 'Oxfam Australia', url: 'https://www.oxfam.org.au/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-actionaid-aus', organization: 'ActionAid Australia', url: 'https://www.actionaid.org.au/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1, 5], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-care-aus', organization: 'CARE Australia', url: 'https://www.care.org.au/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1, 5], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-plan-aus', organization: 'Plan International Australia', url: 'https://www.plan.org.au/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 5], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-worldvision-aus', organization: 'World Vision Australia', url: 'https://www.worldvision.com.au/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1, 3], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-anu-events', organization: 'ANU Development Policy', url: 'https://devpolicy.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17, 8], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-lowy-events', organization: 'Lowy Institute', url: 'https://www.lowyinstitute.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16, 17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-aspi-events', organization: 'ASPI Strategic Policy', url: 'https://www.aspi.org.au/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-sydney-events', organization: 'University of Sydney Pacific', url: 'https://www.sydney.edu.au/news-opinion/events.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-auckland-events', organization: 'University of Auckland Pacific', url: 'https://www.auckland.ac.nz/en/news/events.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-victoria-events', organization: 'Victoria University Wellington', url: 'https://www.wgtn.ac.nz/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 17], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-monash-events', organization: 'Monash University Pacific Studies', url: 'https://www.monash.edu/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Pacific', language: 'en', requires_auth: false },

  // ── Pacific Ocean and Marine ──────────────────────────────────────────────
  { id: 'pac-pcreef-events', organization: 'Pacific Community Reef Summit', url: 'https://www.spc.int/coastfish/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [14], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-ffa-events', organization: 'Pacific FFA Fisheries', url: 'https://www.ffa.int/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [14, 2], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-piofs-events', organization: 'Pacific Islands Ocean Forum', url: 'https://www.forumsec.org/ocean/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [14, 13], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-niwa-events', organization: 'NIWA New Zealand', url: 'https://www.niwa.co.nz/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [14, 13], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pac-aim-marine', organization: 'AIMS Australian Marine', url: 'https://www.aims.gov.au/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [14], region: 'Pacific', language: 'en', requires_auth: false },
];
