import type { ScraperSource } from './types';

export const SOURCES_EDUCATION: ScraperSource[] = [

  // ── UNESCO ──────────────────────────────────────────────────────────────────
  { id: 'edu-unesco-events', organization: 'UNESCO', url: 'https://www.unesco.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [4, 17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-unesco-education', organization: 'UNESCO Education', url: 'https://www.unesco.org/en/education', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-unesco-iiep', organization: 'UNESCO IIEP', url: 'https://iiep.unesco.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-unesco-uil', organization: 'UNESCO UIL', url: 'https://uil.unesco.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-unesco-uis', organization: 'UNESCO UIS', url: 'https://uis.unesco.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-unesco-ibe', organization: 'UNESCO IBE', url: 'https://www.ibe.unesco.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-unesco-hefp', organization: 'UNESCO Higher Education', url: 'https://www.unesco.org/en/education/higher-education', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-unesco-gemreport', organization: 'UNESCO GEM Report', url: 'https://www.education-progress.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-wed', organization: 'World Education Day', url: 'https://www.unesco.org/en/days/education', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-unesco-africa', organization: 'UNESCO Africa Education', url: 'https://www.unesco.org/en/fieldoffice/dakar', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Africa', language: 'en', requires_auth: false },

  // ── Global Education Partnerships ──────────────────────────────────────────
  { id: 'edu-gpe-events', organization: 'Global Partnership for Education', url: 'https://www.globalpartnership.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-ecw-events', organization: 'Education Cannot Wait', url: 'https://www.educationcannotwait.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-efa-events', organization: 'Education for All', url: 'https://www.right-to-education.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-ciff-events', organization: "Children's Investment Fund Foundation", url: 'https://ciff.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-ukaid-education', organization: 'UK FCDO Education', url: 'https://www.gov.uk/government/organisations/foreign-commonwealth-development-office', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-usaid-education', organization: 'USAID Education', url: 'https://www.usaid.gov/education', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-worldbank-education', organization: 'World Bank Education', url: 'https://www.worldbank.org/en/topic/education/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-adb-education', organization: 'ADB Education', url: 'https://www.adb.org/sectors/education/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Asia-Pacific', language: 'en', requires_auth: false },
  { id: 'edu-aga-khan', organization: 'Aga Khan Foundation Education', url: 'https://www.akdn.org/our-agencies/aga-khan-foundation', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-room-to-read', organization: 'Room to Read', url: 'https://www.roomtoread.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },

  // ── Regional Education Bodies ──────────────────────────────────────────────
  { id: 'edu-aau-events', organization: 'Association of African Universities', url: 'https://www.aau.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'edu-seameo-events', organization: 'SEAMEO', url: 'https://www.seameo.org/SeameoWeb2/index.php/component/k2/item', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'edu-iau-events', organization: 'Int. Association of Universities', url: 'https://www.iau-aiu.net/Events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-ace-events', organization: 'Association of Commonwealth Universities', url: 'https://www.acu.ac.uk/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-eua-events', organization: 'European University Association', url: 'https://eua.eu/events.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'edu-apru-events', organization: 'Asia Pacific Research Universities', url: 'https://apru.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Asia-Pacific', language: 'en', requires_auth: false },
  { id: 'edu-sarua-events', organization: 'SARUA', url: 'https://www.sarua.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Africa-Southern', language: 'en', requires_auth: false },
  { id: 'edu-acenet-events', organization: 'ACENET', url: 'https://www.ace-net.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Americas-Caribbean', language: 'en', requires_auth: false },
  { id: 'edu-caricom-education', organization: 'CARICOM Education', url: 'https://caricom.org/education/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Americas-Caribbean', language: 'en', requires_auth: false },
  { id: 'edu-andean-education', organization: 'Andean Community Education', url: 'https://www.comunidadandina.org/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Americas-Latin', language: 'es', requires_auth: false },

  // ── Higher Education Conferences ───────────────────────────────────────────
  { id: 'edu-wche-events', organization: 'World Conference on Higher Education', url: 'https://www.iesalc.unesco.org/en/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-nacac-events', organization: 'NACAC', url: 'https://www.nacacnet.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'edu-aacrao-events', organization: 'AACRAO', url: 'https://www.aacrao.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'edu-nafsa-events', organization: 'NAFSA', url: 'https://www.nafsa.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 17], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'edu-eaie-events', organization: 'EAIE', url: 'https://www.eaie.org/events.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'edu-apaie-events', organization: 'APAIE', url: 'https://www.apaie.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Asia-Pacific', language: 'en', requires_auth: false },
  { id: 'edu-aiea-events', organization: 'AIEA', url: 'https://www.aiea.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-unimed-events', organization: 'UNIMED', url: 'https://www.unimed.eu/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Europe-South', language: 'en', requires_auth: false },
  { id: 'edu-conahec-events', organization: 'CONAHEC', url: 'https://www.conahec.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'edu-qs-rankings', organization: 'QS World University Events', url: 'https://www.qs.com/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },

  // ── EdTech and Innovation ──────────────────────────────────────────────────
  { id: 'edu-iste-events', organization: 'ISTE', url: 'https://www.iste.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 9], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'edu-bett-events', organization: 'Bett', url: 'https://www.bettshow.com/bett-2025', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 9], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'edu-educause-events', organization: 'EDUCAUSE', url: 'https://www.educause.edu/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 9], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'edu-lak-events', organization: 'Learning Analytics', url: 'https://www.solaresearch.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 9], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-edtech-summit', organization: 'EdTech Summit', url: 'https://edtechsummit.com/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-sxswedu-events', organization: 'SXSW Edu', url: 'https://www.sxswedu.com/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'edu-ash-institute', organization: 'Ash Institute Education', url: 'https://ash.harvard.edu/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 16], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'edu-gemini', organization: 'Gemini Education Forum', url: 'https://www.gemini-project.eu/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'edu-worldedweek', organization: 'World Education Week', url: 'https://www.worldeducationweek.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-aect-events', organization: 'AECT', url: 'https://www.aect.org/events.php', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Americas-North', language: 'en', requires_auth: false },

  // ── Universities – Africa ──────────────────────────────────────────────────
  { id: 'edu-uct-events', organization: 'University of Cape Town', url: 'https://www.uct.ac.za/news-and-events/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Africa-Southern', language: 'en', requires_auth: false },
  { id: 'edu-makerere-events', organization: 'Makerere University', url: 'https://www.mak.ac.ug/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'edu-ug-events', organization: 'University of Ghana', url: 'https://www.ug.edu.gh/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Africa-West', language: 'en', requires_auth: false },
  { id: 'edu-wits-events', organization: 'University of the Witwatersrand', url: 'https://www.wits.ac.za/news/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Africa-Southern', language: 'en', requires_auth: false },
  { id: 'edu-unnairobi-events', organization: 'University of Nairobi', url: 'https://www.uonbi.ac.ke/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'edu-stellenbosch-events', organization: 'Stellenbosch University', url: 'https://www.sun.ac.za/english/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Africa-Southern', language: 'en', requires_auth: false },
  { id: 'edu-ibadan-events', organization: 'University of Ibadan', url: 'https://www.ui.edu.ng/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Africa-West', language: 'en', requires_auth: false },
  { id: 'edu-aku-events', organization: 'Aga Khan University', url: 'https://www.aku.edu/news/pages/events.aspx', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 3], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'edu-auc-events', organization: 'American University in Cairo', url: 'https://www.aucegypt.edu/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Africa-North', language: 'en', requires_auth: false },
  { id: 'edu-um6p-events', organization: 'UM6P Morocco', url: 'https://um6p.ma/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Africa-North', language: 'en', requires_auth: false },

  // ── Universities – Asia ────────────────────────────────────────────────────
  { id: 'edu-nus-events', organization: 'NUS', url: 'https://nus.edu.sg/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'edu-ntu-events', organization: 'Nanyang Technological University', url: 'https://www.ntu.edu.sg/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'edu-iit-events', organization: 'IIT Delhi', url: 'https://home.iitd.ac.in/events.php', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 9], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'edu-peking-events', organization: 'Peking University', url: 'https://english.pku.edu.cn/news_events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Asia-East', language: 'en', requires_auth: false },
  { id: 'edu-utokyo-events', organization: 'University of Tokyo', url: 'https://www.u-tokyo.ac.jp/en/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Asia-East', language: 'en', requires_auth: false },
  { id: 'edu-aub-events', organization: 'American University of Beirut', url: 'https://www.aub.edu.lb/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Middle-East', language: 'en', requires_auth: false },
  { id: 'edu-ku-events', organization: 'Kabul University', url: 'https://ku.edu.af/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'edu-dhaka-events', organization: 'University of Dhaka', url: 'https://www.du.ac.bd/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'edu-kaust-events', organization: 'KAUST', url: 'https://www.kaust.edu.sa/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 9], region: 'Middle-East', language: 'en', requires_auth: false },
  { id: 'edu-usp-events', organization: 'University of the South Pacific', url: 'https://www.usp.ac.fj/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Pacific', language: 'en', requires_auth: false },

  // ── Universities – Latin America ───────────────────────────────────────────
  { id: 'edu-unam-events', organization: 'UNAM Mexico', url: 'https://www.unam.mx/eventos', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'edu-tec-events', organization: 'Tec de Monterrey', url: 'https://tec.mx/es/agenda', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'edu-usp-brazil-events', organization: 'University of São Paulo', url: 'https://www5.usp.br/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Americas-Latin', language: 'pt', requires_auth: false },
  { id: 'edu-uba-events', organization: 'University of Buenos Aires', url: 'https://www.uba.ar/contenido/1040', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'edu-flacso-events', organization: 'FLACSO', url: 'https://www.flacso.org/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 16], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'edu-redalyc-events', organization: 'Redalyc', url: 'https://www.redalyc.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Americas-Latin', language: 'es', requires_auth: false },

  // ── Universities – Europe ──────────────────────────────────────────────────
  { id: 'edu-oxford-events', organization: 'University of Oxford', url: 'https://www.ox.ac.uk/news-and-events/events-for-the-public', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'edu-cambridge-events', organization: 'University of Cambridge', url: 'https://www.cam.ac.uk/news-and-events/upcoming-events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'edu-lse-events', organization: 'London School of Economics', url: 'https://www.lse.ac.uk/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 16], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'edu-ki-events', organization: 'Karolinska Institutet', url: 'https://ki.se/en/news/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 3], region: 'Europe-Nordic', language: 'en', requires_auth: false },
  { id: 'edu-lshtm-events', organization: 'LSHTM', url: 'https://www.lshtm.ac.uk/newsevents/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 3], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'edu-sorbonne-events', organization: 'Sorbonne University', url: 'https://www.sorbonne-universite.fr/en/agenda', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Europe', language: 'fr', requires_auth: false },
  { id: 'edu-heidelberg-events', organization: 'Heidelberg University', url: 'https://www.uni-heidelberg.de/en/news/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'edu-eth-events', organization: 'ETH Zurich', url: 'https://ethz.ch/en/news-and-events/events.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 9], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'edu-uw-events', organization: 'University of Warsaw', url: 'https://en.uw.edu.pl/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Europe-East', language: 'en', requires_auth: false },

  // ── Universities – North America ───────────────────────────────────────────
  { id: 'edu-harvard-events', organization: 'Harvard Kennedy School', url: 'https://www.hks.harvard.edu/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 16], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'edu-columbia-events', organization: 'Columbia SIPA', url: 'https://sipa.columbia.edu/news-insights/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 16], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'edu-jhu-events', organization: 'Johns Hopkins SAIS', url: 'https://sais.jhu.edu/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 3], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'edu-stanford-education', organization: 'Stanford GSE', url: 'https://gse.stanford.edu/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'edu-mit-events', organization: 'MIT Educational Technology', url: 'https://events.mit.edu/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 9], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'edu-mcgill-events', organization: 'McGill University', url: 'https://www.mcgill.ca/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'edu-toronto-events', organization: 'University of Toronto', url: 'https://www.utoronto.ca/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Americas-North', language: 'en', requires_auth: false },

  // ── Skills and Vocational Training ────────────────────────────────────────
  { id: 'edu-ilo-skills', organization: 'ILO Skills and Employability', url: 'https://www.ilo.org/global/topics/skills-knowledge-and-employability/lang--en/index.htm', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 8], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-tvsd-forum', organization: 'TVET Forum', url: 'https://unevoc.unesco.org/home/Events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 8], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-worldskills', organization: 'WorldSkills', url: 'https://worldskills.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 8], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-etf-events', organization: 'European Training Foundation', url: 'https://www.etf.europa.eu/en/news-and-events/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 8], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'edu-g20-education', organization: 'G20 Education', url: 'https://www.g20.org/en/tracks/sherpa/education', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-inclusive-edu', organization: 'Inclusive Education Initiative', url: 'https://www.inclusive-education-initiative.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-uis-forum', organization: 'UNESCO Data for SDG 4', url: 'https://tcg.uis.unesco.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },

  // ── Education Research & Policy ────────────────────────────────────────────
  { id: 'edu-comparative-edu', organization: 'Comparative Education Society', url: 'https://www.cesa-online.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-aera-events', organization: 'AERA', url: 'https://www.aera.net/Events-Meetings/Annual-Meeting', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'edu-cies-events', organization: 'CIES', url: 'https://cies.us/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-r4d-education', organization: 'Results for Development Education', url: 'https://www.r4d.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-brookings-education', organization: 'Brookings Education', url: 'https://www.brookings.edu/events/?topic=education', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'edu-jpal-events', organization: 'J-PAL Education', url: 'https://www.povertyactionlab.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-ies-events', organization: 'Institute of Education Sciences', url: 'https://ies.ed.gov/conferences/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'edu-epdc-events', organization: 'Education Policy Data Center', url: 'https://epdc.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-rise-program', organization: 'RISE Education Programme', url: 'https://www.riseprogramme.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-odi-education', organization: 'ODI Education', url: 'https://odi.org/en/events/?q=education', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },

  // ── African National Education Ministries ──────────────────────────────────
  { id: 'edu-ke-education', organization: 'Ministry of Education Kenya', url: 'https://www.education.go.ke/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'edu-tz-education', organization: 'MoEST Tanzania', url: 'https://www.moe.go.tz/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'edu-ug-education', organization: 'MoES Uganda', url: 'https://www.education.go.ug/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'edu-et-education', organization: 'MoE Ethiopia', url: 'https://moe.gov.et/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'edu-gh-education', organization: 'Ghana Education Service', url: 'https://www.ges.gov.gh/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Africa-West', language: 'en', requires_auth: false },
  { id: 'edu-ng-education', organization: 'Federal Ministry of Education Nigeria', url: 'https://www.education.gov.ng/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Africa-West', language: 'en', requires_auth: false },
  { id: 'edu-sn-education', organization: 'MEN Sénégal', url: 'https://www.education.gouv.sn/actualites/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Africa-West', language: 'fr', requires_auth: false },
  { id: 'edu-ci-education', organization: 'MEN Côte d\'Ivoire', url: 'https://www.men.gouv.ci/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Africa-West', language: 'fr', requires_auth: false },
  { id: 'edu-cm-education', organization: 'MINEDUB Cameroon', url: 'https://www.minedub.cm/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Africa-Central', language: 'fr', requires_auth: false },
  { id: 'edu-rw-education', organization: 'REB Rwanda', url: 'https://www.reb.rw/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'edu-zw-education', organization: 'Ministry of Education Zimbabwe', url: 'https://www.mopse.co.zw/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Africa-Southern', language: 'en', requires_auth: false },
  { id: 'edu-zm-education', organization: 'Ministry of Education Zambia', url: 'https://www.moge.gov.zm/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Africa-Southern', language: 'en', requires_auth: false },
  { id: 'edu-mz-education', organization: 'MINED Mozambique', url: 'https://www.mined.gov.mz/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Africa-Southern', language: 'pt', requires_auth: false },
  { id: 'edu-ao-education', organization: 'MED Angola', url: 'https://www.med.gov.ao/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Africa-Southern', language: 'pt', requires_auth: false },
  { id: 'edu-ma-education', organization: 'MENESRS Morocco', url: 'https://www.men.gov.ma/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Africa-North', language: 'fr', requires_auth: false },
  { id: 'edu-eg-education', organization: 'Ministry of Education Egypt', url: 'https://www.moe.gov.eg/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Africa-North', language: 'ar', requires_auth: false },
  { id: 'edu-tn-education', organization: 'Ministère de l\'Éducation Tunisie', url: 'https://www.education.gov.tn/actualites/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Africa-North', language: 'fr', requires_auth: false },
  { id: 'edu-drc-education', organization: 'METP DRC', url: 'https://www.eduquepsp.cd/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Africa-Central', language: 'fr', requires_auth: false },
  { id: 'edu-ml-education', organization: 'MEN Mali', url: 'https://www.men-mali.education/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Africa-West', language: 'fr', requires_auth: false },
  { id: 'edu-sa-education', organization: 'DBE South Africa', url: 'https://www.education.gov.za/events.aspx', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Africa-Southern', language: 'en', requires_auth: false },

  // ── Asian National Education Ministries ────────────────────────────────────
  { id: 'edu-id-kemendikbud', organization: 'Kemendikbud Indonesia', url: 'https://www.kemdikbud.go.id/main/event', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'edu-ph-deped', organization: 'DepEd Philippines', url: 'https://www.deped.gov.ph/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'edu-th-obec', organization: 'OBEC Thailand', url: 'https://www.obec.go.th/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'edu-vn-moet', organization: 'MOET Vietnam', url: 'https://moet.gov.vn/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'edu-my-moe', organization: 'MOE Malaysia', url: 'https://www.moe.gov.my/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'edu-mm-moetk', organization: 'MoETK Myanmar', url: 'https://www.moetk.gov.mm/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'edu-kh-moeys', organization: 'MOEYS Cambodia', url: 'https://www.moeys.gov.kh/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'edu-la-moes', organization: 'MoES Laos', url: 'https://www.moe.gov.la/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'edu-pk-mofept', organization: 'MoFEPT Pakistan', url: 'https://www.mofept.gov.pk/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'edu-bd-moedu', organization: 'MoEdu Bangladesh', url: 'https://www.moedu.gov.bd/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'edu-np-moe-nepal', organization: 'MoE Nepal', url: 'https://www.moe.gov.np/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'edu-mn-mecs', organization: 'MECS Mongolia', url: 'https://mec.gov.mn/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Asia-East', language: 'en', requires_auth: false },

  // ── Distance and Open Learning ─────────────────────────────────────────────
  { id: 'edu-icde-events', organization: 'ICDE', url: 'https://www.icde.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-open-university', organization: 'Open University UK', url: 'https://www.open.ac.uk/about/main/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'edu-commonwealth-dl', organization: 'Commonwealth of Learning', url: 'https://www.col.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-aou-events', organization: 'Arab Open University', url: 'https://www.aou.edu.kw/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Middle-East', language: 'ar', requires_auth: false },
  { id: 'edu-ignou-events', organization: 'IGNOU India', url: 'https://www.ignou.ac.in/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'edu-ou-africa', organization: 'Open University Africa', url: 'https://www.openuniversity.edu.ng/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Africa', language: 'en', requires_auth: false },

  // ── Early Childhood Education ──────────────────────────────────────────────
  { id: 'edu-omep-events', organization: 'OMEP', url: 'https://www.worldomep.org/en/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-bvlf-events', organization: 'Bernard van Leer Foundation', url: 'https://bernardvanleer.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-ece-forum', organization: 'ECE Forum', url: 'https://www.naeyc.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'edu-step-by-step', organization: 'Step by Step Foundation', url: 'https://www.stepbystep.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-aga-khan-ece', organization: 'Aga Khan ECE', url: 'https://www.akdn.org/education', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },

  // ── Girls Education ────────────────────────────────────────────────────────
  { id: 'edu-camfed-events', organization: 'CAMFED', url: 'https://camfed.org/news-events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 5], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'edu-forum-girls-education', organization: 'Forum for African Women Educationalists', url: 'https://fawe.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 5], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'edu-equalaccess', organization: 'Equal Access International', url: 'https://www.equalaccess.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-agp-events', organization: 'Alliance for Girls Education', url: 'https://allianceforgirlseducation.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-educate-girls', organization: 'Educate Girls', url: 'https://www.educategirls.ngo/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 5], region: 'Asia-South', language: 'en', requires_auth: false },

  // ── Literacy and Adult Education ───────────────────────────────────────────
  { id: 'edu-uil-confintea', organization: 'UIL CONFINTEA', url: 'https://uil.unesco.org/confintea/confintea-vii', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-literacy-world', organization: 'Literacy World Conference', url: 'https://www.ila.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-dvv-international', organization: 'DVV International', url: 'https://www.dvv-international.de/en/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },

  // ── Education in Emergencies ───────────────────────────────────────────────
  { id: 'edu-inee-events', organization: 'INEE', url: 'https://inee.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-ecw-conference', organization: 'ECW Conference', url: 'https://www.educationcannotwait.org/news-and-events/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-save-children-edu', organization: 'Save the Children Education', url: 'https://www.savethechildren.net/education', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-unicef-eie', organization: 'UNICEF Education in Emergencies', url: 'https://www.unicef.org/education/education-emergencies', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },

  // ── Education Finance ──────────────────────────────────────────────────────
  { id: 'edu-ifc-education', organization: 'IFC Education Finance', url: 'https://www.ifc.org/en/sector/education', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 8], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-ies-finance', organization: 'Education Finance Network', url: 'https://efn.international/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-efa-data-conference', organization: 'EFA Data Conference', url: 'https://uis.unesco.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },

  // ── Special Needs and Inclusive Education ──────────────────────────────────
  { id: 'edu-isec-events', organization: 'ISEC Inclusive Education', url: 'https://www.isec2025.com/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-ahead-events', organization: 'AHEAD', url: 'https://www.ahead.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 10], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'edu-right-to-education', organization: 'Right to Education Initiative', url: 'https://www.right-to-education.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'edu-ged-events', organization: 'Global Education and Disability', url: 'https://www.lightfortheworld.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 10], region: 'Global', language: 'en', requires_auth: false },

  // ── African Universities (more) ────────────────────────────────────────────
  { id: 'edu-kwame-nkrumah', organization: 'KNUST Ghana', url: 'https://www.knust.edu.gh/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 9], region: 'Africa-West', language: 'en', requires_auth: false },
  { id: 'edu-lagos-events', organization: 'University of Lagos', url: 'https://unilag.edu.ng/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Africa-West', language: 'en', requires_auth: false },
  { id: 'edu-obafemi-events', organization: 'OAU Ile-Ife', url: 'https://www.oauife.edu.ng/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Africa-West', language: 'en', requires_auth: false },
  { id: 'edu-dar-events', organization: 'University of Dar es Salaam', url: 'https://www.udsm.ac.tz/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'edu-addis-events', organization: 'Addis Ababa University', url: 'https://www.aau.edu.et/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'edu-cheikh-anta', organization: 'UCAD Dakar', url: 'https://www.ucad.sn/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Africa-West', language: 'fr', requires_auth: false },
  { id: 'edu-unilag-eg-events', organization: 'Cairo University', url: 'https://cu.edu.eg/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Africa-North', language: 'ar', requires_auth: false },
];
