import type { ScraperSource } from './types';

export const SOURCES_ASIA: ScraperSource[] = [
  // ── WHO SEARO MEMBER STATE MINISTRIES ─────────────────────────────────────

  { id: 'moh-bd', organization: 'Ministry of Health Bangladesh', url: 'https://www.mohfw.gov.bd', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'South-Asia', language: 'en', requires_auth: false },
  { id: 'moh-bt', organization: 'Ministry of Health Bhutan', url: 'https://www.health.gov.bt', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'South-Asia', language: 'en', requires_auth: false },
  { id: 'moh-in', organization: 'Ministry of Health India', url: 'https://www.mohfw.gov.in', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'South-Asia', language: 'en', requires_auth: false },
  { id: 'moh-id', organization: 'Ministry of Health Indonesia', url: 'https://www.kemkes.go.id', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'moh-mv', organization: 'Ministry of Health Maldives', url: 'https://health.gov.mv', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'South-Asia', language: 'en', requires_auth: false },
  { id: 'moh-mm', organization: 'Ministry of Health Myanmar', url: 'https://www.mohs.gov.mm', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'moh-np', organization: 'Ministry of Health Nepal', url: 'https://www.mohp.gov.np', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'South-Asia', language: 'en', requires_auth: false },
  { id: 'moh-lk', organization: 'Ministry of Health Sri Lanka', url: 'https://www.health.gov.lk', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'South-Asia', language: 'en', requires_auth: false },
  { id: 'moh-th', organization: 'Ministry of Public Health Thailand', url: 'https://www.moph.go.th', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'moh-tl', organization: 'Ministry of Health Timor-Leste', url: 'https://www.moh.gov.tl', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-Southeast', language: 'en', requires_auth: false },

  // ── WHO WPRO MEMBER STATE MINISTRIES ──────────────────────────────────────

  { id: 'moh-au', organization: 'Department of Health Australia', url: 'https://www.health.gov.au', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-Pacific', language: 'en', requires_auth: false },
  { id: 'moh-bn', organization: 'Ministry of Health Brunei', url: 'https://www.moh.gov.bn', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'moh-kh', organization: 'Ministry of Health Cambodia', url: 'https://www.moh.gov.kh', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'moh-cn', organization: 'National Health Commission China', url: 'https://www.nhc.gov.cn', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-East', language: 'en', requires_auth: false },
  { id: 'moh-fj', organization: 'Ministry of Health Fiji', url: 'https://www.health.gov.fj', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'moh-jp', organization: 'Ministry of Health Japan', url: 'https://www.mhlw.go.jp/english/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-East', language: 'en', requires_auth: false },
  { id: 'moh-ki', organization: 'Ministry of Health Kiribati', url: 'https://www.health.gov.ki', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'moh-la', organization: 'Ministry of Health Laos', url: 'https://www.moh.gov.la', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'moh-my', organization: 'Ministry of Health Malaysia', url: 'https://www.moh.gov.my', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'moh-mh', organization: 'Ministry of Health Marshall Islands', url: 'https://www.moh.gov.mh', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'moh-fm', organization: 'Department of Health FSM', url: 'https://www.fsmhealth.fm', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'moh-mn', organization: 'Ministry of Health Mongolia', url: 'https://www.moh.gov.mn', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-East', language: 'en', requires_auth: false },
  { id: 'moh-nz', organization: 'Ministry of Health New Zealand', url: 'https://www.health.govt.nz', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-Pacific', language: 'en', requires_auth: false },
  { id: 'moh-pg', organization: 'Department of Health Papua New Guinea', url: 'https://www.health.gov.pg', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'moh-ph', organization: 'Department of Health Philippines', url: 'https://www.doh.gov.ph', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'moh-kr', organization: 'Ministry of Health Republic of Korea', url: 'https://www.mohw.go.kr/eng/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-East', language: 'en', requires_auth: false },
  { id: 'moh-ws', organization: 'Ministry of Health Samoa', url: 'https://www.health.gov.ws', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'moh-sb', organization: 'Ministry of Health Solomon Islands', url: 'https://www.moh.gov.sb', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'moh-vu', organization: 'Ministry of Health Vanuatu', url: 'https://www.health.gov.vu', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'moh-vn', organization: 'Ministry of Health Vietnam', url: 'https://moh.gov.vn/en_US/web/guest/home', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-Southeast', language: 'en', requires_auth: false },


  // ── SOUTH AND SOUTHEAST ASIAN BODIES ─────────────────────────────────────

  { id: 'saarc-tb-events', organization: 'SAARC Tuberculosis and HIV Centre', url: 'https://www.stbhc.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'South-Asia', language: 'en', requires_auth: false },
  { id: 'asean-health-events', organization: 'ASEAN Health Ministers Meetings', url: 'https://asean.org/asean-socio-cultural/asean-health-ministers-meeting/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 17], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'aplma-events', organization: 'Asia Pacific Leaders Malaria Alliance (APLMA)', url: 'https://aplma.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-Pacific', language: 'en', requires_auth: false },
  { id: 'apacph-events', organization: 'Asia-Pacific Academic Consortium for Public Health (APACPH)', url: 'https://www.apacph.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Asia-Pacific', language: 'en', requires_auth: false },
  { id: 'icddrb-events', organization: 'icddr,b Bangladesh', url: 'https://www.icddrb.org/news-and-events/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'South-Asia', language: 'en', requires_auth: false },
  { id: 'brac-events', organization: 'BRAC Bangladesh', url: 'https://www.brac.net/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 3, 4], region: 'South-Asia', language: 'en', requires_auth: false },
  { id: 'phfi-events', organization: 'Public Health Foundation of India (PHFI)', url: 'https://www.phfi.org/news-events/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'South-Asia', language: 'en', requires_auth: false },
  { id: 'icmr-events', organization: 'Indian Council of Medical Research (ICMR)', url: 'https://www.icmr.gov.in/events.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'South-Asia', language: 'en', requires_auth: false },
  { id: 'aiims-events', organization: 'All India Institute of Medical Sciences (AIIMS)', url: 'https://www.aiims.edu/en/events.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'South-Asia', language: 'en', requires_auth: false },
  { id: 'nie-india-events', organization: 'National Institute of Epidemiology India', url: 'https://nie.gov.in/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'South-Asia', language: 'en', requires_auth: false },
  { id: 'phai-events', organization: 'Public Health Association of India (PHAI)', url: 'https://www.phai.in/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'South-Asia', language: 'en', requires_auth: false },
  { id: 'hai-asiapac-events', organization: 'Health Action International Asia-Pacific', url: 'https://haiweb.org/region/asia-pacific/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-Pacific', language: 'en', requires_auth: false },
  { id: 'mahidol-events', organization: 'Mahidol University Thailand', url: 'https://www.mahidol.ac.th/en/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'chula-events', organization: 'Chulalongkorn University Thailand', url: 'https://www.chula.ac.th/en/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'upmanila-events', organization: 'University of the Philippines Manila', url: 'https://www.upm.edu.ph/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'um-malaysia-events', organization: 'University of Malaya', url: 'https://www.um.edu.my/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'nus-sph-events', organization: 'NUS Saw Swee Hock School of Public Health', url: 'https://sph.nus.edu.sg/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'duke-nus-events', organization: 'Duke-NUS Medical School Singapore', url: 'https://www.duke-nus.edu.sg/research/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'indonesia-pha-events', organization: 'Indonesia Public Health Association', url: 'https://iakmi.or.id/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'vpha-events', organization: 'Vietnamese Public Health Association', url: 'https://vpha.vn/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'mma-events', organization: 'Myanmar Medical Association', url: 'https://www.mma.org.mm/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'slma-events', organization: 'Sri Lanka Medical Association', url: 'https://www.slma.lk/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'South-Asia', language: 'en', requires_auth: false },
  { id: 'nepha-events', organization: 'Nepal Public Health Association', url: 'https://nepha.org.np/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'South-Asia', language: 'en', requires_auth: false },
  { id: 'pakpha-events', organization: 'Pakistan Public Health Association', url: 'https://www.pakpha.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'South-Asia', language: 'en', requires_auth: false },
  { id: 'seameo-events', organization: 'Southeast Asian Ministers of Education Organization (SEAMEO)', url: 'https://www.seameo.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'hmu-hanoi-events', organization: 'Hanoi Medical University Vietnam', url: 'https://hmu.edu.vn/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'udhaka-events', organization: 'University of Dhaka', url: 'https://www.du.ac.bd/news/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'South-Asia', language: 'en', requires_auth: false },
  { id: 'iphec-events', organization: 'International Public Health and Environment Conference', url: 'https://www.iphec.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 13], region: 'Asia-Pacific', language: 'en', requires_auth: false },
  { id: 'sas-india-events', organization: 'Centre for Health Research and Development (Society for Applied Studies)', url: 'https://www.sas.org.in/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'South-Asia', language: 'en', requires_auth: false },


  // ── PACIFIC ISLANDS BODIES ────────────────────────────────────────────────

  { id: 'spc-health-events', organization: 'Pacific Community (SPC) Health', url: 'https://www.spc.int/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pifs-events', organization: 'Pacific Islands Forum Secretariat', url: 'https://www.forumsec.org/calendar/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17, 16], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'sprep-events', organization: 'Secretariat of the Pacific Regional Environment Programme (SPREP)', url: 'https://www.sprep.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [13, 14, 15], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pphm-events', organization: 'Pacific Health Ministers Meetings', url: 'https://www.phm.org.fj/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pphsn-events', organization: 'Pacific Public Health Surveillance Network (PPHSN)', url: 'https://www.pphsn.net/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'usp-pacific-events', organization: 'University of the South Pacific (USP)', url: 'https://www.usp.ac.fj/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'upng-events', organization: 'University of Papua New Guinea', url: 'https://www.upng.ac.pg/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'piph-events', organization: 'Pacific Institute of Public Health', url: 'https://www.piph.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'fnu-events', organization: 'Fiji National University', url: 'https://www.fnu.ac.fj/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pdf-pacific-events', organization: 'Pacific Disabilities Forum', url: 'https://www.pacificdisabilitiesforum.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10, 3], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'forum-fisheries-events', organization: 'Forum Fisheries Agency', url: 'https://www.ffa.int/news_events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [14, 2], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'spc-foodsec-events', organization: 'Pacific Community Food Security', url: 'https://www.spc.int/lrd/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pacific-women-events', organization: 'Pacific Women DFAT-funded', url: 'https://pacificwomen.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Pacific', language: 'en', requires_auth: false },
  { id: 'pdp-pacific-events', organization: 'Partnerships for Development in the Pacific (PDP)', url: 'https://www.pdp.org.fj/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Pacific', language: 'en', requires_auth: false },


  { id: 'moh-kz', organization: 'Ministry of Health — Kazakhstan', url: 'https://www.gov.kz/memleket/entities/dsm/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-Central', language: 'en', requires_auth: false },
  { id: 'moh-uz', organization: 'Ministry of Health — Uzbekistan', url: 'https://minzdrav.uz/ru/activities/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-Central', language: 'en', requires_auth: false },
  { id: 'moh-kg', organization: 'Ministry of Health — Kyrgyzstan', url: 'https://minzdrav.gov.kg/ru/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-Central', language: 'en', requires_auth: false },
  { id: 'moh-tj', organization: 'Ministry of Health — Tajikistan', url: 'https://moh.tj/index.php/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-Central', language: 'en', requires_auth: false },
  { id: 'moh-tm', organization: 'Ministry of Health — Turkmenistan', url: 'https://minzdrav.gov.tm/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-Central', language: 'en', requires_auth: false },

  { id: 'moh-to', organization: 'Ministry of Health — Tonga', url: 'https://health.gov.to/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Pacific', language: 'en', requires_auth: false },
];
