import type { ScraperSource } from './types';

// Chunk 1 of 3: US + Canada government sources.
// Defaults applied: source_type=website, scrape_method=html,
// scrape_frequency=weekly, requires_auth=false, language=en.

export const NORTH_AMERICA_GOVERNMENT_SOURCES: ScraperSource[] = [
  // ── UNITED STATES GOVERNMENT ──────────────────────────────────────────────
  { id: 'usaid-events', organization: 'USAID Events', url: 'https://www.usaid.gov/news-information/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [17], region: 'Americas-North' },
  { id: 'state-dept-events', organization: 'US State Department Events', url: 'https://www.state.gov/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [16, 17], region: 'Americas-North' },
  { id: 'us-epa-events', organization: 'US EPA Events', url: 'https://www.epa.gov/newsevents/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [13, 15], region: 'Americas-North' },
  { id: 'us-education-events', organization: 'US Department of Education Events', url: 'https://www.ed.gov/news/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [4], region: 'Americas-North' },
  { id: 'us-labor-events', organization: 'US Department of Labor Events', url: 'https://www.dol.gov/newsroom/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [8], region: 'Americas-North' },
  { id: 'us-agriculture-events', organization: 'USDA Agriculture Events', url: 'https://www.usda.gov/media/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [2], region: 'Americas-North' },
  { id: 'us-energy-events', organization: 'US Department of Energy Events', url: 'https://www.energy.gov/newsroom/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [7], region: 'Americas-North' },
  { id: 'us-treasury-events', organization: 'US Treasury Events', url: 'https://home.treasury.gov/news/press-releases', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [8, 17], region: 'Americas-North' },
  { id: 'mcc-events', organization: 'Millennium Challenge Corporation Events', url: 'https://www.mcc.gov/news-and-events/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [17], region: 'Americas-North' },
  { id: 'peacecorps-events', organization: 'Peace Corps Events', url: 'https://www.peacecorps.gov/news/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [17], region: 'Americas-North' },
  { id: 'dfc-events', organization: 'US DFC Events', url: 'https://www.dfc.gov/newsroom/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [8, 17], region: 'Americas-North' },
  { id: 'cdc-global-events', organization: 'CDC Global Health Events', url: 'https://www.cdc.gov/globalhealth/newsroom/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [3], region: 'Americas-North' },
  { id: 'nih-fogarty-events', organization: 'NIH Fogarty International Events', url: 'https://www.fic.nih.gov/Events/Pages/default.aspx', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [3, 4], region: 'Americas-North' },
  { id: 'nsf-international-events', organization: 'NSF International Events', url: 'https://www.nsf.gov/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [9, 4], region: 'Americas-North' },
  { id: 'us-hhs-global-events', organization: 'HHS Global Health Events', url: 'https://www.hhs.gov/about/news/index.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [3], region: 'Americas-North' },
  { id: 'us-commerce-events', organization: 'US Commerce Department Events', url: 'https://www.commerce.gov/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [8, 9], region: 'Americas-North' },
  { id: 'us-interior-events', organization: 'US Interior Department Events', url: 'https://www.doi.gov/news/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [15], region: 'Americas-North' },
  { id: 'us-transport-events', organization: 'US Transportation Events', url: 'https://www.transportation.gov/news/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [11], region: 'Americas-North' },
  { id: 'us-housing-events', organization: 'HUD Housing Events', url: 'https://www.hud.gov/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [11], region: 'Americas-North' },
  { id: 'us-justice-events', organization: 'US Justice Department Events', url: 'https://www.justice.gov/news', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [16], region: 'Americas-North' },

  // ── CANADA ────────────────────────────────────────────────────────────────
  { id: 'canada-gap-events', organization: 'Global Affairs Canada Events', url: 'https://www.international.gc.ca/world-monde/events-evenements/index.aspx', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [17], region: 'Americas-North' },
  { id: 'canada-environment-events', organization: 'Canada Environment Events', url: 'https://www.canada.ca/en/environment-climate-change/news/events.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [13], region: 'Americas-North' },
  { id: 'canada-immigration-events', organization: 'Canada Immigration Events', url: 'https://www.canada.ca/en/immigration-refugees-citizenship/news/events.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [10], region: 'Americas-North' },
  { id: 'canada-agriculture-events', organization: 'Agriculture Canada Events', url: 'https://www.canada.ca/en/agriculture-agri-food/news/events.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [2], region: 'Americas-North' },
  { id: 'idrc-events', organization: 'IDRC Canada Events', url: 'https://www.idrc.ca/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [17], region: 'Americas-North' },
  { id: 'canada-status-women-events', organization: 'Canada Status of Women Events', url: 'https://www.canada.ca/en/status-women/news/events.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [5], region: 'Americas-North' },
  { id: 'canada-indigenous-events', organization: 'Canada Indigenous Affairs Events', url: 'https://www.rcaanc-cirnac.gc.ca/eng/1100100010002/1533321160986', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [10], region: 'Americas-North' },
  { id: 'canada-natural-resources-events', organization: 'Canada Natural Resources Events', url: 'https://www.nrcan.gc.ca/news/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [7, 15], region: 'Americas-North' },
  { id: 'canada-justice-events', organization: 'Canada Justice Events', url: 'https://www.justice.gc.ca/eng/news-nouv/events.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [16], region: 'Americas-North' },
];

// Chunk 2 of 3: Brazil + Mexico government sources.
// Defaults: source_type=website, scrape_method=html, scrape_frequency=weekly,
// requires_auth=false. Language: pt for Brazil, es for Mexico.

export const LATIN_AMERICA_GOVERNMENT_SOURCES_PART1: ScraperSource[] = [
  // ── BRAZIL ────────────────────────────────────────────────────────────────
  { id: 'brazil-mre-events', organization: 'Brazil Foreign Ministry Events', url: 'https://www.gov.br/mre/pt-br/assuntos/eventos', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'brazil-mma-events', organization: 'Brazil Environment Ministry', url: 'https://www.gov.br/mma/pt-br/assuntos/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [13, 15], region: 'Americas-Latin' },
  { id: 'brazil-mec-events', organization: 'Brazil Education Ministry', url: 'https://www.gov.br/mec/pt-br/assuntos/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [4], region: 'Americas-Latin' },
  { id: 'brazil-mds-events', organization: 'Brazil Social Development Ministry', url: 'https://www.gov.br/mds/pt-br/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [1, 10], region: 'Americas-Latin' },
  { id: 'brazil-agriculture-events', organization: 'Brazil Agriculture Ministry', url: 'https://www.gov.br/agricultura/pt-br/assuntos/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [2], region: 'Americas-Latin' },
  { id: 'brazil-energy-events', organization: 'Brazil Energy Ministry', url: 'https://www.gov.br/mme/pt-br/assuntos/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [7], region: 'Americas-Latin' },
  { id: 'brazil-women-events', organization: 'Brazil Women Ministry', url: 'https://www.gov.br/mulheres/pt-br/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [5], region: 'Americas-Latin' },
  { id: 'brazil-indigenous-events', organization: 'Brazil FUNAI Indigenous Affairs', url: 'https://www.gov.br/funai/pt-br/assuntos/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [10], region: 'Americas-Latin' },
  { id: 'abc-brazil-events', organization: 'ABC Brazil South-South Cooperation', url: 'https://www.gov.br/abc/pt-br/assuntos/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'brazil-health-events', organization: 'Brazil Health Ministry', url: 'https://www.gov.br/saude/pt-br/assuntos/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [3], region: 'Americas-Latin' },
  { id: 'brazil-justice-events', organization: 'Brazil Justice Ministry', url: 'https://www.gov.br/mj/pt-br/assuntos/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [16], region: 'Americas-Latin' },
  { id: 'brazil-labor-events', organization: 'Brazil Labor Ministry', url: 'https://www.gov.br/trabalho/pt-br/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [8], region: 'Americas-Latin' },
  { id: 'brazil-cities-events', organization: 'Brazil Cities Ministry', url: 'https://www.gov.br/cidades/pt-br/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [11], region: 'Americas-Latin' },
  { id: 'brazil-science-events', organization: 'Brazil Science Technology Ministry', url: 'https://www.gov.br/mcti/pt-br/assuntos/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [9], region: 'Americas-Latin' },
  { id: 'brazil-human-rights-events', organization: 'Brazil Human Rights Ministry', url: 'https://www.gov.br/mdh/pt-br/assuntos/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [10, 16], region: 'Americas-Latin' },
  { id: 'brazil-racial-equality-events', organization: 'Brazil Racial Equality Ministry', url: 'https://www.gov.br/igualdaderacial/pt-br/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [10], region: 'Americas-Latin' },

  // ── MEXICO ────────────────────────────────────────────────────────────────
  { id: 'mexico-sre-events', organization: 'Mexico Foreign Ministry', url: 'https://www.gob.mx/sre/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'mexico-semarnat-events', organization: 'Mexico Environment Ministry', url: 'https://www.gob.mx/semarnat/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [13, 15], region: 'Americas-Latin' },
  { id: 'mexico-sep-events', organization: 'Mexico Education Ministry', url: 'https://www.gob.mx/sep/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [4], region: 'Americas-Latin' },
  { id: 'mexico-agriculture-events', organization: 'Mexico Agriculture Ministry', url: 'https://www.gob.mx/sader/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [2], region: 'Americas-Latin' },
  { id: 'mexico-energy-events', organization: 'Mexico Energy Ministry', url: 'https://www.gob.mx/sener/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [7], region: 'Americas-Latin' },
  { id: 'mexico-women-events', organization: 'Mexico Women Institute', url: 'https://www.gob.mx/inmujeres/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [5], region: 'Americas-Latin' },
  { id: 'amexcid-events', organization: 'AMEXCID Mexico Cooperation Agency', url: 'https://www.gob.mx/amexcid/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'mexico-health-events', organization: 'Mexico Health Ministry', url: 'https://www.gob.mx/salud/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [3], region: 'Americas-Latin' },
  { id: 'mexico-labor-events', organization: 'Mexico Labor Ministry', url: 'https://www.gob.mx/stps/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [8], region: 'Americas-Latin' },
  { id: 'mexico-social-events', organization: 'Mexico Social Welfare Ministry', url: 'https://www.gob.mx/bienestar/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [1, 10], region: 'Americas-Latin' },
  { id: 'mexico-indigenous-events', organization: 'Mexico Indigenous Peoples Institute', url: 'https://www.gob.mx/inpi/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [10], region: 'Americas-Latin' },
  { id: 'mexico-water-events', organization: 'Mexico Water Commission', url: 'https://www.gob.mx/conagua/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [6], region: 'Americas-Latin' },
  { id: 'mexico-housing-events', organization: 'Mexico Urban Development Ministry', url: 'https://www.gob.mx/sedatu/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [11], region: 'Americas-Latin' },
  { id: 'mexico-justice-events', organization: 'Mexico Justice Ministry', url: 'https://www.gob.mx/sspc/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [16], region: 'Americas-Latin' },
  { id: 'mexico-science-events', organization: 'Mexico Science Council CONAHCYT', url: 'https://www.gob.mx/conahcyt/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [9], region: 'Americas-Latin' },
];

// Chunk 3A: remaining Latin America + Caribbean country government sources.
// Defaults: source_type=website, scrape_method=html, scrape_frequency=weekly,
// requires_auth=false. Language per country: es default, fr for Haiti,
// en for Anglophone Caribbean (Jamaica, Trinidad, Barbados, Guyana, Belize).

export const LATIN_AMERICA_GOVERNMENT_SOURCES_PART2: ScraperSource[] = [
  // ── COLOMBIA ──────────────────────────────────────────────────────────────
  { id: 'colombia-cancilleria-events', organization: 'Colombia Foreign Ministry', url: 'https://www.cancilleria.gov.co/newsroom/news', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'colombia-minambiente-events', organization: 'Colombia Environment Ministry', url: 'https://www.minambiente.gov.co/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [13, 15], region: 'Americas-Latin' },
  { id: 'colombia-mineducacion-events', organization: 'Colombia Education Ministry', url: 'https://www.mineducacion.gov.co/portal/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [4], region: 'Americas-Latin' },
  { id: 'colombia-women-events', organization: 'Colombia Gender Equality Office', url: 'https://www.equidadmujer.gov.co/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [5], region: 'Americas-Latin' },
  { id: 'apc-colombia-events', organization: 'APC Colombia Cooperation Agency', url: 'https://www.apccolombia.gov.co/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'colombia-health-events', organization: 'Colombia Health Ministry', url: 'https://www.minsalud.gov.co/Noticias/Paginas/default.aspx', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [3], region: 'Americas-Latin' },
  { id: 'colombia-agriculture-events', organization: 'Colombia Agriculture Ministry', url: 'https://www.minagricultura.gov.co/noticias/Paginas/Noticias.aspx', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [2], region: 'Americas-Latin' },
  { id: 'colombia-labor-events', organization: 'Colombia Labor Ministry', url: 'https://www.mintrabajo.gov.co/prensa/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [8], region: 'Americas-Latin' },
  { id: 'colombia-social-events', organization: 'Colombia Social Prosperity Agency', url: 'https://www.prosperidadsocial.gov.co/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [1, 10], region: 'Americas-Latin' },
  { id: 'colombia-justice-events', organization: 'Colombia Justice Ministry', url: 'https://www.minjusticia.gov.co/Noticias/Paginas/default.aspx', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [16], region: 'Americas-Latin' },
  { id: 'colombia-science-events', organization: 'Colombia Science Ministry', url: 'https://minciencias.gov.co/sala_de_prensa/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [9], region: 'Americas-Latin' },
  { id: 'colombia-housing-events', organization: 'Colombia Housing Ministry', url: 'https://minvivienda.gov.co/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [11], region: 'Americas-Latin' },

  // ── ARGENTINA ─────────────────────────────────────────────────────────────
  { id: 'argentina-cancilleria-events', organization: 'Argentina Foreign Ministry', url: 'https://cancilleria.gob.ar/es/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'argentina-ambiente-events', organization: 'Argentina Environment Ministry', url: 'https://www.argentina.gob.ar/ambiente/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [13], region: 'Americas-Latin' },
  { id: 'argentina-education-events', organization: 'Argentina Education Ministry', url: 'https://www.argentina.gob.ar/educacion/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [4], region: 'Americas-Latin' },
  { id: 'argentina-women-events', organization: 'Argentina Gender Ministry', url: 'https://www.argentina.gob.ar/generos/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [5], region: 'Americas-Latin' },
  { id: 'argentina-agriculture-events', organization: 'Argentina Agriculture Ministry', url: 'https://www.argentina.gob.ar/agricultura/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [2], region: 'Americas-Latin' },
  { id: 'argentina-health-events', organization: 'Argentina Health Ministry', url: 'https://www.argentina.gob.ar/salud/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [3], region: 'Americas-Latin' },
  { id: 'argentina-labor-events', organization: 'Argentina Labor Ministry', url: 'https://www.argentina.gob.ar/trabajo/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [8], region: 'Americas-Latin' },
  { id: 'argentina-science-events', organization: 'Argentina Science Ministry', url: 'https://www.argentina.gob.ar/ciencia/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [9], region: 'Americas-Latin' },
  { id: 'argentina-social-events', organization: 'Argentina Social Development Ministry', url: 'https://www.argentina.gob.ar/desarrollosocial/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [1, 10], region: 'Americas-Latin' },
  { id: 'argentina-justice-events', organization: 'Argentina Justice Ministry', url: 'https://www.argentina.gob.ar/justicia/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [16], region: 'Americas-Latin' },
  { id: 'fonplata-events', organization: 'FONPLATA Development Bank Southern Cone', url: 'https://www.fonplata.org/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [8, 17], region: 'Americas-Latin' },

  // ── CHILE ─────────────────────────────────────────────────────────────────
  { id: 'chile-minrel-events', organization: 'Chile Foreign Ministry', url: 'https://www.minrel.gob.cl/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'chile-mma-events', organization: 'Chile Environment Ministry', url: 'https://mma.gob.cl/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [13], region: 'Americas-Latin' },
  { id: 'chile-mineduc-events', organization: 'Chile Education Ministry', url: 'https://www.mineduc.cl/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [4], region: 'Americas-Latin' },
  { id: 'agci-chile-events', organization: 'AGCI Chile International Cooperation', url: 'https://www.agci.gob.cl/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'chile-health-events', organization: 'Chile Health Ministry', url: 'https://www.minsal.cl/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [3], region: 'Americas-Latin' },
  { id: 'chile-women-events', organization: 'Chile Women Ministry', url: 'https://minmujeryeg.gob.cl/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [5], region: 'Americas-Latin' },
  { id: 'chile-labor-events', organization: 'Chile Labor Ministry', url: 'https://www.mintrab.gob.cl/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [8], region: 'Americas-Latin' },
  { id: 'chile-social-events', organization: 'Chile Social Development Ministry', url: 'https://www.desarrollosocialyfamilia.gob.cl/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [1, 10], region: 'Americas-Latin' },
  { id: 'chile-science-events', organization: 'Chile Science Ministry', url: 'https://www.minciencia.gob.cl/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [9], region: 'Americas-Latin' },
  { id: 'chile-indigenous-events', organization: 'Chile CONADI Indigenous Affairs', url: 'https://www.conadi.gob.cl/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [10], region: 'Americas-Latin' },
  { id: 'chile-housing-events', organization: 'Chile Housing Ministry', url: 'https://minvu.gob.cl/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [11], region: 'Americas-Latin' },

  // ── PERU ──────────────────────────────────────────────────────────────────
  { id: 'peru-rree-events', organization: 'Peru Foreign Ministry', url: 'https://www.gob.pe/institucion/rree/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'peru-ambiente-events', organization: 'Peru Environment Ministry', url: 'https://www.gob.pe/institucion/minam/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [13, 15], region: 'Americas-Latin' },
  { id: 'peru-education-events', organization: 'Peru Education Ministry', url: 'https://www.gob.pe/institucion/minedu/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [4], region: 'Americas-Latin' },
  { id: 'apci-peru-events', organization: 'APCI Peru International Cooperation', url: 'https://www.apci.gob.pe/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'peru-health-events', organization: 'Peru Health Ministry', url: 'https://www.gob.pe/institucion/minsa/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [3], region: 'Americas-Latin' },
  { id: 'peru-women-events', organization: 'Peru Women Ministry', url: 'https://www.gob.pe/institucion/mimp/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [5], region: 'Americas-Latin' },
  { id: 'peru-labor-events', organization: 'Peru Labor Ministry', url: 'https://www.gob.pe/institucion/mtpe/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [8], region: 'Americas-Latin' },
  { id: 'peru-agriculture-events', organization: 'Peru Agriculture Ministry', url: 'https://www.gob.pe/institucion/midagri/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [2], region: 'Americas-Latin' },
  { id: 'peru-social-events', organization: 'Peru Social Development Ministry', url: 'https://www.gob.pe/institucion/midis/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [1, 10], region: 'Americas-Latin' },
  { id: 'peru-housing-events', organization: 'Peru Housing Ministry', url: 'https://www.gob.pe/institucion/mvcs/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [11], region: 'Americas-Latin' },
  { id: 'peru-water-events', organization: 'Peru Water Authority', url: 'https://www.gob.pe/institucion/ana/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [6], region: 'Americas-Latin' },

  // ── ECUADOR ───────────────────────────────────────────────────────────────
  { id: 'ecuador-cancilleria-events', organization: 'Ecuador Foreign Ministry', url: 'https://www.cancilleria.gob.ec/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'ecuador-ambiente-events', organization: 'Ecuador Environment Ministry', url: 'https://www.ambiente.gob.ec/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [13], region: 'Americas-Latin' },
  { id: 'ecuador-education-events', organization: 'Ecuador Education Ministry', url: 'https://educacion.gob.ec/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [4], region: 'Americas-Latin' },
  { id: 'ecuador-health-events', organization: 'Ecuador Health Ministry', url: 'https://www.salud.gob.ec/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [3], region: 'Americas-Latin' },
  { id: 'ecuador-women-events', organization: 'Ecuador Gender Ministry', url: 'https://www.igualdad.gob.ec/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [5], region: 'Americas-Latin' },
  { id: 'ecuador-agriculture-events', organization: 'Ecuador Agriculture Ministry', url: 'https://www.agricultura.gob.ec/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [2], region: 'Americas-Latin' },
  { id: 'ecuador-water-events', organization: 'Ecuador Water Secretariat', url: 'https://www.agua.gob.ec/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [6], region: 'Americas-Latin' },
  { id: 'ecuador-social-events', organization: 'Ecuador Social Inclusion Ministry', url: 'https://www.inclusion.gob.ec/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [1, 10], region: 'Americas-Latin' },

  // ── BOLIVIA ───────────────────────────────────────────────────────────────
  { id: 'bolivia-rree-events', organization: 'Bolivia Foreign Ministry', url: 'https://www.cancilleria.gob.bo/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'bolivia-environment-events', organization: 'Bolivia Environment Ministry', url: 'https://www.mmaya.gob.bo/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [13], region: 'Americas-Latin' },
  { id: 'bolivia-education-events', organization: 'Bolivia Education Ministry', url: 'https://www.minedu.gob.bo/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [4], region: 'Americas-Latin' },
  { id: 'bolivia-health-events', organization: 'Bolivia Health Ministry', url: 'https://www.minsalud.gob.bo/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [3], region: 'Americas-Latin' },
  { id: 'bolivia-women-events', organization: 'Bolivia Gender Ministry', url: 'https://www.mingeneros.gob.bo/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [5], region: 'Americas-Latin' },
  { id: 'bolivia-agriculture-events', organization: 'Bolivia Agriculture Ministry', url: 'https://www.mdryt.gob.bo/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [2], region: 'Americas-Latin' },
  { id: 'bolivia-social-events', organization: 'Bolivia Social Development Ministry', url: 'https://www.mds.gob.bo/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [1, 10], region: 'Americas-Latin' },

  // ── VENEZUELA ─────────────────────────────────────────────────────────────
  { id: 'venezuela-mppre-events', organization: 'Venezuela Foreign Ministry', url: 'https://mppre.gob.ve/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'venezuela-environment-events', organization: 'Venezuela Environment Ministry', url: 'https://www.minec.gob.ve/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [13], region: 'Americas-Latin' },
  { id: 'venezuela-education-events', organization: 'Venezuela Education Ministry', url: 'https://www.me.gob.ve/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [4], region: 'Americas-Latin' },

  // ── PARAGUAY ──────────────────────────────────────────────────────────────
  { id: 'paraguay-mre-events', organization: 'Paraguay Foreign Ministry', url: 'https://www.mre.gov.py/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'paraguay-environment-events', organization: 'Paraguay Environment Ministry', url: 'https://www.mades.gov.py/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [13], region: 'Americas-Latin' },
  { id: 'paraguay-education-events', organization: 'Paraguay Education Ministry', url: 'https://www.mec.gov.py/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [4], region: 'Americas-Latin' },
  { id: 'paraguay-health-events', organization: 'Paraguay Health Ministry', url: 'https://www.mspbs.gov.py/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [3], region: 'Americas-Latin' },
  { id: 'paraguay-women-events', organization: 'Paraguay Women Secretariat', url: 'https://www.mujer.gov.py/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [5], region: 'Americas-Latin' },
  { id: 'paraguay-agriculture-events', organization: 'Paraguay Agriculture Ministry', url: 'https://www.mag.gov.py/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [2], region: 'Americas-Latin' },

  // ── URUGUAY ───────────────────────────────────────────────────────────────
  { id: 'uruguay-mrree-events', organization: 'Uruguay Foreign Ministry', url: 'https://www.gub.uy/ministerio-relaciones-exteriores/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'uruguay-ambiente-events', organization: 'Uruguay Environment Ministry', url: 'https://www.gub.uy/ministerio-ambiente/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [13], region: 'Americas-Latin' },
  { id: 'uruguay-education-events', organization: 'Uruguay Education Ministry', url: 'https://www.gub.uy/ministerio-educacion-cultura/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [4], region: 'Americas-Latin' },
  { id: 'uruguay-health-events', organization: 'Uruguay Health Ministry', url: 'https://www.gub.uy/ministerio-salud-publica/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [3], region: 'Americas-Latin' },
  { id: 'uruguay-women-events', organization: 'Uruguay Women Institute', url: 'https://www.gub.uy/inmujeres/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [5], region: 'Americas-Latin' },
  { id: 'uruguay-agriculture-events', organization: 'Uruguay Agriculture Ministry', url: 'https://www.gub.uy/ministerio-ganaderia-agricultura-pesca/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [2], region: 'Americas-Latin' },
  { id: 'uruguay-social-events', organization: 'Uruguay Social Development Ministry', url: 'https://www.gub.uy/ministerio-desarrollo-social/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [1, 10], region: 'Americas-Latin' },
  { id: 'uruguay-labor-events', organization: 'Uruguay Labor Ministry', url: 'https://www.gub.uy/ministerio-trabajo-seguridad-social/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [8], region: 'Americas-Latin' },

  // ── COSTA RICA ────────────────────────────────────────────────────────────
  { id: 'costarica-mre-events', organization: 'Costa Rica Foreign Ministry', url: 'https://www.rree.go.cr/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'costarica-minae-events', organization: 'Costa Rica Environment Ministry', url: 'https://minae.go.cr/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [13], region: 'Americas-Latin' },
  { id: 'costarica-education-events', organization: 'Costa Rica Education Ministry', url: 'https://www.mep.go.cr/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [4], region: 'Americas-Latin' },
  { id: 'costarica-health-events', organization: 'Costa Rica Health Ministry', url: 'https://www.ministeriodesalud.go.cr/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [3], region: 'Americas-Latin' },
  { id: 'costarica-women-events', organization: 'Costa Rica Women Institute INAMU', url: 'https://www.inamu.go.cr/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [5], region: 'Americas-Latin' },
  { id: 'costarica-agriculture-events', organization: 'Costa Rica Agriculture Ministry', url: 'https://www.mag.go.cr/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [2], region: 'Americas-Latin' },
  { id: 'costarica-social-events', organization: 'Costa Rica Social Assistance IMAS', url: 'https://www.imas.go.cr/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [1, 10], region: 'Americas-Latin' },
  { id: 'costarica-science-events', organization: 'Costa Rica Science Ministry', url: 'https://www.micitt.go.cr/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [9], region: 'Americas-Latin' },

  // ── PANAMA ────────────────────────────────────────────────────────────────
  { id: 'panama-mire-events', organization: 'Panama Foreign Ministry', url: 'https://www.mire.gob.pa/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'panama-miambiente-events', organization: 'Panama Environment Ministry', url: 'https://www.miambiente.gob.pa/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [13], region: 'Americas-Latin' },
  { id: 'panama-education-events', organization: 'Panama Education Ministry', url: 'https://www.meduca.gob.pa/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [4], region: 'Americas-Latin' },
  { id: 'panama-health-events', organization: 'Panama Health Ministry', url: 'https://www.minsa.gob.pa/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [3], region: 'Americas-Latin' },
  { id: 'panama-agriculture-events', organization: 'Panama Agriculture Ministry', url: 'https://www.mida.gob.pa/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [2], region: 'Americas-Latin' },
  { id: 'panama-social-events', organization: 'Panama Social Development Ministry', url: 'https://www.mides.gob.pa/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [1, 10], region: 'Americas-Latin' },

  // ── GUATEMALA ─────────────────────────────────────────────────────────────
  { id: 'guatemala-minex-events', organization: 'Guatemala Foreign Ministry', url: 'https://www.minex.gob.gt/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'guatemala-marn-events', organization: 'Guatemala Environment Ministry', url: 'https://www.marn.gob.gt/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [13], region: 'Americas-Latin' },
  { id: 'guatemala-education-events', organization: 'Guatemala Education Ministry', url: 'https://www.mineduc.gob.gt/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [4], region: 'Americas-Latin' },
  { id: 'guatemala-health-events', organization: 'Guatemala Health Ministry', url: 'https://www.mspas.gob.gt/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [3], region: 'Americas-Latin' },
  { id: 'guatemala-women-events', organization: 'Guatemala Women Secretariat', url: 'https://www.seprem.gob.gt/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [5], region: 'Americas-Latin' },
  { id: 'guatemala-agriculture-events', organization: 'Guatemala Agriculture Ministry', url: 'https://www.maga.gob.gt/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [2], region: 'Americas-Latin' },
  { id: 'guatemala-social-events', organization: 'Guatemala Social Development Ministry', url: 'https://www.mides.gob.gt/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [1, 10], region: 'Americas-Latin' },
  { id: 'segeplan-guatemala-events', organization: 'Guatemala Planning Secretariat SEGEPLAN', url: 'https://www.segeplan.gob.gt/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [17], region: 'Americas-Latin' },

  // ── HONDURAS ──────────────────────────────────────────────────────────────
  { id: 'honduras-sre-events', organization: 'Honduras Foreign Ministry', url: 'https://sre.gob.hn/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'honduras-miambiente-events', organization: 'Honduras Environment Ministry', url: 'https://www.miambiente.gob.hn/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [13], region: 'Americas-Latin' },
  { id: 'honduras-education-events', organization: 'Honduras Education Ministry', url: 'https://www.se.gob.hn/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [4], region: 'Americas-Latin' },
  { id: 'honduras-health-events', organization: 'Honduras Health Ministry', url: 'https://www.salud.gob.hn/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [3], region: 'Americas-Latin' },
  { id: 'honduras-women-events', organization: 'Honduras Women Institute INAM', url: 'https://www.inam.gob.hn/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [5], region: 'Americas-Latin' },
  { id: 'honduras-agriculture-events', organization: 'Honduras Agriculture Ministry', url: 'https://www.sag.gob.hn/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [2], region: 'Americas-Latin' },
  { id: 'honduras-social-events', organization: 'Honduras Social Development Ministry', url: 'https://www.sedesol.gob.hn/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [1, 10], region: 'Americas-Latin' },

  // ── EL SALVADOR ───────────────────────────────────────────────────────────
  { id: 'elsalvador-mrree-events', organization: 'El Salvador Foreign Ministry', url: 'https://rree.gob.sv/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'elsalvador-marn-events', organization: 'El Salvador Environment Ministry', url: 'https://www.marn.gob.sv/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [13], region: 'Americas-Latin' },
  { id: 'elsalvador-education-events', organization: 'El Salvador Education Ministry', url: 'https://www.mined.gob.sv/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [4], region: 'Americas-Latin' },
  { id: 'elsalvador-health-events', organization: 'El Salvador Health Ministry', url: 'https://www.salud.gob.sv/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [3], region: 'Americas-Latin' },
  { id: 'elsalvador-women-events', organization: 'El Salvador Women Institute ISDEMU', url: 'https://www.isdemu.gob.sv/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [5], region: 'Americas-Latin' },
  { id: 'elsalvador-agriculture-events', organization: 'El Salvador Agriculture Ministry', url: 'https://www.mag.gob.sv/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [2], region: 'Americas-Latin' },

  // ── NICARAGUA ─────────────────────────────────────────────────────────────
  { id: 'nicaragua-minrex-events', organization: 'Nicaragua Foreign Ministry', url: 'https://www.minrex.gob.ni/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'nicaragua-marena-events', organization: 'Nicaragua Environment Ministry', url: 'https://www.marena.gob.ni/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [13], region: 'Americas-Latin' },
  { id: 'nicaragua-education-events', organization: 'Nicaragua Education Ministry', url: 'https://www.mined.gob.ni/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [4], region: 'Americas-Latin' },
  { id: 'nicaragua-health-events', organization: 'Nicaragua Health Ministry', url: 'https://www.minsa.gob.ni/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [3], region: 'Americas-Latin' },

  // ── CARIBBEAN COUNTRIES ───────────────────────────────────────────────────
  { id: 'jamaica-mfaft-events', organization: 'Jamaica Foreign Ministry Events', url: 'https://www.mfaft.gov.jm/news-events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'jamaica-nepa-events', organization: 'Jamaica Environment Agency NEPA', url: 'https://www.nepa.gov.jm/news-events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [13], region: 'Americas-Latin' },
  { id: 'jamaica-education-events', organization: 'Jamaica Education Ministry', url: 'https://moey.gov.jm/news-events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [4], region: 'Americas-Latin' },
  { id: 'jamaica-health-events', organization: 'Jamaica Health Ministry', url: 'https://www.moh.gov.jm/news-events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [3], region: 'Americas-Latin' },
  { id: 'trinidad-mfa-events', organization: 'Trinidad Foreign Ministry', url: 'https://foreign.gov.tt/news-events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'trinidad-environment-events', organization: 'Trinidad Environmental Management Authority', url: 'https://www.ema.co.tt/news-events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [13], region: 'Americas-Latin' },
  { id: 'trinidad-education-events', organization: 'Trinidad Education Ministry', url: 'https://www.moe.gov.tt/news-events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [4], region: 'Americas-Latin' },
  { id: 'trinidad-health-events', organization: 'Trinidad Health Ministry', url: 'https://health.gov.tt/news-events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [3], region: 'Americas-Latin' },
  { id: 'barbados-mfa-events', organization: 'Barbados Foreign Ministry', url: 'https://www.foreign.gov.bb/news-events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'guyana-mfa-events', organization: 'Guyana Foreign Ministry', url: 'https://www.minfor.gov.gy/news-events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'guyana-education-events', organization: 'Guyana Education Ministry', url: 'https://www.moe.gov.gy/news-events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [4], region: 'Americas-Latin' },
  { id: 'guyana-health-events', organization: 'Guyana Health Ministry', url: 'https://www.health.gov.gy/news-events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [3], region: 'Americas-Latin' },
  { id: 'belize-mfa-events', organization: 'Belize Foreign Ministry', url: 'https://www.mfa.gov.bz/news-events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'belize-education-events', organization: 'Belize Education Ministry', url: 'https://www.moe.gov.bz/news-events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [4], region: 'Americas-Latin' },
  { id: 'belize-health-events', organization: 'Belize Health Ministry', url: 'https://www.health.gov.bz/news-events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [3], region: 'Americas-Latin' },
  { id: 'domrep-mirex-events', organization: 'Dominican Republic Foreign Ministry', url: 'https://mirex.gob.do/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'domrep-environment-events', organization: 'Dominican Republic Environment Ministry', url: 'https://www.medioambiente.gob.do/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [13], region: 'Americas-Latin' },
  { id: 'domrep-education-events', organization: 'Dominican Republic Education Ministry', url: 'https://www.ministeriodeeducacion.gob.do/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [4], region: 'Americas-Latin' },
  { id: 'domrep-health-events', organization: 'Dominican Republic Health Ministry', url: 'https://www.msp.gob.do/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [3], region: 'Americas-Latin' },
  { id: 'domrep-women-events', organization: 'Dominican Republic Women Ministry', url: 'https://mujer.gob.do/noticias/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [5], region: 'Americas-Latin' },
  { id: 'haiti-maecdn-events', organization: 'Haiti Foreign Ministry', url: 'https://www.maecdn.gouv.ht/actualites/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'fr', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'haiti-education-events', organization: 'Haiti Education Ministry', url: 'https://www.menfp.gouv.ht/actualites/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'fr', primary_sdg_goals: [4], region: 'Americas-Latin' },
  { id: 'cuba-minrex-events', organization: 'Cuba Foreign Ministry', url: 'https://www.minrex.gob.cu/en/news', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [17], region: 'Americas-Latin' },
];
