import type { ScraperSource } from './types';

export const SOURCES_MENA: ScraperSource[] = [
  // ── WHO EMRO MEMBER STATE MINISTRIES ──────────────────────────────────────

  { id: 'moh-af', organization: 'Ministry of Health Afghanistan', url: 'https://moph.gov.af', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'South-Asia', language: 'en', requires_auth: false },
  { id: 'moh-bh', organization: 'Ministry of Health Bahrain', url: 'https://www.moh.gov.bh', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Middle-East', language: 'ar', requires_auth: false },
  { id: 'moh-dj', organization: 'Ministry of Health Djibouti', url: 'https://www.sante.gouv.dj', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Africa-East', language: 'fr', requires_auth: false },
  { id: 'moh-eg', organization: 'Ministry of Health Egypt', url: 'https://www.mohp.gov.eg', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Africa-North', language: 'ar', requires_auth: false },
  { id: 'moh-ir', organization: 'Ministry of Health Iran', url: 'https://www.behdasht.gov.ir', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Middle-East', language: 'ar', requires_auth: false },
  { id: 'moh-iq', organization: 'Ministry of Health Iraq', url: 'https://www.moh.gov.iq', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Middle-East', language: 'ar', requires_auth: false },
  { id: 'moh-jo', organization: 'Ministry of Health Jordan', url: 'https://www.moh.gov.jo', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Middle-East', language: 'ar', requires_auth: false },
  { id: 'moh-kw', organization: 'Ministry of Health Kuwait', url: 'https://www.moh.gov.kw', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Middle-East', language: 'ar', requires_auth: false },
  { id: 'moh-lb', organization: 'Ministry of Public Health Lebanon', url: 'https://www.moph.gov.lb', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Middle-East', language: 'ar', requires_auth: false },
  { id: 'moh-ly', organization: 'Ministry of Health Libya', url: 'https://www.health.gov.ly', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Middle-East', language: 'ar', requires_auth: false },
  { id: 'moh-ma', organization: 'Ministry of Health Morocco', url: 'https://www.sante.gov.ma', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Africa-North', language: 'fr', requires_auth: false },
  { id: 'moh-om', organization: 'Ministry of Health Oman', url: 'https://www.moh.gov.om', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Middle-East', language: 'ar', requires_auth: false },
  { id: 'moh-pk', organization: 'Ministry of National Health Services Pakistan', url: 'https://www.nhsrc.gov.pk', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'South-Asia', language: 'en', requires_auth: false },
  { id: 'moh-ps', organization: 'Palestinian Ministry of Health', url: 'https://www.moh.gov.ps', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Middle-East', language: 'ar', requires_auth: false },
  { id: 'moh-qa', organization: 'Ministry of Public Health Qatar', url: 'https://www.moph.gov.qa', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Middle-East', language: 'ar', requires_auth: false },
  { id: 'moh-sa', organization: 'Ministry of Health Saudi Arabia', url: 'https://www.moh.gov.sa', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Middle-East', language: 'ar', requires_auth: false },
  { id: 'moh-so', organization: 'Ministry of Health Somalia', url: 'https://moh.gov.so', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'moh-sd', organization: 'Ministry of Health Sudan', url: 'https://www.fmoh.gov.sd', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Africa-North', language: 'ar', requires_auth: false },
  { id: 'moh-sy', organization: 'Ministry of Health Syria', url: 'https://www.moh.gov.sy', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Middle-East', language: 'ar', requires_auth: false },
  { id: 'moh-tn', organization: 'Ministry of Health Tunisia', url: 'https://www.santetunisie.rns.tn', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Africa-North', language: 'fr', requires_auth: false },
  { id: 'moh-ae', organization: 'Ministry of Health UAE', url: 'https://www.mohap.gov.ae', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Middle-East', language: 'ar', requires_auth: false },
  { id: 'moh-ye', organization: 'Ministry of Public Health Yemen', url: 'https://www.mophp-ye.org', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Middle-East', language: 'ar', requires_auth: false },


  // ── MIDDLE EAST AND ARAB BODIES ───────────────────────────────────────────

  { id: 'arab-league-health-events', organization: 'Arab League Health Programs', url: 'https://www.leagueofarabstates.net/en/sectors/Pages/health.aspx', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 17], region: 'Middle-East', language: 'ar', requires_auth: false },
  { id: 'gcc-health-events', organization: 'Gulf Cooperation Council Health Bodies', url: 'https://www.sgh.org.sa/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Middle-East', language: 'ar', requires_auth: false },
  { id: 'isdb-events', organization: 'Islamic Development Bank', url: 'https://www.isdb.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 17], region: 'Middle-East', language: 'en', requires_auth: false },
  { id: 'arab-board-medical-events', organization: 'Arab Board for Medical Specializations', url: 'https://www.arabboard.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Middle-East', language: 'ar', requires_auth: false },
  { id: 'arab-health-conference', organization: 'Arab Health Conference Dubai', url: 'https://www.arabhealthonline.com/en/conference.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Middle-East', language: 'en', requires_auth: false },
  { id: 'saudi-medical-conf', organization: 'Saudi Medical Conference', url: 'https://www.smj.org.sa/index.php/smj/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Middle-East', language: 'en', requires_auth: false },
  { id: 'ehs-uae-events', organization: 'Emirates Health Services', url: 'https://www.ehs.gov.ae/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Middle-East', language: 'en', requires_auth: false },
  { id: 'qatar-foundation-events', organization: 'Qatar Foundation Events', url: 'https://www.qf.org.qa/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 17], region: 'Middle-East', language: 'en', requires_auth: false },
  { id: 'qnrf-events', organization: 'Qatar National Research Fund', url: 'https://www.qnrf.org/en-us/Events-and-Workshops', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 17], region: 'Middle-East', language: 'en', requires_auth: false },
  { id: 'aub-health-events', organization: 'American University of Beirut Health Faculty', url: 'https://www.aub.edu.lb/fm/Pages/events.aspx', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Middle-East', language: 'en', requires_auth: false },
  { id: 'just-jordan-events', organization: 'Jordan University of Science and Technology', url: 'https://www.just.edu.jo/Events/Pages/default.aspx', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Middle-East', language: 'en', requires_auth: false },
  { id: 'kaust-events', organization: 'King Abdullah University of Science and Technology (KAUST)', url: 'https://www.kaust.edu.sa/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 17], region: 'Middle-East', language: 'en', requires_auth: false },
  { id: 'uj-jordan-events', organization: 'University of Jordan', url: 'https://www.ju.edu.jo/Home/News.aspx', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Middle-East', language: 'en', requires_auth: false },
  { id: 'cairo-health-events', organization: 'Cairo University Health Events', url: 'https://cu.edu.eg/en/news-events/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Africa-North', language: 'en', requires_auth: false },
  { id: 'aku-nairobi-events', organization: 'Aga Khan University Nairobi', url: 'https://www.aku.edu/nairobi/Pages/events.aspx', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'emphnet-events', organization: 'Eastern Mediterranean Public Health Network (EMPHNET)', url: 'https://emphnet.net/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Middle-East', language: 'en', requires_auth: false },
  { id: 'empha-events', organization: 'Eastern Mediterranean Public Health Association (EMPHA)', url: 'https://empha.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Middle-East', language: 'en', requires_auth: false },
  { id: 'apha-arab-events', organization: 'Arab Public Health Association', url: 'https://arabpha.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Middle-East', language: 'ar', requires_auth: false },
  { id: 'menah-policy-forum', organization: 'Middle East and North Africa Health Policy Forum', url: 'https://www.menahealthforum.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 16], region: 'Middle-East', language: 'en', requires_auth: false },
  { id: 'pmrs-events', organization: 'Palestine Medical Relief Society (PMRS)', url: 'https://www.pmrs.ps/en/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 16], region: 'Middle-East', language: 'en', requires_auth: false },
  { id: 'mdm-mena-events', organization: 'Médecins du Monde MENA', url: 'https://www.medecinsdumonde.org/en/regions/middle-east', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 16], region: 'Middle-East', language: 'en', requires_auth: false },
  { id: 'irc-mena-events', organization: 'IRC MENA', url: 'https://www.rescue.org/region/middle-east-and-north-africa', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 16], region: 'Middle-East', language: 'en', requires_auth: false },
  { id: 'imc-mena-events', organization: 'International Medical Corps MENA', url: 'https://internationalmedicalcorps.org/where-we-work/middle-east/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Middle-East', language: 'en', requires_auth: false },
  { id: 'msf-me-events', organization: 'Médecins Sans Frontières Middle East', url: 'https://www.msf.org/middle-east', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 16], region: 'Middle-East', language: 'en', requires_auth: false },



  // ── ADDITIONAL MIDDLE EAST AND ASIA ───────────────────────────────────────

  { id: 'who-wpro-events', organization: 'WHO Regional Office for the Western Pacific (WPRO)', url: 'https://www.who.int/westernpacific/news/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-Pacific', language: 'en', requires_auth: false },
  { id: 'seag-events', organization: 'South East Asia Regional Bureau of Education for Peace', url: 'https://www.seameo.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 16], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'prc-health-events', organization: 'Philippines Red Cross Health Events', url: 'https://www.redcross.org.ph/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'pha-thailand-events', organization: 'Public Health Association Thailand', url: 'https://www.pha.or.th/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'taiwan-cdc-events', organization: 'Taiwan Centers for Disease Control Events', url: 'https://www.cdc.gov.tw/En/Events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-East', language: 'en', requires_auth: false },
  { id: 'hong-kong-sph-events', organization: 'University of Hong Kong School of Public Health Events', url: 'https://sph.hku.hk/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Asia-East', language: 'en', requires_auth: false },
  { id: 'nus-global-health-events', organization: 'NUS Global Health Program Events', url: 'https://globalhealth.nus.edu.sg/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'amed-japan-events', organization: 'Japan Agency for Medical Research and Development (AMED)', url: 'https://www.amed.go.jp/en/news/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-East', language: 'en', requires_auth: false },
  { id: 'khidi-events', organization: 'Korea Health Industry Development Institute Events', url: 'https://www.khidi.or.kr/eng/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-East', language: 'en', requires_auth: false },
  { id: 'gfmer-events', organization: 'Geneva Foundation for Medical Education and Research Events', url: 'https://www.gfmer.ch/events.htm', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'ihmec-events', organization: 'International Health, Medical Education Consortium Events', url: 'https://www.ihmec.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'ecfmg-events', organization: 'Educational Commission for Foreign Medical Graduates Events', url: 'https://www.ecfmg.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Global', language: 'en', requires_auth: false },


  { id: 'moh-tr', organization: 'Ministry of Health — Turkey', url: 'https://www.saglik.gov.tr/EN/ana-sayfa.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Middle-East', language: 'en', requires_auth: false },

  { id: 'arab-network-health', organization: 'Arab Network for Health and Environment (Arabic)', url: 'https://www.anhe.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 13], region: 'Middle-East', language: 'ar', requires_auth: false },
  { id: 'arab-league-health-ar', organization: 'Arab League — Health Affairs Directorate (Arabic)', url: 'https://www.lasportal.org/ar/sectors/social/health/Pages/default.aspx', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Middle-East', language: 'ar', requires_auth: false },
];
