import type { ScraperSource } from './types';

export const SOURCES_GENDER_SOCIAL: ScraperSource[] = [

  // ── UN Women ────────────────────────────────────────────────────────────────
  { id: 'gen-unwomen-events', organization: 'UN Women', url: 'https://www.unwomen.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [5, 10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-unwomen-csw', organization: 'UN CSW', url: 'https://www.unwomen.org/en/csw', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-unwomen-africa', organization: 'UN Women Africa', url: 'https://africa.unwomen.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'gen-unwomen-asia', organization: 'UN Women Asia-Pacific', url: 'https://asiapacific.unwomen.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Asia-Pacific', language: 'en', requires_auth: false },
  { id: 'gen-unwomen-americas', organization: 'UN Women Americas', url: 'https://lac.unwomen.org/en/eventos', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'gen-unwomen-arab', organization: 'UN Women Arab States', url: 'https://arabstates.unwomen.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Middle-East', language: 'en', requires_auth: false },

  // ── UNFPA ───────────────────────────────────────────────────────────────────
  { id: 'gen-unfpa-events', organization: 'UNFPA', url: 'https://www.unfpa.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [5, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-unfpa-icpd', organization: 'UNFPA ICPD', url: 'https://www.unfpa.org/icpd', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-unfpa-africa', organization: 'UNFPA Africa', url: 'https://esaro.unfpa.org/en/news', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Africa', language: 'en', requires_auth: false },

  // ── Gender and Social Equality Organizations ────────────────────────────────
  { id: 'gen-wedo-events', organization: 'WEDO', url: 'https://wedo.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5, 13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-icrw-events', organization: 'ICRW', url: 'https://www.icrw.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-cgiar-gender', organization: 'CGIAR Gender', url: 'https://gender.cgiar.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5, 2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-care-gender', organization: 'CARE Gender', url: 'https://www.care.org/our-work/womens-empowerment/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-womendeliver', organization: 'Women Deliver', url: 'https://womendeliver.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-girlsnotbrides', organization: 'Girls Not Brides', url: 'https://www.girlsnotbrides.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-awdf-events', organization: 'African Women Development Fund', url: 'https://www.awdf.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'gen-ippf-events', organization: 'IPPF', url: 'https://www.ippf.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-gfems-events', organization: 'Global Fund to End Modern Slavery', url: 'https://www.gfems.org/news-events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5, 8], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-msichoice-events', organization: 'MSI Reproductive Choices', url: 'https://www.msichoices.org/news-resources/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-plan-international', organization: 'Plan International', url: 'https://plan-international.org/news/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5, 4], region: 'Global', language: 'en', requires_auth: false },

  // ── Social Inclusion and Inequality ───────────────────────────────────────
  { id: 'gen-oxfam-inequality', organization: 'Oxfam Inequality', url: 'https://www.oxfam.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10, 5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-actionaid-events', organization: 'ActionAid', url: 'https://www.actionaid.org/news-events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10, 5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-humanrights-watch', organization: 'Human Rights Watch', url: 'https://www.hrw.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10, 16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-amnesty-events', organization: 'Amnesty International', url: 'https://www.amnesty.org/en/latest/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10, 16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-ohchr-events', organization: 'OHCHR', url: 'https://www.ohchr.org/en/news-and-events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [10, 16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-disability-rights', organization: 'International Disability Alliance', url: 'https://www.internationaldisabilityalliance.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-inclusion-international', organization: 'Inclusion International', url: 'https://inclusion-international.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-crin-events', organization: "Child Rights International Network", url: 'https://www.crin.org/en/home/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10, 5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-age-international', organization: 'Age International', url: 'https://www.ageinternational.org.uk/about-us/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-helpage-events', organization: 'HelpAge International', url: 'https://www.helpage.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },

  // ── Indigenous Rights ───────────────────────────────────────────────────────
  { id: 'gen-unpfii-events', organization: 'UN Permanent Forum on Indigenous Issues', url: 'https://www.un.org/development/desa/indigenouspeoples/unpfii-sessions-2.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10, 16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-ipcca-events', organization: 'IPCCA', url: 'https://ipcca.info/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10, 13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-fimi-events', organization: 'International Indigenous Women Forum', url: 'https://www.iiwf.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10, 5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-iwgia-events', organization: 'IWGIA', url: 'https://www.iwgia.org/en/events.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },

  // ── LGBTIQ+ Rights ──────────────────────────────────────────────────────────
  { id: 'gen-ilga-events', organization: 'ILGA World', url: 'https://ilga.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-outright-events', organization: 'OutRight Action International', url: 'https://outrightinternational.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },

  // ── Migration and Social Protection ────────────────────────────────────────
  { id: 'gen-iom-social', organization: 'IOM Migration & Social', url: 'https://www.iom.int/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-giz-social', organization: 'GIZ Social Protection', url: 'https://www.giz.de/en/worldwide/social_protection.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10, 1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-ilo-social', organization: 'ILO Social Protection', url: 'https://www.ilo.org/global/topics/social-security-benefits/lang--en/index.htm', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10, 8], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-spiac-events', organization: 'SPIAC-B', url: 'https://www.ilo.org/global/topics/dw4sd/WCMS_183326/lang--en/index.htm', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10, 1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-socialwatch-events', organization: 'Social Watch', url: 'https://www.socialwatch.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },

  // ── Regional Gender Bodies ──────────────────────────────────────────────────
  { id: 'gen-au-gender', organization: 'African Union Gender', url: 'https://www.au.int/en/gender', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'gen-cepal-gender', organization: 'ECLAC Gender', url: 'https://www.cepal.org/en/issues/gender', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'gen-asean-gender', organization: 'ASEAN Gender', url: 'https://asean.org/asean-socio-cultural/asean-committee-on-women/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'gen-saarc-gender', organization: 'SAARC Gender', url: 'https://www.saarc-sec.org/Social-Development/3/Gender', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'gen-council-europe-gender', organization: 'Council of Europe Gender', url: 'https://www.coe.int/en/web/gender-equality/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'gen-eige-events', organization: 'EIGE', url: 'https://eige.europa.eu/newsroom/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'gen-ecowas-gender', organization: 'ECOWAS Gender', url: 'https://www.ecowas.int/departments/gender/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Africa-West', language: 'en', requires_auth: false },

  // ── Research and Policy ────────────────────────────────────────────────────
  { id: 'gen-gender-forum', organization: 'OECD Gender', url: 'https://www.oecd.org/gender/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5, 10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-cgdev-gender', organization: 'CGD Gender', url: 'https://www.cgdev.org/events?topic=gender', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-3ie-gender', organization: '3ie Gender', url: 'https://www.3ieimpact.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-alyansa-events', organization: 'Gender Equality Forum', url: 'https://forum.generationequality.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-awid-events', organization: 'AWID', url: 'https://www.awid.org/news-and-analysis/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-generation-equality', organization: 'Generation Equality', url: 'https://forum.generationequality.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-her-voice-fund', organization: 'Her Voice Fund', url: 'https://hervoicefund.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-wocan-events', organization: 'WOCAN', url: 'https://wocan.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5, 2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-wlp-events', organization: 'Women Learning Partnership', url: 'https://www.learningpartnership.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },

  // ── Youth and Children ─────────────────────────────────────────────────────
  { id: 'gen-unicef-child', organization: 'UNICEF Child Rights', url: 'https://www.unicef.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [5, 10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-crc-committee', organization: 'UN Committee on the Rights of the Child', url: 'https://www.ohchr.org/en/treaty-bodies/crc', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-girls-globe', organization: 'Girls Globe', url: 'https://girlsglobe.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5, 4], region: 'Global', language: 'en', requires_auth: false },

  // ── Racial and Ethnic Equity ────────────────────────────────────────────────
  { id: 'gen-un-decade-afrodescendants', organization: 'UN Decade for Afrodescendants', url: 'https://www.un.org/en/observances/decade-people-african-descent', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-raceforward-events', organization: 'Race Forward', url: 'https://www.raceforward.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'gen-meso-latinx', organization: 'Latino Equity Forum', url: 'https://www.latinoequityforum.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10], region: 'Americas-Latin', language: 'es', requires_auth: false },

  // ── Violence Against Women ──────────────────────────────────────────────────
  { id: 'gen-16days-events', organization: '16 Days of Activism', url: 'https://www.unwomen.org/en/what-we-do/ending-violence-against-women/take-action/16-days-of-activism', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-evaw-forum', organization: 'EVAW Coalition', url: 'https://evaw-global-database.unwomen.org/en', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-together-endvaw', organization: 'Together for Girls', url: 'https://www.togetherforgirls.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-parity-org', organization: 'Parity.org', url: 'https://parity.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5, 8], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'gen-wb-gender', organization: 'World Bank Gender', url: 'https://www.worldbank.org/en/topic/gender/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },

  // ── National Gender Ministries – Africa ─────────────────────────────────────
  { id: 'gen-ke-gender', organization: 'Kenya Ministry of Gender', url: 'https://gender.go.ke/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'gen-tz-gender', organization: 'Tanzania Ministry of Community Development', url: 'https://www.mcdgec.go.tz/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'gen-ug-gender', organization: 'Uganda Ministry of Gender', url: 'https://www.mglsd.go.ug/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'gen-et-gender', organization: 'Ethiopia Ministry of Women and Social Affairs', url: 'https://www.mowsa.gov.et/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'gen-gh-gender', organization: 'Ghana Ministry of Gender', url: 'https://mogcsp.gov.gh/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Africa-West', language: 'en', requires_auth: false },
  { id: 'gen-ng-gender', organization: 'Nigeria Ministry of Women Affairs', url: 'https://womenaffairs.gov.ng/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Africa-West', language: 'en', requires_auth: false },
  { id: 'gen-sn-gender', organization: 'Senegal Ministère de la Femme', url: 'https://www.femme.gouv.sn/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Africa-West', language: 'fr', requires_auth: false },
  { id: 'gen-ci-gender', organization: "Côte d'Ivoire Ministère de la Femme", url: 'https://www.femme.gouv.ci/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Africa-West', language: 'fr', requires_auth: false },
  { id: 'gen-rw-gender', organization: 'Rwanda Ministry of Gender', url: 'https://www.migeprof.gov.rw/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'gen-za-gender', organization: 'South Africa Department of Women', url: 'https://www.women.gov.za/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Africa-Southern', language: 'en', requires_auth: false },
  { id: 'gen-mz-gender', organization: 'Mozambique Ministry of Gender', url: 'https://www.mgcas.gov.mz/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Africa-Southern', language: 'pt', requires_auth: false },
  { id: 'gen-ma-gender', organization: 'Morocco Ministry of Solidarity and Women', url: 'https://www.social.gov.ma/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Africa-North', language: 'ar', requires_auth: false },
  { id: 'gen-eg-gender', organization: 'Egypt National Council for Women', url: 'https://ncw.gov.eg/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Africa-North', language: 'ar', requires_auth: false },

  // ── National Gender Ministries – Asia ──────────────────────────────────────
  { id: 'gen-in-women', organization: 'India Ministry of Women and Child Development', url: 'https://wcd.nic.in/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'gen-bd-women', organization: 'Bangladesh Ministry of Women', url: 'https://www.mowca.gov.bd/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'gen-pk-women', organization: 'Pakistan Ministry of Human Rights', url: 'https://www.mohr.gov.pk/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'gen-id-women', organization: 'Indonesia Ministry of Women Empowerment', url: 'https://www.kemenpppa.go.id/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Asia-Southeast', language: 'id', requires_auth: false },
  { id: 'gen-ph-women', organization: 'Philippines PCW', url: 'https://www.pcw.gov.ph/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'gen-th-women', organization: 'Thailand Ministry of Social Development', url: 'https://www.m-society.go.th/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Asia-Southeast', language: 'th', requires_auth: false },
  { id: 'gen-vn-women', organization: 'Vietnam Women Union', url: 'https://www.hoilhpn.org.vn/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Asia-Southeast', language: 'vi', requires_auth: false },
  { id: 'gen-np-gender', organization: 'Nepal Ministry of Women', url: 'https://mowcsc.gov.np/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Asia-South', language: 'en', requires_auth: false },

  // ── National Gender Ministries – Latin America ─────────────────────────────
  { id: 'gen-br-women', organization: 'Brazil Ministry of Women', url: 'https://www.gov.br/mulheres/pt-br/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Americas-Latin', language: 'pt', requires_auth: false },
  { id: 'gen-mx-women', organization: 'Mexico INMUJERES', url: 'https://www.gob.mx/inmujeres/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'gen-co-gender', organization: 'Colombia Alta Consejería para la Equidad de la Mujer', url: 'https://equidadmujer.gov.co/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'gen-ar-gender', organization: 'Argentina Ministerio de Mujeres', url: 'https://www.argentina.gob.ar/generos/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'gen-pe-gender', organization: 'Peru MIMP', url: 'https://www.mimp.gob.pe/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Americas-Latin', language: 'es', requires_auth: false },

  // ── Regional Women Networks ─────────────────────────────────────────────────
  { id: 'gen-aff-events', organization: 'African Feminist Forum', url: 'https://africanfeministforum.com/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5, 10], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'gen-aprc-events', organization: 'Asian Pacific Resource and Research Centre', url: 'https://www.arrow.org.my/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5, 3], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'gen-dawn-events', organization: 'DAWN Development Alternatives with Women', url: 'https://dawnnet.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5, 10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-wedo-events', organization: 'Women Environment Development', url: 'https://wedo.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5, 13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-femnet-events', organization: 'FEMNET', url: 'https://femnet.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5, 10], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'gen-cladem-events', organization: 'CLADEM', url: 'https://www.cladem.org/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5, 16], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'gen-cwgl-events', organization: 'Center for Women Global Leadership', url: 'https://cwgl.rutgers.edu/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-wildaf-events', organization: 'WiLDAF Africa', url: 'https://www.wildaf-ao.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5, 16], region: 'Africa-West', language: 'fr', requires_auth: false },
  { id: 'gen-awo-events', organization: 'Arab Women Organization', url: 'https://www.arabwomenorg.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Middle-East', language: 'ar', requires_auth: false },
  { id: 'gen-siha-events', organization: 'SIHA Network Africa', url: 'https://sihanet.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5, 16], region: 'Africa', language: 'en', requires_auth: false },

  // ── LGBTQ+ Rights Organizations ──────────────────────────────────────────
  { id: 'gen-ilga-events', organization: 'ILGA World', url: 'https://ilga.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10, 16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-ilga-europe', organization: 'ILGA Europe', url: 'https://www.ilga-europe.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'gen-arc-intl', organization: 'ARC International', url: 'https://arc-international.net/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10, 16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-outright-events', organization: 'OutRight Action International', url: 'https://outrightinternational.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-transgendereurope', organization: 'Transgender Europe', url: 'https://tgeu.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'gen-galz-events', organization: 'GALZ Zimbabwe', url: 'https://galz.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10], region: 'Africa-Southern', language: 'en', requires_auth: false },

  // ── Disability Rights ────────────────────────────────────────────────────────
  { id: 'gen-ida-events', organization: 'International Disability Alliance', url: 'https://www.internationaldisabilityalliance.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-dpi-events', organization: 'Disabled Peoples International', url: 'https://www.dpi.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-cbm-events', organization: 'CBM Global Disability', url: 'https://www.cbm.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-handicap-intl', organization: 'Humanity and Inclusion', url: 'https://www.hi.org/en/news-projects', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-edf-events', organization: 'European Disability Forum', url: 'https://www.edf-feph.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'gen-apdf-events', organization: 'Asia Pacific Disability Forum', url: 'https://www.apdf.org.hk/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10], region: 'Asia-Pacific', language: 'en', requires_auth: false },

  // ── Indigenous Peoples ────────────────────────────────────────────────────
  { id: 'gen-unpfii-events', organization: 'UN Permanent Forum on Indigenous Issues', url: 'https://www.un.org/development/desa/indigenouspeoples/unpfii-sessions-2.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10, 15], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-iwgia-events', organization: 'IWGIA Indigenous Affairs', url: 'https://www.iwgia.org/en/events.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-cultural-survival', organization: 'Cultural Survival', url: 'https://www.culturalsurvival.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-tebtebba-events', organization: 'Tebtebba Indigenous', url: 'https://www.tebtebba.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10, 15], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'gen-aipp-events', organization: 'Asia Indigenous Peoples Pact', url: 'https://www.aippnet.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10], region: 'Asia-Pacific', language: 'en', requires_auth: false },
  { id: 'gen-coica-events', organization: 'COICA Amazon', url: 'https://www.coica.org.ec/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10, 15], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'gen-forest-peoples', organization: 'Forest Peoples Programme', url: 'https://www.forestpeoples.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10, 15], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-unsr-indigenous', organization: 'UN Special Rapporteur Indigenous Peoples', url: 'https://www.ohchr.org/en/special-procedures/sr-indigenous-peoples', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },

  // ── Social Protection Networks ────────────────────────────────────────────
  { id: 'gen-issa-events', organization: 'ISSA Social Security', url: 'https://www.issa.int/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-socialprotection-org', organization: 'Social Protection Community', url: 'https://socialprotection.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-ilo-socialprotection', organization: 'ILO Social Protection', url: 'https://www.ilo.org/global/topics/social-security/events/lang--en/index.htm', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 8], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-wb-socialprotection', organization: 'World Bank Social Protection', url: 'https://www.worldbank.org/en/topic/socialprotection/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-help-age-events', organization: 'HelpAge International', url: 'https://www.helpage.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1, 10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-wiego-events', organization: 'WIEGO Informal Economy', url: 'https://www.wiego.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5, 8], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-girlsnotbrides', organization: 'Girls Not Brides', url: 'https://www.girlsnotbrides.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-musawah-events', organization: 'Musawah Muslim Equality', url: 'https://www.musawah.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-awdf-events', organization: 'African Women Development Fund', url: 'https://www.awdf.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5, 10], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'gen-mama-cash', organization: 'Mama Cash', url: 'https://www.mamacash.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5, 10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-global-fund-women', organization: 'Global Fund for Women', url: 'https://www.globalfundforwomen.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },

  // ── Women in Science, Leadership and Politics ──────────────────────────────
  { id: 'gen-owsd-events', organization: 'OWSD Women in Science Developing', url: 'https://owsd.net/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-ipu-women', organization: 'IPU Women in Parliament', url: 'https://www.ipu.org/our-impact/gender-equality', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5, 16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-idea-gender', organization: 'International IDEA Gender', url: 'https://www.idea.int/our-work/political-participation-and-representation/gender-in-politics', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5, 16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-women-deliver', organization: 'Women Deliver', url: 'https://womendeliver.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-ippf-events', organization: 'IPPF', url: 'https://www.ippf.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-end-fgm-network', organization: 'End FGM European Network', url: 'https://www.endfgm.eu/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5, 3], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'gen-iucn-gender', organization: 'IUCN Gender Office', url: 'https://www.iucn.org/theme/gender', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5, 15], region: 'Global', language: 'en', requires_auth: false },
];
