import type { ScraperSource } from './types';

export const SOURCES_GLOBAL_CONFERENCES: ScraperSource[] = [

  // ── Conference Listing Aggregators ─────────────────────────────────────────
  { id: 'conf-wikicfp', organization: 'WikiCFP', url: 'http://www.wikicfp.com/cfp/call?conference=social+science', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-wikicfp-health', organization: 'WikiCFP Health', url: 'http://www.wikicfp.com/cfp/call?conference=health', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-wikicfp-env', organization: 'WikiCFP Environment', url: 'http://www.wikicfp.com/cfp/call?conference=environment', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-wikicfp-econ', organization: 'WikiCFP Economics', url: 'http://www.wikicfp.com/cfp/call?conference=economics', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [8], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-allconferences-health', organization: 'AllConferences Health', url: 'https://www.allconferences.com/Health/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-allconferences-social', organization: 'AllConferences Social Science', url: 'https://www.allconferences.com/Social_Sciences/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-allconferences-env', organization: 'AllConferences Environment', url: 'https://www.allconferences.com/Environment/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-conferencealerts-dev', organization: 'Conference Alerts Development', url: 'https://conferencealerts.com/topic-listing?topic=development+studies', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-conferencealerts-pub', organization: 'Conference Alerts Public Health', url: 'https://conferencealerts.com/topic-listing?topic=public+health', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-conferencealerts-econ', organization: 'Conference Alerts Economics', url: 'https://conferencealerts.com/topic-listing?topic=economics', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [8], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-paperdigest', organization: 'Paper Digest Conferences', url: 'https://www.paperdigest.org/conferences/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [9], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-eventbrite-global-dev', organization: 'Eventbrite Global Development', url: 'https://www.eventbrite.com/d/online/international-development/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-eventbrite-health', organization: 'Eventbrite Global Health', url: 'https://www.eventbrite.com/d/online/global-health/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [3], region: 'Global', language: 'en', requires_auth: false },

  // ── Global Health Conferences ──────────────────────────────────────────────
  { id: 'conf-wha-events', organization: 'World Health Assembly', url: 'https://www.who.int/about/governance/world-health-assembly', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-astmh-events', organization: 'ASTMH', url: 'https://www.astmh.org/annual-meeting', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-apha-events', organization: 'APHA', url: 'https://www.apha.org/events-and-meetings/annual', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'conf-ipha-events', organization: 'International Public Health Conference', url: 'https://www.globalconference.com/publichealth/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-aids-conference', organization: 'AIDS Conference', url: 'https://aids2026.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-malaria-world', organization: 'World Malaria Conference', url: 'https://www.worldmalariaconference.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-tb-conference', organization: 'TB Conference', url: 'https://www.worldtbday.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-ntd-summit', organization: 'NTD Summit', url: 'https://www.endtb.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-icph-global', organization: 'ICPH Global', url: 'https://www.icphconference.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-lancet-conference', organization: 'Lancet Countdown Events', url: 'https://www.lancetcountdown.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3, 13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-ghcc-events', organization: 'Global Health Conference Clearinghouse', url: 'https://www.ghconferences.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-jhsph-events', organization: 'Johns Hopkins Bloomberg SPH Events', url: 'https://www.jhsph.edu/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'conf-hsph-events', organization: 'Harvard TH Chan SPH Events', url: 'https://www.hsph.harvard.edu/news-and-events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'conf-lshtm-events', organization: 'LSHTM Events', url: 'https://www.lshtm.ac.uk/newsevents/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Europe', language: 'en', requires_auth: false },

  // ── Development Studies Conferences ───────────────────────────────────────
  { id: 'conf-dsa-events', organization: 'DSA UK', url: 'https://www.devstud.org.uk/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 17], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'conf-eadi-events', organization: 'EADI', url: 'https://www.eadi.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'conf-icas-events', organization: 'International Convention of Asian Scholars', url: 'https://www.icasnet.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 17], region: 'Asia-Pacific', language: 'en', requires_auth: false },
  { id: 'conf-mela-events', organization: 'MELA Middle East Studies', url: 'https://www.mela-online.net/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Middle-East', language: 'en', requires_auth: false },
  { id: 'conf-asauk-events', organization: 'ASA UK Africa Studies', url: 'https://www.theasa.net/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'conf-asa-events', organization: 'African Studies Association', url: 'https://www.africanstudies.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'conf-lasa-events', organization: 'LASA Latin American Studies', url: 'https://lasa.international.pitt.edu/congress/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Americas-Latin', language: 'en', requires_auth: false },
  { id: 'conf-isa-events', organization: 'International Studies Association', url: 'https://www.isanet.org/Conferences', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16, 17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-apsa-events', organization: 'American Political Science Association', url: 'https://www.apsanet.org/EVENTS', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'conf-ecpr-events', organization: 'ECPR', url: 'https://ecpr.eu/Events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Europe', language: 'en', requires_auth: false },

  // ── Economics Conferences ──────────────────────────────────────────────────
  { id: 'conf-aea-events', organization: 'American Economic Association', url: 'https://www.aeaweb.org/conference/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'conf-ier-events', organization: 'International Economic Association', url: 'https://www.iea-world.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-res-events', organization: 'Royal Economic Society', url: 'https://res.org.uk/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'conf-eea-events', organization: 'European Economic Association', url: 'https://www.eeassoc.org/congress/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'conf-gdnet-events', organization: 'GDNet Development Economics', url: 'https://www.gdnet.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8, 1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-pedl-events', organization: 'PEDL', url: 'https://pedl.cepr.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-cepr-events', organization: 'CEPR', url: 'https://cepr.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8, 17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-nber-events', organization: 'NBER', url: 'https://www.nber.org/news/upcoming-events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'conf-ideas-events', organization: 'IDEAS Conference Listings', url: 'https://ideas.repec.org/s/conf/scodev.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8], region: 'Global', language: 'en', requires_auth: false },

  // ── Environmental Science Conferences ──────────────────────────────────────
  { id: 'conf-egu-events', organization: 'EGU', url: 'https://www.egu.eu/meetings/calendar/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-agu-events', organization: 'AGU', url: 'https://www.agu.org/annual-meeting', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13, 14], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'conf-setac-events', organization: 'SETAC', url: 'https://www.setac.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [15, 14], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-ise-events', organization: 'International Society of Ecology', url: 'https://www.intecol.net/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [15], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-iugg-events', organization: 'IUGG', url: 'https://www.iugg.org/assemblies/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-wcc-events', organization: 'World Climate Conference', url: 'https://www.wmo.int/agenda/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-oceansciences', organization: 'Ocean Sciences Meeting', url: 'https://www.aslo.org/meetings/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [14], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-nybf-climate', organization: 'NY Climate Week', url: 'https://www.climateweeknyc.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13], region: 'Americas-North', language: 'en', requires_auth: false },

  // ── Public Administration Conferences ──────────────────────────────────────
  { id: 'conf-iias-events', organization: 'IIAS', url: 'https://www.iias-iisa.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-aspa-events', organization: 'ASPA', url: 'https://www.aspanet.org/ASPA/Events/ASPA/Events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'conf-egpa-events', organization: 'EGPA', url: 'https://www.egpa.eu/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'conf-aapam-events', organization: 'AAPAM', url: 'https://www.aapam.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'conf-capam-events', organization: 'CAPAM', url: 'https://www.capam.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },

  // ── International Relations Conferences ────────────────────────────────────
  { id: 'conf-ipsa-events', organization: 'IPSA', url: 'https://www.ipsa.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-bisa-events', organization: 'BISA', url: 'https://www.bisa.ac.uk/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16, 17], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'conf-sgir-events', organization: 'SGIR', url: 'https://sgir.eu/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16, 17], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'conf-iaps-events', organization: 'International Affairs Summit', url: 'https://www.internationalaffairssummit.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },

  // ── Social Work Conferences ────────────────────────────────────────────────
  { id: 'conf-ifsw-events', organization: 'IFSW', url: 'https://www.ifsw.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-iassw-events', organization: 'IASSW', url: 'https://www.iassw-aiets.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-nasw-events', organization: 'NASW', url: 'https://www.socialworkers.org/News/Events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'conf-easw-events', organization: 'EASW', url: 'https://easw.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10], region: 'Europe', language: 'en', requires_auth: false },

  // ── SDG and Sustainability Conferences ────────────────────────────────────
  { id: 'conf-sdg-summit', organization: 'SDG Summit', url: 'https://sdgs.un.org/conferences/sdgsummit2023', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-futureoftheseas', organization: 'Future of the Seas Conference', url: 'https://www.oceanconference.un.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [14], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-un-habitat', organization: 'UN Habitat World Urban Forum', url: 'https://wuf.unhabitat.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-global-sustainability', organization: 'Global Sustainability Conference', url: 'https://www.globalconference.org/sustainability/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-planet-earth', organization: 'Planet Earth Conference', url: 'https://planetearth.net/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [15, 13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-cop-presessions', organization: 'Pre-COP Ministerials', url: 'https://unfccc.int/process/bodies/supreme-bodies/cop', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-cgiar-week', organization: 'CGIAR Science Week', url: 'https://www.cgiar.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 15], region: 'Global', language: 'en', requires_auth: false },

  // ── Technology and Innovation Conferences ──────────────────────────────────
  { id: 'conf-itu-wtdc', organization: 'ITU WTDC', url: 'https://www.itu.int/en/ITU-D/Conferences/WTDC/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [9], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-wsis-forum', organization: 'WSIS Forum', url: 'https://www.itu.int/net4/wsis/forum/2025/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [9, 17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-ictd-conference', organization: 'ICTD Conference', url: 'https://ictd.acm.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [9], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-isoc-events', organization: 'Internet Society', url: 'https://www.internetsociety.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [9], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-rsa-events', organization: 'Regional Studies Association', url: 'https://www.regionalstudies.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [11], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-ai-ethics', organization: 'AI Ethics Conference', url: 'https://aies-conference.com/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [9, 16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-neurips-events', organization: 'NeurIPS Social Good', url: 'https://nips.cc/Conferences/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [9], region: 'Global', language: 'en', requires_auth: false },

  // ── Agriculture and Food Conferences ──────────────────────────────────────
  { id: 'conf-iufro-world', organization: 'IUFRO World Congress', url: 'https://www.iufro.org/events/congresses/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [15], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-world-food-prize', organization: 'World Food Prize', url: 'https://www.worldfoodprize.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-iff-food', organization: 'International Food Forum', url: 'https://www.foodtank.com/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-soil-world', organization: 'World Soil Congress', url: 'https://www.worldsoilcongress.com/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 15], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-global-agri-geek', organization: 'Global AgriTech', url: 'https://globalagritech.com/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 9], region: 'Global', language: 'en', requires_auth: false },

  // ── Urban and Housing Conferences ─────────────────────────────────────────
  { id: 'conf-usp-forum', organization: 'Urban Symposium', url: 'https://www.urbanresilienceforum.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-ihs-conference', organization: 'IHS Urban Conference', url: 'https://www.ihs.nl/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-world-urban-forum', organization: 'World Urban Forum', url: 'https://wuf.unhabitat.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-habitat-regional', organization: 'Habitat Regional Forum', url: 'https://unhabitat.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [11], region: 'Global', language: 'en', requires_auth: false },

  // ── Water and Sanitation Conferences ──────────────────────────────────────
  { id: 'conf-world-water-week', organization: 'World Water Week', url: 'https://www.worldwaterweek.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [6], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-iwra-events', organization: 'IWRA', url: 'https://www.iwra.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [6], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-iwa-events', organization: 'IWA', url: 'https://iwa-network.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [6], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-wash-conference', organization: 'WASH Conference', url: 'https://www.washconference.net/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [6], region: 'Global', language: 'en', requires_auth: false },

  // ── Energy Conferences ─────────────────────────────────────────────────────
  { id: 'conf-irena-assembly', organization: 'IRENA Assembly', url: 'https://www.irena.org/assembly', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [7], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-world-energy-conference', organization: 'World Energy Congress', url: 'https://www.worldenergy.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [7], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-clean-energy-forum', organization: 'International Clean Energy Forum', url: 'https://www.iea.org/events/categories/conferences', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [7, 13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-ses-conference', organization: 'Solar Energy Society', url: 'https://www.ises.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [7], region: 'Global', language: 'en', requires_auth: false },

  // ── Peace and Security Conferences ────────────────────────────────────────
  { id: 'conf-munich-security', organization: 'Munich Security Conference', url: 'https://securityconference.org/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'conf-shangri-la', organization: 'Shangri-La Dialogue', url: 'https://www.iiss.org/events/shangri-la-dialogue/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'conf-asem-events', organization: 'ASEM', url: 'https://www.aseminfoboard.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17, 16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-nuclear-summit', organization: 'Nuclear Security Summit', url: 'https://www.un.org/disarmament/wmd/nuclear/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },

  // ── Sociology and Anthropology Conferences ─────────────────────────────────
  { id: 'conf-isa-sociology', organization: 'International Sociological Association', url: 'https://www.isa-sociology.org/en/conferences/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-aas-events', organization: 'American Anthropological Association', url: 'https://www.americananthro.org/StayInformed/Events.aspx', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'conf-wara-events', organization: 'World Archaeological Congress', url: 'https://www.worldarchaeologicalcongress.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },

  // ── Migration and Refugee Conferences ──────────────────────────────────────
  { id: 'conf-imrf-events', organization: 'IMRF Migration Forum', url: 'https://www.un.org/en/migration', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-gcm-forum', organization: 'GCM International Migration Forum', url: 'https://www.un.org/en/migration/forums', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-iom-world-migration', organization: 'World Migration Forum', url: 'https://worldmigrationforum.iom.int/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },

  // ── Finance and Banking Conferences ────────────────────────────────────────
  { id: 'conf-bis-events', organization: 'BIS', url: 'https://www.bis.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8, 17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-fintech-global', organization: 'Fintech Global Conference', url: 'https://fintech.global/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8, 9], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-swift-sibos', organization: 'SIBOS SWIFT', url: 'https://www.sibos.com/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8], region: 'Global', language: 'en', requires_auth: false },

  // ── Diaspora and Remittances Conferences ───────────────────────────────────
  { id: 'conf-idd-events', organization: 'International Diaspora Engagement Alliance', url: 'https://www.diasporaalliance.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10, 17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-send-money-home', organization: 'Remittance Conference', url: 'https://www.ifad.org/remittances/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10, 17], region: 'Global', language: 'en', requires_auth: false },

  // ── Gender and Women's Rights Conferences ─────────────────────────────────
  { id: 'conf-awid-forum', organization: 'AWID Forum', url: 'https://forum.awid.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-generation-eq', organization: 'Generation Equality Forum', url: 'https://forum.generationequality.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-srhr-conference', organization: 'SRHR International Conference', url: 'https://www.icpd.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5, 3], region: 'Global', language: 'en', requires_auth: false },

  // ── Business and Responsible Investment ───────────────────────────────────
  { id: 'conf-un-global-compact', organization: 'UN Global Compact Leaders Summit', url: 'https://unglobalcompact.org/take-action/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8, 17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-bhr-forum', organization: 'UN Forum on Business and Human Rights', url: 'https://www.ohchr.org/en/business-and-human-rights/un-forum-business-and-human-rights', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8, 16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-gri-events', organization: 'GRI Conference', url: 'https://www.globalreporting.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8, 17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-esg-summit', organization: 'ESG Global Summit', url: 'https://www.esgglobalsummit.com/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8, 13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-impact-summit', organization: 'Global Impact Investing Summit', url: 'https://thegiin.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8, 17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'conf-blended-finance', organization: 'Convergence Blended Finance Forum', url: 'https://www.convergence.finance/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Global', language: 'en', requires_auth: false },
];
