import type { ScraperSource } from './types';

export const SOURCES_AMERICAS: ScraperSource[] = [
  // ── WHO AMRO LATIN AMERICAN MINISTRIES ────────────────────────────────────

  { id: 'moh-ar', organization: 'Ministry of Health Argentina', url: 'https://www.argentina.gob.ar/salud', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'moh-bo', organization: 'Ministry of Health Bolivia', url: 'https://www.minsalud.gob.bo', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'moh-br', organization: 'Ministry of Health Brazil', url: 'https://www.saude.gov.br', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'pt', requires_auth: false },
  { id: 'moh-cl', organization: 'Ministry of Health Chile', url: 'https://www.minsal.cl', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'moh-co', organization: 'Ministry of Health Colombia', url: 'https://www.minsalud.gov.co', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'moh-cr', organization: 'Ministry of Health Costa Rica', url: 'https://www.ministeriodesalud.go.cr', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'moh-cu', organization: 'Ministry of Public Health Cuba', url: 'https://www.minsap.gob.cu', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'moh-do', organization: 'Ministry of Public Health Dominican Republic', url: 'https://www.msp.gob.do', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'moh-ec', organization: 'Ministry of Public Health Ecuador', url: 'https://www.salud.gob.ec', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'moh-sv', organization: 'Ministry of Health El Salvador', url: 'https://www.salud.gob.sv', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'moh-gt', organization: 'Ministry of Public Health Guatemala', url: 'https://www.mspas.gob.gt', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'moh-ht', organization: 'Ministry of Public Health Haiti', url: 'https://www.mspp.gouv.ht', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'fr', requires_auth: false },
  { id: 'moh-hn', organization: 'Ministry of Health Honduras', url: 'https://www.salud.gob.hn', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'moh-mx', organization: 'Ministry of Health Mexico', url: 'https://www.gob.mx/salud', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'moh-ni', organization: 'Ministry of Health Nicaragua', url: 'https://www.minsa.gob.ni', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'moh-pa', organization: 'Ministry of Health Panama', url: 'https://www.minsa.gob.pa', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'moh-py', organization: 'Ministry of Public Health Paraguay', url: 'https://www.mspbs.gov.py', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'moh-pe', organization: 'Ministry of Health Peru', url: 'https://www.gob.pe/minsa', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'moh-uy', organization: 'Ministry of Public Health Uruguay', url: 'https://www.gub.uy/ministerio-salud-publica', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'moh-ve', organization: 'Ministry of Health Venezuela', url: 'https://www.mpps.gob.ve', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'es', requires_auth: false },

  // ── WHO AMRO CARIBBEAN MINISTRIES ─────────────────────────────────────────

  { id: 'moh-ag', organization: 'Ministry of Health Antigua and Barbuda', url: 'https://www.health.gov.ag', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Caribbean', language: 'en', requires_auth: false },
  { id: 'moh-bs', organization: 'Ministry of Health Bahamas', url: 'https://www.moh.gov.bs', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Caribbean', language: 'en', requires_auth: false },
  { id: 'moh-bb', organization: 'Ministry of Health Barbados', url: 'https://www.health.gov.bb', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Caribbean', language: 'en', requires_auth: false },
  { id: 'moh-bz', organization: 'Ministry of Health Belize', url: 'https://www.health.gov.bz', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Caribbean', language: 'en', requires_auth: false },
  { id: 'moh-dm', organization: 'Ministry of Health Dominica', url: 'https://health.gov.dm', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Caribbean', language: 'en', requires_auth: false },
  { id: 'moh-gd', organization: 'Ministry of Health Grenada', url: 'https://www.health.gov.gd', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Caribbean', language: 'en', requires_auth: false },
  { id: 'moh-gy', organization: 'Ministry of Health Guyana', url: 'https://www.health.gov.gy', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Caribbean', language: 'en', requires_auth: false },
  { id: 'moh-jm', organization: 'Ministry of Health Jamaica', url: 'https://www.moh.gov.jm', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Caribbean', language: 'en', requires_auth: false },
  { id: 'moh-kn', organization: 'Ministry of Health Saint Kitts and Nevis', url: 'https://www.health.gov.kn', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Caribbean', language: 'en', requires_auth: false },
  { id: 'moh-lc', organization: 'Ministry of Health Saint Lucia', url: 'https://www.health.gov.lc', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Caribbean', language: 'en', requires_auth: false },
  { id: 'moh-vc', organization: 'Ministry of Health Saint Vincent and Grenadines', url: 'https://www.health.gov.vc', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Caribbean', language: 'en', requires_auth: false },
  { id: 'moh-sr', organization: 'Ministry of Health Suriname', url: 'https://www.health.gov.sr', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Caribbean', language: 'en', requires_auth: false },
  { id: 'moh-tt', organization: 'Ministry of Health Trinidad and Tobago', url: 'https://www.health.gov.tt', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Caribbean', language: 'en', requires_auth: false },



  // ── LATIN AMERICA AND CARIBBEAN BODIES ───────────────────────────────────

  { id: 'fiocruz-events', organization: 'Fiocruz (Oswaldo Cruz Foundation Brazil)', url: 'https://portal.fiocruz.br/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Americas-Latin', language: 'pt', requires_auth: false },
  { id: 'paho-programs-events', organization: 'PAHO Health Programs', url: 'https://www.paho.org/en/topics', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'flacso-events', organization: 'FLACSO Latin American Social Sciences', url: 'https://www.flacso.org/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 10], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'alames-events', organization: 'Latin American Social Medicine Association (ALAMES)', url: 'https://alames.org/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 10], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'alaesp-events', organization: 'Association of Schools of Public Health in Latin America (ALAESP)', url: 'https://alaesp.org/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'feppen-events', organization: 'Pan American Federation of Nursing (FEPPEN)', url: 'https://feppen.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'idb-health-events', organization: 'Inter-American Development Bank Health', url: 'https://www.iadb.org/en/news-and-events/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 1, 17], region: 'Americas-Latin', language: 'en', requires_auth: false },
  { id: 'mercosur-health-events', organization: 'MERCOSUR Health', url: 'https://www.mercosur.int/en/areas/health/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 17], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'oras-conhu-events', organization: 'Andean Health Organism (ORAS-CONHU)', url: 'https://www.orasconhu.org/portal/eventos', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'carpha-events', organization: 'Caribbean Public Health Agency (CARPHA)', url: 'https://carpha.org/Events/Upcoming-Events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Caribbean', language: 'en', requires_auth: false },
  { id: 'cdb-events', organization: 'Caribbean Development Bank Events', url: 'https://www.caribank.org/newsroom/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 17], region: 'Americas-Caribbean', language: 'en', requires_auth: false },
  { id: 'caricom-health-events', organization: 'CARICOM Health', url: 'https://www.caricom.org/category/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 17], region: 'Americas-Caribbean', language: 'en', requires_auth: false },
  { id: 'usp-health-events', organization: 'University of São Paulo Health Faculty', url: 'https://www.fsp.usp.br/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Americas-Latin', language: 'pt', requires_auth: false },
  { id: 'uchile-health-events', organization: 'University of Chile Health Faculty', url: 'https://www.medicina.uchile.cl/noticias/eventos', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'unam-health-events', organization: 'UNAM Health Events', url: 'https://www.unam.mx/eventos', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'uandes-events', organization: 'Universidad de los Andes Colombia', url: 'https://uniandes.edu.co/es/eventos', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'puc-chile-events', organization: 'Pontificia Universidad Católica de Chile', url: 'https://www.uc.cl/eventos', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'uwi-events', organization: 'University of the West Indies (UWI)', url: 'https://www.uwi.edu/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Americas-Caribbean', language: 'en', requires_auth: false },
  { id: 'alap-events', organization: 'Latin American Population Association (ALAP)', url: 'https://alapop.org/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 10], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'csa-events', organization: 'Caribbean Studies Association', url: 'https://www.caribbeanstudiesassociation.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10, 4], region: 'Americas-Caribbean', language: 'en', requires_auth: false },
  { id: 'repem-events', organization: 'REPEM Red de Educación Popular entre Mujeres', url: 'https://repem.org/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5, 4], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'red-ibero-salud-events', organization: 'Red Iberoamericana de Salud Pública', url: 'https://www.redsalud.org/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'cepalstat-events', organization: 'CEPALSTAT Latin America Stats Events', url: 'https://www.cepal.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10, 17], region: 'Americas-Latin', language: 'es', requires_auth: false },


  { id: 'fiocruz-pt-events', organization: 'Fiocruz Events (Portuguese)', url: 'https://portal.fiocruz.br/eventos', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Americas-Latin', language: 'pt', requires_auth: false },

  { id: 'ops-paho-es', organization: 'OPS/PAHO Eventos (Spanish)', url: 'https://www.paho.org/es/eventos', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'alames-events-es', organization: 'Asociación Latinoamericana de Medicina Social (Spanish)', url: 'https://www.alames.org/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 10], region: 'Americas-Latin', language: 'es', requires_auth: false },
];
