import type { ScraperSource } from './types';

export const SOURCES_GENDER_SOCIAL: ScraperSource[] = [

  // ── UN Women ────────────────────────────────────────────────────────────────
  { id: 'gen-unwomen-events', organization: 'UN Women', url: 'https://www.unwomen.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [5, 10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-unwomen-csw', organization: 'UN CSW', url: 'https://www.unwomen.org/en/csw', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-unwomen-africa', organization: 'UN Women Africa', url: 'https://africa.unwomen.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'gen-unwomen-asia', organization: 'UN Women Asia-Pacific', url: 'https://asiapacific.unwomen.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Asia-Pacific', language: 'en', requires_auth: false },
  { id: 'gen-unwomen-americas', organization: 'UN Women Americas', url: 'https://lac.unwomen.org/en/eventos', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'gen-unwomen-arab', organization: 'UN Women Arab States', url: 'https://arabstates.unwomen.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Middle-East', language: 'en', requires_auth: false },

  // ── UNFPA ───────────────────────────────────────────────────────────────────
  { id: 'gen-unfpa-events', organization: 'UNFPA', url: 'https://www.unfpa.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [5, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-unfpa-icpd', organization: 'UNFPA ICPD', url: 'https://www.unfpa.org/icpd', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-unfpa-africa', organization: 'UNFPA Africa', url: 'https://esaro.unfpa.org/en/news', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Africa', language: 'en', requires_auth: false },

  // ── Gender and Social Equality Organizations ────────────────────────────────
  { id: 'gen-wedo-events', organization: 'WEDO', url: 'https://wedo.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5, 13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-icrw-events', organization: 'ICRW', url: 'https://www.icrw.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-cgiar-gender', organization: 'CGIAR Gender', url: 'https://gender.cgiar.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5, 2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-care-gender', organization: 'CARE Gender', url: 'https://www.care.org/our-work/womens-empowerment/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-womendeliver', organization: 'Women Deliver', url: 'https://womendeliver.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-girlsnotbrides', organization: 'Girls Not Brides', url: 'https://www.girlsnotbrides.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-awdf-events', organization: 'African Women Development Fund', url: 'https://www.awdf.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'gen-ippf-events', organization: 'IPPF', url: 'https://www.ippf.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-gfems-events', organization: 'Global Fund to End Modern Slavery', url: 'https://www.gfems.org/news-events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5, 8], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-msichoice-events', organization: 'MSI Reproductive Choices', url: 'https://www.msichoices.org/news-resources/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-plan-international', organization: 'Plan International', url: 'https://plan-international.org/news/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5, 4], region: 'Global', language: 'en', requires_auth: false },

  // ── Social Inclusion and Inequality ───────────────────────────────────────
  { id: 'gen-oxfam-inequality', organization: 'Oxfam Inequality', url: 'https://www.oxfam.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10, 5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-actionaid-events', organization: 'ActionAid', url: 'https://www.actionaid.org/news-events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10, 5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-humanrights-watch', organization: 'Human Rights Watch', url: 'https://www.hrw.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10, 16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-amnesty-events', organization: 'Amnesty International', url: 'https://www.amnesty.org/en/latest/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10, 16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-ohchr-events', organization: 'OHCHR', url: 'https://www.ohchr.org/en/news-and-events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [10, 16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-disability-rights', organization: 'International Disability Alliance', url: 'https://www.internationaldisabilityalliance.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-inclusion-international', organization: 'Inclusion International', url: 'https://inclusion-international.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-crin-events', organization: "Child Rights International Network", url: 'https://www.crin.org/en/home/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10, 5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-age-international', organization: 'Age International', url: 'https://www.ageinternational.org.uk/about-us/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-helpage-events', organization: 'HelpAge International', url: 'https://www.helpage.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },

  // ── Indigenous Rights ───────────────────────────────────────────────────────
  { id: 'gen-unpfii-events', organization: 'UN Permanent Forum on Indigenous Issues', url: 'https://www.un.org/development/desa/indigenouspeoples/unpfii-sessions-2.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10, 16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-ipcca-events', organization: 'IPCCA', url: 'https://ipcca.info/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10, 13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-fimi-events', organization: 'International Indigenous Women Forum', url: 'https://www.iiwf.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10, 5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-iwgia-events', organization: 'IWGIA', url: 'https://www.iwgia.org/en/events.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },

  // ── LGBTIQ+ Rights ──────────────────────────────────────────────────────────
  { id: 'gen-ilga-events', organization: 'ILGA World', url: 'https://ilga.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-outright-events', organization: 'OutRight Action International', url: 'https://outrightinternational.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },

  // ── Migration and Social Protection ────────────────────────────────────────
  { id: 'gen-iom-social', organization: 'IOM Migration & Social', url: 'https://www.iom.int/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-giz-social', organization: 'GIZ Social Protection', url: 'https://www.giz.de/en/worldwide/social_protection.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10, 1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-ilo-social', organization: 'ILO Social Protection', url: 'https://www.ilo.org/global/topics/social-security-benefits/lang--en/index.htm', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10, 8], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-spiac-events', organization: 'SPIAC-B', url: 'https://www.ilo.org/global/topics/dw4sd/WCMS_183326/lang--en/index.htm', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10, 1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-socialwatch-events', organization: 'Social Watch', url: 'https://www.socialwatch.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },

  // ── Regional Gender Bodies ──────────────────────────────────────────────────
  { id: 'gen-au-gender', organization: 'African Union Gender', url: 'https://www.au.int/en/gender', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'gen-cepal-gender', organization: 'ECLAC Gender', url: 'https://www.cepal.org/en/issues/gender', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'gen-asean-gender', organization: 'ASEAN Gender', url: 'https://asean.org/asean-socio-cultural/asean-committee-on-women/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'gen-saarc-gender', organization: 'SAARC Gender', url: 'https://www.saarc-sec.org/Social-Development/3/Gender', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'gen-council-europe-gender', organization: 'Council of Europe Gender', url: 'https://www.coe.int/en/web/gender-equality/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'gen-eige-events', organization: 'EIGE', url: 'https://eige.europa.eu/newsroom/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'gen-ecowas-gender', organization: 'ECOWAS Gender', url: 'https://www.ecowas.int/departments/gender/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Africa-West', language: 'en', requires_auth: false },

  // ── Research and Policy ────────────────────────────────────────────────────
  { id: 'gen-gender-forum', organization: 'OECD Gender', url: 'https://www.oecd.org/gender/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5, 10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-cgdev-gender', organization: 'CGD Gender', url: 'https://www.cgdev.org/events?topic=gender', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-3ie-gender', organization: '3ie Gender', url: 'https://www.3ieimpact.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-alyansa-events', organization: 'Gender Equality Forum', url: 'https://forum.generationequality.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-awid-events', organization: 'AWID', url: 'https://www.awid.org/news-and-analysis/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-generation-equality', organization: 'Generation Equality', url: 'https://forum.generationequality.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-her-voice-fund', organization: 'Her Voice Fund', url: 'https://hervoicefund.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-wocan-events', organization: 'WOCAN', url: 'https://wocan.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5, 2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-wlp-events', organization: 'Women Learning Partnership', url: 'https://www.learningpartnership.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },

  // ── Youth and Children ─────────────────────────────────────────────────────
  { id: 'gen-unicef-child', organization: 'UNICEF Child Rights', url: 'https://www.unicef.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [5, 10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-crc-committee', organization: 'UN Committee on the Rights of the Child', url: 'https://www.ohchr.org/en/treaty-bodies/crc', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-girls-globe', organization: 'Girls Globe', url: 'https://girlsglobe.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5, 4], region: 'Global', language: 'en', requires_auth: false },

  // ── Racial and Ethnic Equity ────────────────────────────────────────────────
  { id: 'gen-un-decade-afrodescendants', organization: 'UN Decade for Afrodescendants', url: 'https://www.un.org/en/observances/decade-people-african-descent', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-raceforward-events', organization: 'Race Forward', url: 'https://www.raceforward.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'gen-meso-latinx', organization: 'Latino Equity Forum', url: 'https://www.latinoequityforum.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10], region: 'Americas-Latin', language: 'es', requires_auth: false },

  // ── Violence Against Women ──────────────────────────────────────────────────
  { id: 'gen-16days-events', organization: '16 Days of Activism', url: 'https://www.unwomen.org/en/what-we-do/ending-violence-against-women/take-action/16-days-of-activism', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-evaw-forum', organization: 'EVAW Coalition', url: 'https://evaw-global-database.unwomen.org/en', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-together-endvaw', organization: 'Together for Girls', url: 'https://www.togetherforgirls.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gen-parity-org', organization: 'Parity.org', url: 'https://parity.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5, 8], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'gen-wb-gender', organization: 'World Bank Gender', url: 'https://www.worldbank.org/en/topic/gender/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Global', language: 'en', requires_auth: false },
];
