import type { ScraperSource } from './types';

export const SOURCES_LATIN_AMERICA: ScraperSource[] = [

  // ── CEPAL / ECLAC ───────────────────────────────────────────────────────────
  { id: 'la-cepal-events', organization: 'CEPAL/ECLAC', url: 'https://www.cepal.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [8, 17], region: 'Americas-Latin', language: 'en', requires_auth: false },
  { id: 'la-cepal-forum', organization: 'CEPAL Forum', url: 'https://foroconsultivo.cepal.org/ilpes/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-cepal-stats', organization: 'CEPAL Statistics', url: 'https://estadisticas.cepal.org/cepalstat/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-cepal-gender', organization: 'CEPAL Gender', url: 'https://www.cepal.org/en/events?category=gender', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-cepal-env', organization: 'CEPAL Environment', url: 'https://www.cepal.org/en/subtopics/environment-development', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [13, 15], region: 'Americas-Latin', language: 'es', requires_auth: false },

  // ── Inter-American System ───────────────────────────────────────────────────
  { id: 'la-oas-events', organization: 'OAS', url: 'https://www.oas.org/en/media_center/events.asp', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16, 17], region: 'Americas-Latin', language: 'en', requires_auth: false },
  { id: 'la-paho-events', organization: 'PAHO', url: 'https://www.paho.org/en/news/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'en', requires_auth: false },
  { id: 'la-iadb-events', organization: 'IDB', url: 'https://www.iadb.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8, 17], region: 'Americas-Latin', language: 'en', requires_auth: false },
  { id: 'la-iadb-annual', organization: 'IDB Annual Meeting', url: 'https://www.iadb.org/en/about-us/annual-meetings', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8, 17], region: 'Americas-Latin', language: 'en', requires_auth: false },
  { id: 'la-idbinvest-events', organization: 'IDB Invest', url: 'https://www.idbinvest.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8], region: 'Americas-Latin', language: 'en', requires_auth: false },
  { id: 'la-iachr-events', organization: 'IACHR', url: 'https://www.oas.org/en/iachr/sessions/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Americas-Latin', language: 'en', requires_auth: false },

  // ── CARICOM ────────────────────────────────────────────────────────────────
  { id: 'la-caricom-events', organization: 'CARICOM', url: 'https://caricom.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Americas-Caribbean', language: 'en', requires_auth: false },
  { id: 'la-caricom-summit', organization: 'CARICOM Summit', url: 'https://caricom.org/meetings/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Americas-Caribbean', language: 'en', requires_auth: false },
  { id: 'la-caricom-health', organization: 'CARPHA', url: 'https://carpha.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Caribbean', language: 'en', requires_auth: false },
  { id: 'la-caricom-development', organization: 'CDB Caribbean', url: 'https://www.caribank.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8, 17], region: 'Americas-Caribbean', language: 'en', requires_auth: false },
  { id: 'la-oecs-events', organization: 'OECS', url: 'https://www.oecs.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Americas-Caribbean', language: 'en', requires_auth: false },

  // ── Andean Community ───────────────────────────────────────────────────────
  { id: 'la-can-events', organization: 'Andean Community', url: 'https://www.comunidadandina.org/en/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-can-environment', organization: 'Andean Community Environment', url: 'https://www.comunidadandina.org/en/medio-ambiente/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13, 15], region: 'Americas-Latin', language: 'es', requires_auth: false },

  // ── MERCOSUR ────────────────────────────────────────────────────────────────
  { id: 'la-mercosur-events', organization: 'MERCOSUR', url: 'https://www.mercosur.int/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17, 8], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-mercosur-health', organization: 'MERCOSUR Health', url: 'https://www.mercosur.int/tematics/salud/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'es', requires_auth: false },

  // ── UNASUR and CELAC ───────────────────────────────────────────────────────
  { id: 'la-celac-events', organization: 'CELAC', url: 'https://celac.org/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-prosur-events', organization: 'PROSUR', url: 'https://prosuramericas.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Americas-Latin', language: 'es', requires_auth: false },

  // ── Brazil ─────────────────────────────────────────────────────────────────
  { id: 'la-br-mre-events', organization: 'Itamaraty Brazil', url: 'https://www.gov.br/mre/en/news-and-agenda/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [17, 16], region: 'Americas-Latin', language: 'pt', requires_auth: false },
  { id: 'la-br-health-events', organization: 'Ministry of Health Brazil', url: 'https://www.gov.br/saude/en/news/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'pt', requires_auth: false },
  { id: 'la-br-education-events', organization: 'Ministry of Education Brazil', url: 'https://www.gov.br/mec/pt-br/eventos', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Americas-Latin', language: 'pt', requires_auth: false },
  { id: 'la-br-environment-events', organization: 'Ministry of Environment Brazil', url: 'https://www.gov.br/mma/pt-br/eventos', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [13, 15], region: 'Americas-Latin', language: 'pt', requires_auth: false },
  { id: 'la-fiocruz-events', organization: 'Fiocruz Brazil', url: 'https://www.fiocruz.br/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'pt', requires_auth: false },
  { id: 'la-ipea-events', organization: 'IPEA Brazil', url: 'https://www.ipea.gov.br/portal/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 8], region: 'Americas-Latin', language: 'pt', requires_auth: false },
  { id: 'la-inpe-events', organization: 'INPE Brazil', url: 'https://www.inpe.br/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13], region: 'Americas-Latin', language: 'pt', requires_auth: false },
  { id: 'la-imazon-events', organization: 'Imazon', url: 'https://imazon.org.br/en/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [15, 13], region: 'Americas-Latin', language: 'pt', requires_auth: false },
  { id: 'la-idb-brazil', organization: 'IDB Brazil', url: 'https://www.iadb.org/en/countries/brazil/overview', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8], region: 'Americas-Latin', language: 'pt', requires_auth: false },
  { id: 'la-usp-events', organization: 'USP São Paulo', url: 'https://www5.usp.br/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Americas-Latin', language: 'pt', requires_auth: false },
  { id: 'la-unicamp-events', organization: 'UNICAMP', url: 'https://www.unicamp.br/unicamp/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Americas-Latin', language: 'pt', requires_auth: false },
  { id: 'la-fgv-events', organization: 'FGV Brazil', url: 'https://portal.fgv.br/eventos', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8, 16], region: 'Americas-Latin', language: 'pt', requires_auth: false },
  { id: 'la-cebri-events', organization: 'CEBRI Brazil', url: 'https://cebri.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17, 16], region: 'Americas-Latin', language: 'pt', requires_auth: false },

  // ── Mexico ──────────────────────────────────────────────────────────────────
  { id: 'la-mx-sre-events', organization: 'Secretaría de Relaciones Exteriores Mexico', url: 'https://www.gob.mx/sre/eventos', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [17, 16], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-mx-health-events', organization: 'Secretaría de Salud Mexico', url: 'https://www.gob.mx/salud/eventos', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-mx-education-events', organization: 'SEP Mexico', url: 'https://www.gob.mx/sep/eventos', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-mx-environment-events', organization: 'SEMARNAT Mexico', url: 'https://www.gob.mx/semarnat/eventos', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [13, 15], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-mx-conacyt-events', organization: 'CONACYT Mexico', url: 'https://conahcyt.mx/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [9], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-unam-events', organization: 'UNAM Mexico', url: 'https://www.unam.mx/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-cide-events', organization: 'CIDE Mexico', url: 'https://www.cide.edu/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16, 8], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-imco-events', organization: 'IMCO Mexico', url: 'https://imco.org.mx/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8, 16], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-funsalud-events', organization: 'Funsalud Mexico', url: 'https://www.funsalud.org.mx/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-tec-monterrey-events', organization: 'Tec de Monterrey', url: 'https://tec.mx/es/agenda', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 8], region: 'Americas-Latin', language: 'es', requires_auth: false },

  // ── Colombia ────────────────────────────────────────────────────────────────
  { id: 'la-co-cancilleria', organization: 'Cancillería Colombia', url: 'https://www.cancilleria.gov.co/newsroom/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-co-dnp-events', organization: 'DNP Colombia', url: 'https://www.dnp.gov.co/Paginas/eventos.aspx', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17, 8], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-uniandes-events', organization: 'Universidad de los Andes', url: 'https://uniandes.edu.co/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 8], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-cerac-events', organization: 'CERAC Colombia', url: 'https://www.cerac.org.co/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-pnud-colombia', organization: 'PNUD Colombia', url: 'https://www.undp.org/es/colombia/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 17], region: 'Americas-Latin', language: 'es', requires_auth: false },

  // ── Argentina ───────────────────────────────────────────────────────────────
  { id: 'la-ar-cancilleria', organization: 'Cancillería Argentina', url: 'https://www.cancilleria.gob.ar/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-ar-mec-events', organization: 'Ministry of Education Argentina', url: 'https://www.educ.ar/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-conicet-events', organization: 'CONICET Argentina', url: 'https://www.conicet.gov.ar/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [9], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-cippec-events', organization: 'CIPPEC Argentina', url: 'https://www.cippec.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16, 8], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-uba-events', organization: 'UBA Argentina', url: 'https://www.uba.ar/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Americas-Latin', language: 'es', requires_auth: false },

  // ── Chile ───────────────────────────────────────────────────────────────────
  { id: 'la-cl-minrel-events', organization: 'MINREL Chile', url: 'https://www.minrel.gob.cl/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-puc-chile', organization: 'PUC Chile', url: 'https://www.uc.cl/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-uchile-events', organization: 'University of Chile', url: 'https://www.uchile.cl/agenda', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-clapcs-events', organization: 'CLAP Chile', url: 'https://www.clap.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'es', requires_auth: false },

  // ── Peru ────────────────────────────────────────────────────────────────────
  { id: 'la-pe-mre-events', organization: 'Ministry of Foreign Affairs Peru', url: 'https://www.gob.pe/rree/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-grade-events', organization: 'GRADE Peru', url: 'https://www.grade.org.pe/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 4], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-pucp-events', organization: 'PUCP Peru', url: 'https://www.pucp.edu.pe/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Americas-Latin', language: 'es', requires_auth: false },

  // ── Ecuador ─────────────────────────────────────────────────────────────────
  { id: 'la-ec-mre-events', organization: 'Cancillería Ecuador', url: 'https://www.cancilleria.gob.ec/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-flacso-ecuador', organization: 'FLACSO Ecuador', url: 'https://www.flacso.edu.ec/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16, 4], region: 'Americas-Latin', language: 'es', requires_auth: false },

  // ── Bolivia ─────────────────────────────────────────────────────────────────
  { id: 'la-bo-mmfa-events', organization: 'Ministry of Foreign Affairs Bolivia', url: 'https://www.cancilleria.gob.bo/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Americas-Latin', language: 'es', requires_auth: false },

  // ── Venezuela ───────────────────────────────────────────────────────────────
  { id: 'la-ve-undp-events', organization: 'UNDP Venezuela', url: 'https://www.undp.org/venezuela/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 17], region: 'Americas-Latin', language: 'es', requires_auth: false },

  // ── Central America ─────────────────────────────────────────────────────────
  { id: 'la-sica-events', organization: 'SICA', url: 'https://www.sica.int/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-sieca-events', organization: 'SIECA', url: 'https://www.sieca.int/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8, 17], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-ccad-events', organization: 'CCAD', url: 'https://www.sica.int/ccad/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13, 15], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-bcie-events', organization: 'BCIE', url: 'https://www.bcie.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-gt-usac-events', organization: 'USAC Guatemala', url: 'https://www.usac.edu.gt/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-cr-ucr-events', organization: 'UCR Costa Rica', url: 'https://www.ucr.ac.cr/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Americas-Latin', language: 'es', requires_auth: false },

  // ── Caribbean ──────────────────────────────────────────────────────────────
  { id: 'la-uw-west-indies', organization: 'University of the West Indies', url: 'https://www.uwi.edu/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Americas-Caribbean', language: 'en', requires_auth: false },
  { id: 'la-uw-mona-events', organization: 'UWI Mona Jamaica', url: 'https://www.mona.uwi.edu/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Americas-Caribbean', language: 'en', requires_auth: false },
  { id: 'la-cdc-caribbean', organization: 'CDEMA', url: 'https://www.cdema.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11, 13], region: 'Americas-Caribbean', language: 'en', requires_auth: false },
  { id: 'la-carpha-events', organization: 'CARPHA', url: 'https://carpha.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Caribbean', language: 'en', requires_auth: false },
  { id: 'la-crfm-events', organization: 'CRFM', url: 'https://www.crfm.int/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [14], region: 'Americas-Caribbean', language: 'en', requires_auth: false },

  // ── Latin American Development Organizations ────────────────────────────────
  { id: 'la-undp-lac', organization: 'UNDP LAC', url: 'https://www.undp.org/latin-america/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 17], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-unicef-lac', organization: 'UNICEF LAC', url: 'https://www.unicef.org/lac/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-who-amro', organization: 'WHO AMRO', url: 'https://www.paho.org/en/news/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'en', requires_auth: false },
  { id: 'la-worldbank-lac', organization: 'World Bank LAC', url: 'https://www.worldbank.org/en/region/lac/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 8], region: 'Americas-Latin', language: 'en', requires_auth: false },
  { id: 'la-caf-events', organization: 'CAF LAC', url: 'https://www.caf.com/en/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8, 17], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-giz-lac', organization: 'GIZ LAC', url: 'https://www.giz.de/en/worldwide/latin-america-and-caribbean.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-afd-lac', organization: 'AFD LAC', url: 'https://www.afd.fr/en/carte-des-projets/latin-america-and-caribbean', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-jica-lac', organization: 'JICA LAC', url: 'https://www.jica.go.jp/english/our_work/where_we_work/america/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-usaid-lac', organization: 'USAID LAC', url: 'https://www.usaid.gov/latin-american-and-caribbean', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Americas-Latin', language: 'en', requires_auth: false },

  // ── Latin American Civil Society ────────────────────────────────────────────
  { id: 'la-wola-events', organization: 'WOLA', url: 'https://www.wola.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16, 10], region: 'Americas-Latin', language: 'en', requires_auth: false },
  { id: 'la-dplf-events', organization: 'DPLF', url: 'https://www.dplf.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Americas-Latin', language: 'en', requires_auth: false },
  { id: 'la-ilanud-events', organization: 'ILANUD', url: 'https://www.ilanud.or.cr/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-cels-events', organization: 'CELS Argentina', url: 'https://www.cels.org.ar/web/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16, 10], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-oxfam-lac', organization: 'Oxfam LAC', url: 'https://www.oxfam.org/en/countries/latin-america-and-caribbean', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 10], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-actionaid-lac', organization: 'ActionAid LAC', url: 'https://www.actionaid.org/latin-america/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1, 10], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-faorlac-events', organization: 'FAO LAC', url: 'https://www.fao.org/americas/noticias/ver/es/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-celade-events', organization: 'CELADE', url: 'https://www.cepal.org/en/celade-population-division', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5, 10], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-iwl-events', organization: 'IWL LAC', url: 'https://www.worldlearning.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 17], region: 'Americas-Latin', language: 'en', requires_auth: false },
  { id: 'la-lacea-events', organization: 'LACEA', url: 'https://www.lacea.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8], region: 'Americas-Latin', language: 'es', requires_auth: false },

  // ── Latin American Research Institutions ───────────────────────────────────
  { id: 'la-clacso-events', organization: 'CLACSO', url: 'https://www.clacso.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 10], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-flacso-events', organization: 'FLACSO Regional', url: 'https://www.flacso.org/eventos/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 16], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-incap-events', organization: 'INCAP', url: 'https://www.incap.int/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 3], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-iica-events', organization: 'IICA', url: 'https://www.iica.int/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-iila-events', organization: 'IILA', url: 'https://www.iila.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-prolades-events', organization: 'PROLADES', url: 'https://www.prolades.com/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-rimisp-events', organization: 'Rimisp', url: 'https://rimisp.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 1], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-desco-events', organization: 'DESCO Peru', url: 'https://www.desco.org.pe/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1, 2], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-borda-events', organization: 'La Borda', url: 'https://www.laborda.coop/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'la-proeib-events', organization: 'PROEIB Andes', url: 'https://www.proeibandes.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 10], region: 'Americas-Latin', language: 'es', requires_auth: false },
];
