import type { ScraperSource } from './types';

export const SOURCES_GOVERNANCE_PEACE: ScraperSource[] = [

  // ── UN Main Bodies ──────────────────────────────────────────────────────────
  { id: 'gov-unga-events', organization: 'UN General Assembly', url: 'https://www.un.org/en/ga/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [16, 17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-unsc-events', organization: 'UN Security Council', url: 'https://www.un.org/securitycouncil/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-ecosoc-events', organization: 'UN ECOSOC', url: 'https://www.un.org/ecosoc/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [16, 17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-hlpf-events', organization: 'UN HLPF', url: 'https://sustainabledevelopment.un.org/hlpf', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-un-desa', organization: 'UN DESA', url: 'https://www.un.org/development/desa/en/events.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [17], region: 'Global', language: 'en', requires_auth: false },

  // ── UN Peace and Security ───────────────────────────────────────────────────
  { id: 'gov-undpko-events', organization: 'UN Peacekeeping', url: 'https://peacekeeping.un.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-dppa-events', organization: 'UN DPPA', url: 'https://dppa.un.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-unoda-events', organization: 'UN ODA Disarmament', url: 'https://www.un.org/disarmament/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-unoca-events', organization: 'UNOCA', url: 'https://unoca.unmissions.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Africa-Central', language: 'en', requires_auth: false },
  { id: 'gov-unowas-events', organization: 'UNOWAS', url: 'https://unowas.unmissions.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Africa-West', language: 'en', requires_auth: false },

  // ── Rule of Law and Justice ────────────────────────────────────────────────
  { id: 'gov-unodc-events', organization: 'UNODC', url: 'https://www.unodc.org/unodc/en/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-icj-events', organization: 'ICJ', url: 'https://www.icj-cij.org/en/hearings', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-icc-events', organization: 'ICC', url: 'https://www.icc-cpi.int/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-idlo-events', organization: 'IDLO', url: 'https://www.idlo.int/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-icc-hague-events', organization: 'International Criminal Court Hague', url: 'https://www.icc-cpi.int/calendar', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'gov-itlos-events', organization: 'ITLOS', url: 'https://www.itlos.org/en/main/cases/list-of-cases/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [14, 16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-uncitral-events', organization: 'UNCITRAL', url: 'https://uncitral.un.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16, 17], region: 'Global', language: 'en', requires_auth: false },

  // ── Anti-Corruption ────────────────────────────────────────────────────────
  { id: 'gov-uncac-events', organization: 'UNCAC', url: 'https://www.unodc.org/unodc/en/corruption/events.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-transparency-intl', organization: 'Transparency International', url: 'https://www.transparency.org/en/news/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-anticorruption-forum', organization: 'IAAC', url: 'https://www.iaaca.net/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-g20-anticorruption', organization: 'G20 Anti-Corruption', url: 'https://www.g20.org/en/tracks/sherpa/anti-corruption', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-u4-events', organization: 'U4 Anti-Corruption Centre', url: 'https://www.u4.no/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-oecd-anticorr', organization: 'OECD Anti-Corruption', url: 'https://www.oecd.org/corruption-integrity/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },

  // ── Elections and Democracy ────────────────────────────────────────────────
  { id: 'gov-undp-governance', organization: 'UNDP Governance', url: 'https://www.undp.org/democratic-governance/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-idea-events', organization: 'International IDEA', url: 'https://www.idea.int/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-aceeeo-events', organization: 'ACEEEO', url: 'https://www.aceeeo.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Europe-East', language: 'en', requires_auth: false },
  { id: 'gov-ifes-events', organization: 'IFES', url: 'https://www.ifes.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-vdem-events', organization: 'V-Dem Institute', url: 'https://www.v-dem.net/en/news-publications/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-carter-center-democracy', organization: 'Carter Center Democracy', url: 'https://www.cartercenter.org/news/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-ndi-events', organization: 'National Democratic Institute', url: 'https://www.ndi.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-iri-events', organization: 'International Republican Institute', url: 'https://www.iri.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },

  // ── Think Tanks and Research ────────────────────────────────────────────────
  { id: 'gov-chatham-events', organization: 'Chatham House', url: 'https://www.chathamhouse.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [16, 17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-brookings-events', organization: 'Brookings Institution', url: 'https://www.brookings.edu/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [16, 17], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'gov-iiss-events', organization: 'IISS', url: 'https://www.iiss.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-sipri-events', organization: 'SIPRI', url: 'https://www.sipri.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Europe-Nordic', language: 'en', requires_auth: false },
  { id: 'gov-crisisgroup-events', organization: 'International Crisis Group', url: 'https://www.crisisgroup.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-odi-governance', organization: 'ODI Governance', url: 'https://odi.org/en/events/?q=governance', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-cgdev-events', organization: 'CGD Governance', url: 'https://www.cgdev.org/events?topic=governance', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-cpa-events', organization: 'Carnegie Peace', url: 'https://carnegieendowment.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-wilson-center', organization: 'Wilson Center', url: 'https://www.wilsoncenter.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [16, 17], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'gov-rand-events', organization: 'RAND Corporation', url: 'https://www.rand.org/pubs/events.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Americas-North', language: 'en', requires_auth: false },

  // ── Peacebuilding and Reconciliation ──────────────────────────────────────
  { id: 'gov-un-peacebuilding', organization: 'UN Peacebuilding Support', url: 'https://www.un.org/peacebuilding/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-interpeace-events', organization: 'Interpeace', url: 'https://www.interpeace.org/news-events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-saferworld-events', organization: 'Saferworld', url: 'https://www.saferworld.org.uk/news-and-views/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-seeds-peace', organization: 'Seeds of Peace', url: 'https://www.seedsofpeace.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-africa-peacebuilding', organization: 'African Peacebuilding Network', url: 'https://www.ssrc.org/programs/african-peacebuilding-network/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'gov-conciliation-resources', organization: 'Conciliation Resources', url: 'https://www.c-r.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-berghof-events', organization: 'Berghof Foundation', url: 'https://berghof-foundation.org/news/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-irenees-events', organization: 'Irenees', url: 'https://www.irenees.net/en/evenements.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },

  // ── Global Governance Reform ───────────────────────────────────────────────
  { id: 'gov-g20-leaders', organization: 'G20', url: 'https://www.g20.org/en/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-g7-events', organization: 'G7', url: 'https://www.g7italy.it/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-oecd-governance', organization: 'OECD Governance', url: 'https://www.oecd.org/governance/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16, 17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-council-europe', organization: 'Council of Europe', url: 'https://www.coe.int/en/web/portal/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [16], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'gov-ipu-events', organization: 'IPU', url: 'https://www.ipu.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-un-forum-govtech', organization: 'UN GovTech', url: 'https://www.un.org/techenvoy/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16, 9], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-world-justice', organization: 'World Justice Project', url: 'https://worldjusticeproject.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },

  // ── Open Government and Transparency ──────────────────────────────────────
  { id: 'gov-ogi-events', organization: 'Open Government Partnership', url: 'https://www.opengovpartnership.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-gpar-events', organization: 'Global Public Administration Forum', url: 'https://www.un.org/development/desa/governance/events.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-article19-events', organization: 'Article 19', url: 'https://www.article19.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-freedomhouse-events', organization: 'Freedom House', url: 'https://freedomhouse.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-rsf-events', organization: 'Reporters Without Borders', url: 'https://rsf.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'gov-globalwitness-events', organization: 'Global Witness', url: 'https://www.globalwitness.org/en/campaigns/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },

  // ── Regional Governance ────────────────────────────────────────────────────
  { id: 'gov-igad-peace', organization: 'IGAD Peace and Security', url: 'https://igad.int/divisions/peace-and-security', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'gov-ecowas-peace', organization: 'ECOWAS Peace and Security', url: 'https://www.ecowas.int/institutions/ecowas-commission/department-of-political-affairs-peace-and-security/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Africa-West', language: 'en', requires_auth: false },
  { id: 'gov-au-psc-events', organization: 'AU Peace and Security Council', url: 'https://www.peaceau.org/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'gov-osce-events', organization: 'OSCE', url: 'https://www.osce.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [16], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'gov-oas-events', organization: 'OAS', url: 'https://www.oas.org/en/media_center/events.asp', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Americas', language: 'en', requires_auth: false },
  { id: 'gov-asean-political', organization: 'ASEAN Political-Security', url: 'https://asean.org/asean-political-security-community/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'gov-sco-events', organization: 'Shanghai Cooperation Organisation', url: 'https://eng.sectsco.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Asia-Central', language: 'en', requires_auth: false },
];
