import type { ScraperSource } from './types';

export const SOURCES_FOOD_AGRICULTURE: ScraperSource[] = [

  // ── FAO ─────────────────────────────────────────────────────────────────────
  { id: 'agr-fao-events', organization: 'FAO', url: 'https://www.fao.org/events/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [2, 15], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-fao-council', organization: 'FAO Council', url: 'https://www.fao.org/fao-who-codexalimentarius/meetings/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-fao-coag', organization: 'FAO COAG', url: 'https://www.fao.org/agriculture/meetings/coag/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-fao-cropsites', organization: 'FAO Crop Prospects', url: 'https://www.fao.org/giews/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-fao-africa', organization: 'FAO Africa', url: 'https://www.fao.org/africa/news/detail-news/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'agr-fao-asia', organization: 'FAO Asia-Pacific', url: 'https://www.fao.org/asiapacific/news/detail-news/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Asia-Pacific', language: 'en', requires_auth: false },
  { id: 'agr-fao-latin', organization: 'FAO Latin America', url: 'https://www.fao.org/americas/noticias/ver/es/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'agr-fao-near-east', organization: 'FAO Near East', url: 'https://www.fao.org/neareast/news/detail-news/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Middle-East', language: 'en', requires_auth: false },
  { id: 'agr-fao-codex', organization: 'Codex Alimentarius', url: 'https://www.fao.org/fao-who-codexalimentarius/meetings/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },

  // ── IFAD and WFP ────────────────────────────────────────────────────────────
  { id: 'agr-ifad-events', organization: 'IFAD', url: 'https://www.ifad.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [2, 1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-ifad-governing', organization: 'IFAD Governing Council', url: 'https://www.ifad.org/en/governing-council', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-wfp-events', organization: 'WFP', url: 'https://www.wfp.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-wfp-africa', organization: 'WFP Africa', url: 'https://www.wfp.org/regions/africa', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Africa', language: 'en', requires_auth: false },

  // ── CGIAR ───────────────────────────────────────────────────────────────────
  { id: 'agr-cgiar-events', organization: 'CGIAR', url: 'https://www.cgiar.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 15], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-irri-events', organization: 'IRRI', url: 'https://www.irri.org/news-and-events/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'agr-cimmyt-events', organization: 'CIMMYT', url: 'https://www.cimmyt.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-cip-events', organization: 'CIP', url: 'https://cipotato.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Americas-Latin', language: 'en', requires_auth: false },
  { id: 'agr-iita-events', organization: 'IITA', url: 'https://www.iita.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'agr-icarda-events', organization: 'ICARDA', url: 'https://www.icarda.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Middle-East', language: 'en', requires_auth: false },
  { id: 'agr-worldagroforestry', organization: 'World Agroforestry', url: 'https://www.worldagroforestry.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 15], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-iwmi-events', organization: 'IWMI', url: 'https://www.iwmi.cgiar.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 6], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-ciat-events', organization: 'Alliance of Bioversity-CIAT', url: 'https://alliancebioversityciat.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 15], region: 'Americas-Latin', language: 'en', requires_auth: false },
  { id: 'agr-icraf-events', organization: 'ICRAF', url: 'https://www.worldagroforestry.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 15], region: 'Africa', language: 'en', requires_auth: false },

  // ── Food Security ──────────────────────────────────────────────────────────
  { id: 'agr-cfs-events', organization: 'UN Committee on World Food Security', url: 'https://www.fao.org/cfs/sessions/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-fsin-events', organization: 'Food Security Information Network', url: 'https://www.fsinplatform.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-ipc-food', organization: 'IPC Platform', url: 'https://www.ipcinfo.org/ipcinfo-website/events/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-sofa-report', organization: 'State of Food Security', url: 'https://www.fao.org/publications/sofi/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-gsf-events', organization: 'Global Soil Forum', url: 'https://www.globalsoilpartnership.org/en/pillars/soil-information/global-soil-week/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 15], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-grain-events', organization: 'GRAIN', url: 'https://grain.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-agrifood-economics', organization: 'AgriFood Economics', url: 'https://agrifood.net/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 8], region: 'Global', language: 'en', requires_auth: false },

  // ── Sustainable Agriculture ────────────────────────────────────────────────
  { id: 'agr-ifoam-events', organization: 'IFOAM Organics', url: 'https://www.ifoam.bio/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 12], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-agroecology', organization: 'Agroecology Fund', url: 'https://www.agroecologyfund.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 15], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-conservation-agr', organization: 'Conservation Agriculture', url: 'https://www.fao.org/conservation-agriculture/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 15], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-groundswell-intl', organization: 'Groundswell International', url: 'https://www.groundswellinternational.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-acdi-voca', organization: 'ACDI/VOCA', url: 'https://www.acdivoca.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-fwr-events', organization: 'Future Food Institute', url: 'https://www.futurefoodinstitute.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 12], region: 'Global', language: 'en', requires_auth: false },

  // ── Agriculture Conferences ────────────────────────────────────────────────
  { id: 'agr-gfar-events', organization: 'GFAR', url: 'https://www.gfar.net/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-agrisem-events', organization: 'AGRISEM', url: 'https://www.agrisem.eu/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'agr-world-agri-tech', organization: 'World Agri-Tech Summit', url: 'https://worldagritechsummit.com/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 9], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-euragri-events', organization: 'European Agricultural Economics', url: 'https://www.eaae.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'agr-iaae-events', organization: 'IAAE', url: 'https://www.iaae-agecon.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-nyas-food', organization: 'NYAS Food Sustainability', url: 'https://www.nyas.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'agr-terra-food', organization: 'Terra Madre Salone del Gusto', url: 'https://www.slowfood.com/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 12], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'agr-ifama-events', organization: 'IFAMA', url: 'https://ifama.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 8], region: 'Global', language: 'en', requires_auth: false },

  // ── Land and Biodiversity ──────────────────────────────────────────────────
  { id: 'agr-unccd-events', organization: 'UNCCD', url: 'https://www.unccd.int/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [15, 2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-cbd-sbstta', organization: 'CBD SBSTTA', url: 'https://www.cbd.int/meetings/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [15, 2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-ipbes-events', organization: 'IPBES', url: 'https://ipbes.net/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [15, 2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-iucn-food', organization: 'IUCN Food & Agriculture', url: 'https://www.iucn.org/events?theme=food-agriculture', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [15, 2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-land-coalition', organization: 'International Land Coalition', url: 'https://www.landcoalition.org/en/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-iiasa-events', organization: 'IIASA Food', url: 'https://iiasa.ac.at/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 15], region: 'Europe', language: 'en', requires_auth: false },

  // ── Regional Agriculture ────────────────────────────────────────────────────
  { id: 'agr-caadp-events', organization: 'CAADP', url: 'https://www.nepad.org/caadp/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'agr-agra-events', organization: 'AGRA', url: 'https://agra.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'agr-fanrpan-events', organization: 'FANRPAN', url: 'https://www.fanrpan.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Africa-Southern', language: 'en', requires_auth: false },
  { id: 'agr-aatf-events', organization: 'AATF Africa', url: 'https://www.aatf-africa.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'agr-asareca-events', organization: 'ASARECA', url: 'https://www.asareca.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'agr-coraf-events', organization: 'CORAF', url: 'https://www.coraf.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Africa-West', language: 'en', requires_auth: false },
  { id: 'agr-apec-food', organization: 'APEC Food Security', url: 'https://www.apec.org/Groups/SOM-Steering-Committee-on-Economic-and-Technical-Cooperation/Working-Groups/Agricultural-Technical-Cooperation', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Asia-Pacific', language: 'en', requires_auth: false },
  { id: 'agr-saarc-agri', organization: 'SAARC Agriculture', url: 'https://www.saarc-sec.org/Agriculture/3/5', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'agr-procasur-events', organization: 'PROCASUR', url: 'https://procasur.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Americas-Latin', language: 'es', requires_auth: false },

  // ── Nutrition ──────────────────────────────────────────────────────────────
  { id: 'agr-sun-events', organization: 'SUN Movement', url: 'https://scalingupnutrition.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-nutrition-intl', organization: 'Nutrition International', url: 'https://www.nutritionintl.org/news-events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-who-nutrition', organization: 'WHO Nutrition', url: 'https://www.who.int/activities/nutrition', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-icn3-events', organization: 'International Conference on Nutrition', url: 'https://www.fao.org/nutrition/policies-programmes/icn2/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-iuns-events', organization: 'International Union of Nutritional Sciences', url: 'https://www.iuns.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-gain-events', organization: 'GAIN', url: 'https://www.gainhealth.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 3], region: 'Global', language: 'en', requires_auth: false },

  // ── Fisheries and Aquaculture ───────────────────────────────────────────────
  { id: 'agr-fao-cofi', organization: 'FAO COFI', url: 'https://www.fao.org/fishery/en/body/cofi', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [14, 2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-worldfish-events', organization: 'WorldFish', url: 'https://www.worldfishcenter.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [14, 2], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'agr-eaa-events', organization: 'European Aquaculture Society', url: 'https://www.was.org/meetings/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [14, 2], region: 'Global', language: 'en', requires_auth: false },

  // ── Forestry ───────────────────────────────────────────────────────────────
  { id: 'agr-unff-events', organization: 'UN Forum on Forests', url: 'https://www.un.org/esa/forests/events/index.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [15, 13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-iufro-events', organization: 'IUFRO', url: 'https://www.iufro.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [15], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-tropenbos-events', organization: 'Tropenbos International', url: 'https://www.tropenbos.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [15], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-cifor-events', organization: 'CIFOR', url: 'https://www.cifor.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [15, 13], region: 'Asia-Southeast', language: 'en', requires_auth: false },
];
