import type { ScraperSource } from './types';

export const SOURCES_SOUTH_ASIA: ScraperSource[] = [

  // ── SAARC ───────────────────────────────────────────────────────────────────
  { id: 'sa-saarc-events', organization: 'SAARC', url: 'https://www.saarc-sec.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-saarc-summit', organization: 'SAARC Summit', url: 'https://www.saarc-sec.org/summits/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17, 16], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-saarc-culture', organization: 'SAARC Cultural Centre', url: 'https://www.saarccultural.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-saarc-finance', organization: 'SAARC Finance', url: 'https://www.saarc-sec.org/Finance/3/8', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-saarcfinance-events', organization: 'SAARCFinance', url: 'https://www.saarcfinance.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8, 17], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-saarc-disaster', organization: 'SAARC Disaster Management', url: 'https://www.sdmc.net.in/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11, 13], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-saarc-energy', organization: 'SAARC Energy Centre', url: 'https://www.saarcenergy.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [7], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-saarc-food', organization: 'SAARC Food Bank', url: 'https://www.saarc-sec.org/SFB/3/13', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Asia-South', language: 'en', requires_auth: false },

  // ── India ───────────────────────────────────────────────────────────────────
  { id: 'sa-in-mea-events', organization: 'Ministry of External Affairs India', url: 'https://www.mea.gov.in/events.htm', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [17, 16], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-in-health-events', organization: 'Ministry of Health India', url: 'https://www.mohfw.gov.in/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-in-education-events', organization: 'Ministry of Education India', url: 'https://www.education.gov.in/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-in-environment-events', organization: 'MOEFCC India', url: 'https://moef.gov.in/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [13, 15], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-in-agriculture-events', organization: 'Ministry of Agriculture India', url: 'https://www.agricoop.gov.in/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-in-finance-events', organization: 'Ministry of Finance India', url: 'https://www.finmin.nic.in/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8, 17], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-in-niti-events', organization: 'NITI Aayog India', url: 'https://www.niti.gov.in/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-in-rbi-events', organization: 'Reserve Bank of India', url: 'https://www.rbi.org.in/scripts/Events.aspx', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-in-icmr-events', organization: 'ICMR India', url: 'https://www.icmr.gov.in/events.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-in-csir-events', organization: 'CSIR India', url: 'https://www.csir.res.in/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [9], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-in-nhrc-events', organization: 'NHRC India', url: 'https://nhrc.nic.in/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-igidr-events', organization: 'IGIDR Mumbai', url: 'https://www.igidr.ac.in/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8, 1], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-cprindia-events', organization: 'CPR India', url: 'https://www.cprindia.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16, 17], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-idfc-india', organization: 'IDFC Institute India', url: 'https://www.idfcinstitute.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8, 11], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-iimahm-events', organization: 'IIM Ahmedabad', url: 'https://www.iima.ac.in/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8, 4], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-tiss-events', organization: 'TISS Mumbai', url: 'https://www.tiss.edu/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10, 1], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-jnu-events', organization: 'Jawaharlal Nehru University', url: 'https://www.jnu.ac.in/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 16], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-wipro-foundation', organization: 'Wipro Foundation', url: 'https://www.wiprofoundation.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 8], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-azimpremji', organization: 'Azim Premji Foundation', url: 'https://azimpremjifoundation.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-in-observers-events', organization: 'Observer Research Foundation', url: 'https://www.orfonline.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16, 17], region: 'Asia-South', language: 'en', requires_auth: false },

  // ── Bangladesh ─────────────────────────────────────────────────────────────
  { id: 'sa-bd-mohfw-events', organization: 'Ministry of Health Bangladesh', url: 'https://www.mohfw.gov.bd/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-bd-moe-events', organization: 'Ministry of Education Bangladesh', url: 'https://www.moedu.gov.bd/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-bd-finance-events', organization: 'Ministry of Finance Bangladesh', url: 'https://mof.gov.bd/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-icddrb-events', organization: 'icddr,b', url: 'https://www.icddrb.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-brac-events', organization: 'BRAC Bangladesh', url: 'https://www.brac.net/news-and-events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 4], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-bdmof-events', organization: 'Bangladesh Bank', url: 'https://www.bb.org.bd/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-bids-events', organization: 'Bangladesh Institute of Development Studies', url: 'https://www.bids.org.bd/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1, 8], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-du-events', organization: 'University of Dhaka', url: 'https://du.ac.bd/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Asia-South', language: 'en', requires_auth: false },

  // ── Pakistan ────────────────────────────────────────────────────────────────
  { id: 'sa-pk-mofa-events', organization: 'Ministry of Foreign Affairs Pakistan', url: 'https://mofa.gov.pk/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17, 16], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-pk-health-events', organization: 'Ministry of National Health Pakistan', url: 'https://www.nhsrc.gov.pk/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-pk-education-events', organization: 'Ministry of Education Pakistan', url: 'https://www.mofept.gov.pk/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-pk-aga-events', organization: 'Aga Khan Development Network Pakistan', url: 'https://www.akdn.org/pakistan', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1, 3], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-pk-sdpi-events', organization: 'SDPI Pakistan', url: 'https://sdpi.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17, 13], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-lums-events', organization: 'LUMS Pakistan', url: 'https://lums.edu.pk/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 8], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-iobm-events', organization: 'IOBM Pakistan', url: 'https://www.iobm.edu.pk/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 8], region: 'Asia-South', language: 'en', requires_auth: false },

  // ── Sri Lanka ───────────────────────────────────────────────────────────────
  { id: 'sa-lk-mofa-events', organization: 'Ministry of Foreign Affairs Sri Lanka', url: 'https://www.mfa.gov.lk/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-lk-health-events', organization: 'Ministry of Health Sri Lanka', url: 'https://www.health.gov.lk/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-lk-cbsl-events', organization: 'Central Bank of Sri Lanka', url: 'https://www.cbsl.gov.lk/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-lk-ips-events', organization: 'IPS Sri Lanka', url: 'https://www.ips.lk/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8, 1], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-uc-colombo', organization: 'University of Colombo', url: 'https://cmb.ac.lk/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Asia-South', language: 'en', requires_auth: false },

  // ── Nepal ───────────────────────────────────────────────────────────────────
  { id: 'sa-np-mofa-events', organization: 'Ministry of Foreign Affairs Nepal', url: 'https://www.mofa.gov.np/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-np-mofe-events', organization: 'Ministry of Finance Nepal', url: 'https://www.mof.gov.np/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-np-npc-events', organization: 'National Planning Commission Nepal', url: 'https://www.npc.gov.np/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-tu-kathmandu', organization: 'Tribhuvan University', url: 'https://www.tribhuvan-university.edu.np/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-pra-nepal', organization: 'Practical Action Nepal', url: 'https://practicalaction.org/nepal/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1, 13], region: 'Asia-South', language: 'en', requires_auth: false },

  // ── Afghanistan ─────────────────────────────────────────────────────────────
  { id: 'sa-af-unama-events', organization: 'UNAMA', url: 'https://unama.unmissions.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16, 1], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-af-nrp-events', organization: 'Afghanistan NRP', url: 'https://www.undp.org/afghanistan/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 16], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-af-awdc-events', organization: 'Afghan Women Development Center', url: 'https://awdc.af/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5], region: 'Asia-South', language: 'en', requires_auth: false },

  // ── Bhutan ─────────────────────────────────────────────────────────────────
  { id: 'sa-bt-mofa-events', organization: 'Ministry of Foreign Affairs Bhutan', url: 'https://www.mfa.gov.bt/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-bt-gnh-events', organization: 'GNH Centre Bhutan', url: 'https://www.gnhcentrebhutan.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3, 10], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-rub-events', organization: 'Royal University of Bhutan', url: 'https://www.rub.edu.bt/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Asia-South', language: 'en', requires_auth: false },

  // ── Maldives ────────────────────────────────────────────────────────────────
  { id: 'sa-mv-mofa-events', organization: 'Ministry of Foreign Affairs Maldives', url: 'https://www.mfa.gov.mv/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17, 13], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-mv-climate-events', organization: 'Maldives Climate Change', url: 'https://www.climate.gov.mv/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13], region: 'Asia-South', language: 'en', requires_auth: false },

  // ── South Asian Development Organizations ──────────────────────────────────
  { id: 'sa-undp-india', organization: 'UNDP India', url: 'https://www.undp.org/india/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 17], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-undp-bangladesh', organization: 'UNDP Bangladesh', url: 'https://www.undp.org/bangladesh/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-undp-pakistan', organization: 'UNDP Pakistan', url: 'https://www.undp.org/pakistan/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-unicef-india', organization: 'UNICEF India', url: 'https://www.unicef.org/india/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-who-india', organization: 'WHO India', url: 'https://www.who.int/india/news/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-who-searo', organization: 'WHO SEARO', url: 'https://www.who.int/southeastasia/news/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-worldbank-india', organization: 'World Bank India', url: 'https://www.worldbank.org/en/country/india/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 8], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-adb-south-asia', organization: 'ADB South Asia', url: 'https://www.adb.org/where-we-work/south-asia/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8, 17], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-ifad-south-asia', organization: 'IFAD South Asia', url: 'https://www.ifad.org/en/web/knowledge/events?region=SA', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 1], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-giz-india', organization: 'GIZ India', url: 'https://www.giz.de/en/worldwide/368.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-jica-india', organization: 'JICA India', url: 'https://www.jica.go.jp/india/english/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-dfid-india', organization: 'FCDO India', url: 'https://www.gov.uk/world/india', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Asia-South', language: 'en', requires_auth: false },

  // ── South Asian Think Tanks ────────────────────────────────────────────────
  { id: 'sa-sac-events', organization: 'South Asia Centre', url: 'https://southasiacentre.lse.ac.uk/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17, 16], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-saceps-events', organization: 'SACEPS', url: 'https://saceps.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-icpd-india', organization: 'ICPD India', url: 'https://www.icpdindia.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5, 3], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-icssr-events', organization: 'ICSSR India', url: 'https://www.icssr.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-pids-events', organization: 'PIDS Philippines', url: 'https://www.pids.gov.ph/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8, 1], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-spdc-events', organization: 'SPDC Pakistan', url: 'https://www.spdc.org.pk/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1, 8], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-imi-india', organization: 'IMI New Delhi', url: 'https://www.imi.edu/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-ficci-events', organization: 'FICCI India', url: 'https://www.ficci.in/events.asp', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8, 17], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-cii-events', organization: 'CII India', url: 'https://www.cii.in/events.aspx', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-nasscom-events', organization: 'NASSCOM India', url: 'https://nasscom.in/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [9, 8], region: 'Asia-South', language: 'en', requires_auth: false },

  // ── South Asian Civil Society ──────────────────────────────────────────────
  { id: 'sa-sanhivaya-events', organization: 'South Asia Alliance', url: 'https://southasiaalliance.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-saievac-events', organization: 'SAIEVAC', url: 'https://www.saievac.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5, 10], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-sari-events', organization: 'SARI South Asia Research', url: 'https://www.sari.net.in/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-panos-sa', organization: 'Panos South Asia', url: 'https://www.panossouthasia.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-oxfam-india', organization: 'Oxfam India', url: 'https://www.oxfamindia.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 10], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-care-india', organization: 'CARE India', url: 'https://www.careindia.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 5], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-save-children-india', organization: 'Save the Children India', url: 'https://www.savethechildren.in/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 4], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-path-india', organization: 'PATH India', url: 'https://www.path.org/india/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3], region: 'Asia-South', language: 'en', requires_auth: false },

  // ── South Asian Universities ───────────────────────────────────────────────
  { id: 'sa-iit-bombay', organization: 'IIT Bombay', url: 'https://www.iitb.ac.in/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [9, 4], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-iit-madras', organization: 'IIT Madras', url: 'https://www.iitm.ac.in/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [9, 4], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-iisc-events', organization: 'IISc Bangalore', url: 'https://www.iisc.ac.in/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [9], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-uoc-events', organization: 'University of Calcutta', url: 'https://www.caluniv.ac.in/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-pu-events', organization: 'Punjab University', url: 'https://www.pu.ac.pk/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-aku-events', organization: 'Aga Khan University South Asia', url: 'https://www.aku.edu/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-aiims-events', organization: 'AIIMS Delhi', url: 'https://www.aiims.edu/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Asia-South', language: 'en', requires_auth: false },

  // ── Regional Conferences ───────────────────────────────────────────────────
  { id: 'sa-sarchi-events', organization: 'South Asian Regional Conference', url: 'https://www.southasiaconference.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-saath-events', organization: 'SAATH', url: 'https://www.saath.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1, 10], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-safma-events', organization: 'SAFMA', url: 'https://www.safma.net/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-csrsa-events', organization: 'CSR South Asia', url: 'https://csrsouthasia.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17, 8], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-sapan-events', organization: 'South Asia Partnership Network', url: 'https://www.sapan.net/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-sdrf-events', organization: 'South Asia Development Research Forum', url: 'https://www.sadrf.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17, 1], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-ncaer-events', organization: 'NCAER India', url: 'https://www.ncaer.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8, 1], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-wri-india', organization: 'WRI India', url: 'https://wri.org.in/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [13, 11], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-terri-events', organization: 'TERI India', url: 'https://www.teriin.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [13, 7], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-iima-events', organization: 'IIMA Development', url: 'https://www.iima.ac.in/research/areas/public-policy', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16, 8], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-unnati-events', organization: 'UNNATI India', url: 'https://www.unnati.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1, 4], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-pria-events', organization: 'PRIA India', url: 'https://www.pria.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16, 10], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-sacs-events', organization: 'SACS South Asia', url: 'https://www.sacs.in/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'sa-isst-events', organization: 'ISST India', url: 'https://www.isst.in/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [5, 8], region: 'Asia-South', language: 'en', requires_auth: false },
];
