import type { ScraperSource } from './types';

export const SOURCES_YOUTH_STUDENTS: ScraperSource[] = [

  // ── UN Youth Bodies ────────────────────────────────────────────────────────
  { id: 'yth-un-youth-events', organization: 'UN Youth', url: 'https://www.un.org/en/contact-us/youth', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-unoy-events', organization: 'UNOY Peacebuilders', url: 'https://www.unoy.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-unicef-youth', organization: 'UNICEF Youth', url: 'https://www.unicef.org/youth', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-undp-youth', organization: 'UNDP Youth', url: 'https://www.undp.org/sustainable-development-goals/youth', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-who-youth', organization: 'WHO Youth', url: 'https://www.who.int/news-room/events?healthtopics=youth', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-unfpa-youth', organization: 'UNFPA Youth', url: 'https://www.unfpa.org/young-people', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-unep-youth', organization: 'UNEP Youth', url: 'https://www.unep.org/youth', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [13, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-ilo-youth', organization: 'ILO Youth Employment', url: 'https://www.ilo.org/global/topics/youth-employment/lang--en/index.htm', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-hlpf-youth', organization: 'Major Group Children and Youth', url: 'https://www.un.org/development/desa/youth/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-sdsn-youth', organization: 'SDSN Youth', url: 'https://sdsnyouth.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Global', language: 'en', requires_auth: false },

  // ── Youth Climate Movements ────────────────────────────────────────────────
  { id: 'yth-youngo-events', organization: 'YOUNGO Climate', url: 'https://youthclimatemovement.wordpress.com/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-350-youth', organization: '350.org Youth', url: 'https://350.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-yca-events', organization: 'Youth Climate Action', url: 'https://youthclimateleaders.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-climate-reality', organization: 'Climate Reality Youth', url: 'https://www.climaterealityproject.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-yfcc-events', organization: 'Youth for Climate Change', url: 'https://youthforclimatechange.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-gcyf-events', organization: 'Global Climate Youth Forum', url: 'https://www.globalyouthclimateconference.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-cop-youth', organization: 'COP Youth Delegation', url: 'https://unfccc.int/topics/youth', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13], region: 'Global', language: 'en', requires_auth: false },

  // ── Student Organizations – Global ─────────────────────────────────────────
  { id: 'yth-isf-events', organization: 'International Student Forum', url: 'https://www.esib.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-aiesec-events', organization: 'AIESEC', url: 'https://aiesec.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-nusas-events', organization: 'NUSAS', url: 'https://nusas.org.za/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Africa-Southern', language: 'en', requires_auth: false },
  { id: 'yth-afrisa-events', organization: 'African Students Union', url: 'https://www.africansunion.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'yth-wus-events', organization: 'World University Service', url: 'https://www.wusgermany.de/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-iflry-events', organization: 'IFLRY', url: 'https://www.iflry.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-ifmsa-events', organization: 'IFMSA', url: 'https://ifmsa.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-isads-events', organization: 'International Student Assembly', url: 'https://isads.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },

  // ── Youth Leadership and Entrepreneurship ──────────────────────────────────
  { id: 'yth-gybn-events', organization: 'Global Youth Biodiversity Network', url: 'https://gybn.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [15, 13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-one-young-world', organization: 'One Young World', url: 'https://www.oneyoungworld.com/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17, 8], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-ylc-events', organization: 'Youth Leaders Conference', url: 'https://youngprofessionalsnetwork.com/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 8], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-yali-events', organization: 'YALI', url: 'https://yali.state.gov/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8, 4], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'yth-ylp-africa', organization: 'Young Leaders Program Africa', url: 'https://youngafricalleaders.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'yth-desap-youth', organization: 'YES Youth Entrepreneurship', url: 'https://yes-network.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-gsbi-events', organization: 'Global Social Benefit Institute', url: 'https://www.scu-social-entrepreneurship.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8, 17], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'yth-hult-prize', organization: 'Hult Prize', url: 'https://www.hultprize.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-enactus-events', organization: 'Enactus', url: 'https://enactus.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-endeavor-events', organization: 'Endeavor', url: 'https://endeavor.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8], region: 'Global', language: 'en', requires_auth: false },

  // ── Model UN and Debating ─────────────────────────────────────────────────
  { id: 'yth-nmun-events', organization: 'National Model UN', url: 'https://www.nmun.org/events.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 16], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'yth-amun-events', organization: 'American Model UN', url: 'https://www.amun.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 16], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'yth-mun-conference', organization: 'Global MUN Conference', url: 'https://www.globalmun.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-best-delegate', organization: 'Best Delegate MUN', url: 'https://bestdelegate.com/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-afri-mun', organization: 'African Model UN', url: 'https://www.africamun.com/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 16], region: 'Africa', language: 'en', requires_auth: false },

  // ── Young Professionals Networks ───────────────────────────────────────────
  { id: 'yth-gpn-events', organization: 'Global Policy Network Youth', url: 'https://globalpolicynetwork.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-y20-events', organization: 'Y20 G20 Youth Summit', url: 'https://www.g20.org/en/tracks/youth', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-worldskills-youth', organization: 'WorldSkills Youth', url: 'https://worldskills.org/youth/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 8], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-ypard-events', organization: 'YPARD', url: 'https://ypard.net/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-wpay-events', organization: 'World Programme of Action for Youth', url: 'https://www.un.org/esa/socdev/unyin/events.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-global-shapers', organization: 'WEF Global Shapers', url: 'https://www.globalshapers.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-young-diplomats', organization: 'Young Diplomats Forum', url: 'https://www.youngdiplomats.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16, 17], region: 'Global', language: 'en', requires_auth: false },

  // ── Tech for Youth ─────────────────────────────────────────────────────────
  { id: 'yth-techforgood-youth', organization: 'Tech for Good Youth', url: 'https://techforgoodsummit.com/youth/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [9, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-wsis-youth', organization: 'WSIS Youth', url: 'https://www.itu.int/net4/wsis/forum/2025/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [9, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-itu-youth', organization: 'ITU Youth', url: 'https://www.itu.int/en/youth/Pages/default.aspx', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [9], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-digitalyouth-events', organization: 'Digital Youth Council', url: 'https://digitalyouthcouncil.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [9, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-codeathon-events', organization: 'Global Youth Code-a-thon', url: 'https://globalcode-a-thon.com/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [9], region: 'Global', language: 'en', requires_auth: false },

  // ── Regional Youth Bodies ──────────────────────────────────────────────────
  { id: 'yth-au-youth', organization: 'African Union Youth', url: 'https://www.au.int/en/youth', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 8], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'yth-ayc-events', organization: 'African Youth Council', url: 'https://www.africanyouthcouncil.net/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'yth-ayf-events', organization: 'African Youth Forum', url: 'https://www.africanyouthforum.net/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 8], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'yth-asean-youth', organization: 'ASEAN Youth Council', url: 'https://asean.org/communities/asean-socio-cultural-community/cluster/youth/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'yth-apyc-events', organization: 'Asia-Pacific Youth Council', url: 'https://apyc.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Asia-Pacific', language: 'en', requires_auth: false },
  { id: 'yth-eyp-events', organization: 'European Youth Parliament', url: 'https://eyp.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 16], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'yth-coe-youth', organization: 'Council of Europe Youth', url: 'https://www.coe.int/en/web/youth/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 16], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'yth-ecowas-youth', organization: 'ECOWAS Youth Council', url: 'https://www.ecowas.int/departments/human-development/youth/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Africa-West', language: 'en', requires_auth: false },
  { id: 'yth-arab-youth', organization: 'Arab Youth Forum', url: 'https://www.arabstateleague.org/youth/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Middle-East', language: 'ar', requires_auth: false },
  { id: 'yth-panam-youth', organization: 'Pan-American Youth Forum', url: 'https://www.oas.org/en/youth/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Americas', language: 'en', requires_auth: false },

  // ── Health and Rights for Young People ────────────────────────────────────
  { id: 'yth-youth-health-conf', organization: 'International Youth Health Conference', url: 'https://www.iyhconf.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-srhr-youth', organization: 'SRHR Youth Forum', url: 'https://www.ipas.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-youth-mental-health', organization: 'Youth Mental Health Forum', url: 'https://www.who.int/news-room/events?healthtopics=mental-health', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Global', language: 'en', requires_auth: false },

  // ── STEM and Research Competitions ────────────────────────────────────────
  { id: 'yth-intel-isef', organization: 'Regeneron ISEF', url: 'https://www.societyforscience.org/isef/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 9], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-imo-events', organization: 'International Mathematical Olympiad', url: 'https://www.imo-official.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-igem-events', organization: 'iGEM', url: 'https://igem.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [9, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-stem-net', organization: 'Global STEM Youth Forum', url: 'https://globalstemsummit.com/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 9], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-young-researchers', organization: 'Young Researchers Forum', url: 'https://www.youngresearchers.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 9], region: 'Global', language: 'en', requires_auth: false },

  // ── Social Action and Volunteering ─────────────────────────────────────────
  { id: 'yth-unv-events', organization: 'UNV Youth Volunteering', url: 'https://www.unv.org/news-and-resources/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-volunteerworld-events', organization: 'Volunteer World', url: 'https://www.volunteerworld.com/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-cuso-events', organization: 'CUSO International', url: 'https://cusointernational.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-points-of-light', organization: 'Points of Light', url: 'https://www.pointsoflight.org/news/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'yth-do-it-day', organization: 'Do It Day Youth Action', url: 'https://www.dosomething.org/us/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17, 4], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'yth-scout-world', organization: 'World Scout Bureau', url: 'https://www.scout.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-ywca-events', organization: 'YWCA World', url: 'https://www.worldywca.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-ymca-world', organization: 'World YMCA', url: 'https://www.ymca.int/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-rotary-youth', organization: 'Rotary Youth Exchange', url: 'https://www.rotary.org/en/our-programs/youth-exchanges', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17, 4], region: 'Global', language: 'en', requires_auth: false },

  // ── Youth SDG Forums ───────────────────────────────────────────────────────
  { id: 'yth-iysd-events', organization: 'International Youth Sustainable Development', url: 'https://www.iysd.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-gen-unlimited', organization: 'Generation Unlimited', url: 'https://www.generationunlimited.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 8], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-yps-forum', organization: 'Youth Peace and Security Forum', url: 'https://www.youth4peace.info/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-ifrc-youth', organization: 'IFRC Youth', url: 'https://www.ifrc.org/our-work/volunteers/youth', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-plan-youth-leaders', organization: 'Plan International Youth Leaders', url: 'https://plan-international.org/youth-participation/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5, 4], region: 'Global', language: 'en', requires_auth: false },

  // ── African National Youth Councils ───────────────────────────────────────
  { id: 'yth-ke-nyc', organization: 'Kenya National Youth Council', url: 'https://www.nyc.go.ke/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 8], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'yth-tz-nyc', organization: 'Tanzania National Youth Council', url: 'https://www.nyc.go.tz/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 8], region: 'Africa-East', language: 'sw', requires_auth: false },
  { id: 'yth-ug-nyc', organization: 'Uganda National Youth Council', url: 'https://nyc.go.ug/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 8], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'yth-et-nyc', organization: 'Ethiopia Youth Advisory Committee', url: 'https://www.youth.gov.et/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 8], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'yth-gh-nyc', organization: 'Ghana National Youth Authority', url: 'https://www.nya.gov.gh/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 8], region: 'Africa-West', language: 'en', requires_auth: false },
  { id: 'yth-ng-nysc', organization: 'Nigeria National Youth Service Corps', url: 'https://www.nysc.gov.ng/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 8], region: 'Africa-West', language: 'en', requires_auth: false },
  { id: 'yth-rw-nyc', organization: 'Rwanda National Youth Council', url: 'https://www.nyc.gov.rw/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'yth-za-nyc', organization: 'South Africa National Youth Development Agency', url: 'https://www.nyda.gov.za/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 8], region: 'Africa-Southern', language: 'en', requires_auth: false },
  { id: 'yth-sn-nyc', organization: 'Senegal Ministère de la Jeunesse', url: 'https://www.jeunesse.gouv.sn/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 8], region: 'Africa-West', language: 'fr', requires_auth: false },
  { id: 'yth-zm-nyc', organization: 'Zambia National Youth Council', url: 'https://www.nyc.org.zm/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 8], region: 'Africa-Southern', language: 'en', requires_auth: false },

  // ── Asian National Youth Councils ─────────────────────────────────────────
  { id: 'yth-in-nyc', organization: 'India Ministry of Youth Affairs', url: 'https://www.yas.nic.in/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 8], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'yth-bd-nyc', organization: 'Bangladesh Ministry of Youth', url: 'https://www.mosw.gov.bd/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 8], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'yth-pk-nyc', organization: 'Pakistan National Youth Assembly', url: 'https://www.nyas.gov.pk/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 8], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'yth-id-nyc', organization: 'Indonesia Ministry of Youth and Sports', url: 'https://www.kemenpora.go.id/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 8], region: 'Asia-Southeast', language: 'id', requires_auth: false },
  { id: 'yth-ph-nyc', organization: 'Philippines National Youth Commission', url: 'https://www.nyc.gov.ph/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 8], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'yth-th-nyc', organization: 'Thailand National Youth Bureau', url: 'https://www.dcy.go.th/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Asia-Southeast', language: 'th', requires_auth: false },
  { id: 'yth-vn-nyc', organization: 'Vietnam Youth Union', url: 'https://www.doanthanhnien.vn/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 8], region: 'Asia-Southeast', language: 'vi', requires_auth: false },
  { id: 'yth-np-nyc', organization: 'Nepal Youth Council', url: 'https://www.niyuwa.gov.np/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Asia-South', language: 'en', requires_auth: false },

  // ── Global South Youth MUNs ────────────────────────────────────────────────
  { id: 'yth-amun-africa', organization: 'African Model United Nations', url: 'https://www.africanmun.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 16], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'yth-naimun-events', organization: 'NAIMUN Nairobi', url: 'https://www.naimun.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 16], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'yth-gmun-ghana', organization: 'GMUN Ghana MUN', url: 'https://www.ghanamun.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 16], region: 'Africa-West', language: 'en', requires_auth: false },
  { id: 'yth-naimun-india', organization: 'NAIMUN India', url: 'https://www.naimun.in/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 16], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'yth-pimun-events', organization: 'PIMUN Philippines', url: 'https://www.pimun.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 16], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'yth-aismun-events', organization: 'AISMUN South Asia', url: 'https://www.aismun.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 16], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'yth-lamun-events', organization: 'Latin America MUN', url: 'https://www.lamun.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 16], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'yth-camun-events', organization: 'Caribbean MUN', url: 'https://www.caribbeanmun.com/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 16], region: 'Americas-Caribbean', language: 'en', requires_auth: false },

  // ── Youth Climate Networks ─────────────────────────────────────────────────
  { id: 'yth-youngo-events', organization: 'YOUNGO Youth Climate UNFCCC', url: 'https://www.youngo.uno/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [13, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-wyse-events', organization: 'World Youth Sustainable Energy', url: 'https://www.wyse.energy/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [7, 13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-gcca-youth', organization: 'GCCA Youth Climate', url: 'https://www.gcca.eu/youth', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-cyn-events', organization: 'Climate Youth Network', url: 'https://www.climateyouthnetwork.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-african-youth-climate', organization: 'African Youth for Climate Action', url: 'https://www.africanyouth4climateaction.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13, 4], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'yth-asia-youth-climate', organization: 'Asia Pacific Youth Climate Coalition', url: 'https://www.apycc.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13, 4], region: 'Asia-Pacific', language: 'en', requires_auth: false },
  { id: 'yth-lcoy-events', organization: 'Local Conference of Youth LCOY', url: 'https://www.lcoy.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-yca-events', organization: 'Youth Climate Activists', url: 'https://www.youthclimateactivists.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13], region: 'Global', language: 'en', requires_auth: false },

  // ── Youth Entrepreneurship ─────────────────────────────────────────────────
  { id: 'yth-yebi-events', organization: 'Youth Entrepreneurs Business Initiative', url: 'https://www.yebi.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-gybi-events', organization: 'Global Youth Business Initiative', url: 'https://www.ilo.org/empent/Projects/GYBI/lang--en/index.htm', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-ashoka-youth', organization: 'Ashoka Youth Changemakers', url: 'https://www.ashoka.org/en-us/program/youth-venture', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-yes-events', organization: 'Youth Employment Summit', url: 'https://www.yescoalition.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-youth-co-lab', organization: 'Youth Co:Lab UNDP', url: 'https://www.youthcolab.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8, 9], region: 'Asia-Pacific', language: 'en', requires_auth: false },
  { id: 'yth-tony-elumelu', organization: 'Tony Elumelu Entrepreneurship', url: 'https://www.tonyelumelufoundation.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'yth-seedstars-events', organization: 'Seedstars Africa', url: 'https://www.seedstars.com/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8, 9], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'yth-aban-events', organization: 'African Business Angel Network', url: 'https://www.africanban.com/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8, 9], region: 'Africa', language: 'en', requires_auth: false },

  // ── Student Health and Wellbeing ──────────────────────────────────────────
  { id: 'yth-ifmsa-events', organization: 'IFMSA Medical Students', url: 'https://ifmsa.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-amsa-events', organization: 'AMSA Asian Medical Students', url: 'https://www.amsainternational.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3, 4], region: 'Asia-Pacific', language: 'en', requires_auth: false },
  { id: 'yth-emsa-events', organization: 'EMSA European Medical Students', url: 'https://emsa-eu.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3, 4], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'yth-lmsa-events', organization: 'LMSA Latin American Medical Students', url: 'https://www.lmsa.net/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3, 4], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'yth-afmsa-events', organization: 'AFMSA African Medical Students', url: 'https://www.afmsa.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3, 4], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'yth-student-global-health', organization: 'Student Global Health Forum', url: 'https://www.sghi.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3, 4], region: 'Global', language: 'en', requires_auth: false },

  // ── Youth Peacebuilding ────────────────────────────────────────────────────
  { id: 'yth-pyd-events', organization: 'Peacebuilding Youth Network', url: 'https://www.youth-peacebuilding.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-unoy-events', organization: 'UNOY Peacebuilders', url: 'https://www.unoy.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-ypsa-events', organization: 'Youth Peace Support Africa', url: 'https://www.ypsa.org.bd/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16, 4], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'yth-peace-apps-events', organization: 'Peace Apps Youth', url: 'https://peaceapps.net/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-aypf-events', organization: 'African Youth Peace Forum', url: 'https://aypf.africa/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16, 4], region: 'Africa', language: 'en', requires_auth: false },

  // ── Youth Sports and Development ──────────────────────────────────────────
  { id: 'yth-oisf-events', organization: 'Olympic IOC Youth Forum', url: 'https://olympics.com/ioc/youth-athlete-forum', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-csit-events', organization: 'CSIT Sport for All', url: 'https://www.csit.tv/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-righttoplay', organization: 'Right to Play', url: 'https://www.righttoplay.com/en/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-streetfootball', organization: 'StreetFootballWorld', url: 'https://www.streetfootballworld.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 16], region: 'Global', language: 'en', requires_auth: false },

  // ── Digital Youth and Innovation ──────────────────────────────────────────
  { id: 'yth-y20-summit', organization: 'Y20 Youth Summit G20', url: 'https://y20.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 8], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-youthig-events', organization: 'Youth Internet Governance Forum', url: 'https://www.youthigf.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [9, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'yth-africacode', organization: 'Africa Code Week', url: 'https://africacodeweek.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 9], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'yth-gyti-events', organization: 'Global Youth Tech Initiative', url: 'https://www.unicef.org/innovation/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [9, 4], region: 'Global', language: 'en', requires_auth: false },

  // ── Regional Youth Bodies ──────────────────────────────────────────────────
  { id: 'yth-au-youth', organization: 'AU Youth Division', url: 'https://au.int/en/directorates/youth/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 8], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'yth-panyouth-events', organization: 'Pan-African Youth Union', url: 'https://payu.africa/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 17], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'yth-asean-youth', organization: 'ASEAN Youth Cooperation', url: 'https://asean.org/youth/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'yth-saarc-youth', organization: 'SAARC Youth Forum', url: 'https://www.saarc-sec.org/activities/technical-committees/youth/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 17], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'yth-lac-youth', organization: 'ECLAC Youth LAC', url: 'https://www.cepal.org/en/youth/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 8], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'yth-ecowas-youth', organization: 'ECOWAS Youth Council', url: 'https://www.ecowas.int/ecowas-sectors/youth/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4, 17], region: 'Africa-West', language: 'en', requires_auth: false },
];
