import type { ScraperSource } from './types';

export const SOURCES_EUROPE_EXPANDED: ScraperSource[] = [

  // ── European Union Institutions ────────────────────────────────────────────
  { id: 'eu-ep-events', organization: 'European Parliament', url: 'https://www.europarl.europa.eu/events/en', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [16, 17], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-council-events', organization: 'Council of the EU', url: 'https://www.consilium.europa.eu/en/meetings/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [16, 17], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-commission-events', organization: 'European Commission', url: 'https://ec.europa.eu/commission/events_en', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [17], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-eeas-events', organization: 'EEAS', url: 'https://www.eeas.europa.eu/eeas/events_en', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17, 16], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-ecb-events', organization: 'European Central Bank', url: 'https://www.ecb.europa.eu/pub/conferences/html/index.en.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8, 17], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-eba-events', organization: 'European Banking Authority', url: 'https://www.eba.europa.eu/calendar-events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-ema-events', organization: 'European Medicines Agency', url: 'https://www.ema.europa.eu/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-ecdc-events', organization: 'ECDC', url: 'https://www.ecdc.europa.eu/en/news-events/events-conference', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-jrc-events', organization: 'EU Joint Research Centre', url: 'https://joint-research-centre.ec.europa.eu/events_en', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [9, 13], region: 'Europe', language: 'en', requires_auth: false },

  // ── UK Policy and Research ─────────────────────────────────────────────────
  { id: 'eu-lse-events', organization: 'LSE Events', url: 'https://www.lse.ac.uk/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16, 4], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-odi-events', organization: 'ODI', url: 'https://odi.org/en/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [1, 17], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-chatham-events', organization: 'Chatham House', url: 'https://www.chathamhouse.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [16, 17], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-wellcome-events', organization: 'Wellcome Trust', url: 'https://wellcome.org/news/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 9], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-iom-ipu-events', organization: 'IPU Geneva', url: 'https://www.ipu.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-rsas-events', organization: 'Royal Society', url: 'https://royalsociety.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [9], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-iod-events', organization: 'Institute of Development Studies', url: 'https://www.ids.ac.uk/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 10], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-overseas-dev-inst', organization: 'British Council', url: 'https://www.britishcouncil.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 17], region: 'Europe', language: 'en', requires_auth: false },

  // ── Germany / DACH ─────────────────────────────────────────────────────────
  { id: 'eu-giz-events', organization: 'GIZ', url: 'https://www.giz.de/en/mediacenter/events.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17, 1], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-bmz-events', organization: 'BMZ Germany', url: 'https://www.bmz.de/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-kfw-events', organization: 'KfW Development Bank', url: 'https://www.kfw.de/About-KfW/News/Events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8, 13], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-dii-events', organization: 'DIE Development Institute', url: 'https://www.die-gdi.de/en/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-fnf-events', organization: 'Friedrich Naumann Foundation', url: 'https://www.freiheit.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-goethe-events', organization: 'Goethe-Institut', url: 'https://www.goethe.de/en/ver.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 17], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-dw-akademie-events', organization: 'DW Akademie', url: 'https://www.dw.com/en/dw-akademie/events/s-57900', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Europe', language: 'en', requires_auth: false },

  // ── France / Francophone ───────────────────────────────────────────────────
  { id: 'eu-afd-events', organization: 'AFD France', url: 'https://www.afd.fr/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 17], region: 'Europe', language: 'fr', requires_auth: false },
  { id: 'eu-ird-events', organization: 'IRD France', url: 'https://www.ird.fr/agenda', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [9, 17], region: 'Europe', language: 'fr', requires_auth: false },
  { id: 'eu-sciences-po', organization: 'Sciences Po', url: 'https://www.sciencespo.fr/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16, 4], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-ifri-events', organization: 'IFRI', url: 'https://www.ifri.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-oif-events', organization: 'Organisation Internationale de la Francophonie', url: 'https://www.francophonie.org/evenements', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 17], region: 'Europe', language: 'fr', requires_auth: false },
  { id: 'eu-cirad-events', organization: 'CIRAD', url: 'https://www.cirad.fr/en/news/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 15], region: 'Europe', language: 'fr', requires_auth: false },

  // ── Nordic Countries ───────────────────────────────────────────────────────
  { id: 'eu-nordic-events', organization: 'Nordic Council of Ministers', url: 'https://www.norden.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17, 16], region: 'Europe-Nordic', language: 'en', requires_auth: false },
  { id: 'eu-norad-events', organization: 'NORAD', url: 'https://www.norad.no/en/front/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Europe-Nordic', language: 'en', requires_auth: false },
  { id: 'eu-sida-events', organization: 'Sida Sweden', url: 'https://www.sida.se/en/about/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Europe-Nordic', language: 'en', requires_auth: false },
  { id: 'eu-danida-events', organization: 'DANIDA Denmark', url: 'https://www.udenrigsministeriet.dk/en/development-cooperation/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Europe-Nordic', language: 'en', requires_auth: false },
  { id: 'eu-finnfund-events', organization: 'Finnfund', url: 'https://www.finnfund.fi/en/news/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8, 17], region: 'Europe-Nordic', language: 'en', requires_auth: false },
  { id: 'eu-norfund-events', organization: 'Norfund', url: 'https://www.norfund.no/news/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8, 17], region: 'Europe-Nordic', language: 'en', requires_auth: false },
  { id: 'eu-cph-business', organization: 'Copenhagen Business School', url: 'https://www.cbs.dk/en/research/departments-and-centres/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8, 4], region: 'Europe-Nordic', language: 'en', requires_auth: false },
  { id: 'eu-kis-events', organization: 'Karolinska Institutet', url: 'https://ki.se/en/news/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Europe-Nordic', language: 'en', requires_auth: false },
  { id: 'eu-umb-events', organization: 'University of Oslo', url: 'https://www.uio.no/english/about/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 17], region: 'Europe-Nordic', language: 'en', requires_auth: false },

  // ── Netherlands / Benelux ──────────────────────────────────────────────────
  { id: 'eu-hague-events', organization: 'The Hague International', url: 'https://www.thehague.com/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16, 17], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-iiss-geneva', organization: 'IISS Geneva', url: 'https://www.iiss.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-iom-geneva', organization: 'IOM Geneva', url: 'https://www.iom.int/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [10], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-iss-events', organization: 'ISS The Hague', url: 'https://www.iss.nl/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 4], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-oxfam-nl', organization: 'Oxfam Novib', url: 'https://www.oxfamnovib.nl/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 10], region: 'Europe', language: 'nl', requires_auth: false },

  // ── Switzerland / Geneva International ────────────────────────────────────
  { id: 'eu-wto-geneva', organization: 'WTO Geneva', url: 'https://www.wto.org/english/news_e/news_e.htm?type=event', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [8, 17], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-ilo-geneva', organization: 'ILO Geneva', url: 'https://www.ilo.org/global/meetings-and-events/lang--en/index.htm', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [8], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-itu-events', organization: 'ITU', url: 'https://www.itu.int/net4/events/calendar/events.aspx', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [9], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-wipo-events', organization: 'WIPO', url: 'https://www.wipo.int/meetings/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [9, 8], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-cern-events', organization: 'CERN', url: 'https://home.cern/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [9], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-graduate-institute', organization: 'Geneva Graduate Institute', url: 'https://www.graduateinstitute.ch/academic-departments/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16, 4], region: 'Europe', language: 'en', requires_auth: false },

  // ── Central and Eastern Europe ─────────────────────────────────────────────
  { id: 'eu-warsaw-security-forum', organization: 'Warsaw Security Forum', url: 'https://warsawsecurityforum.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Europe-East', language: 'en', requires_auth: false },
  { id: 'eu-globsec-events', organization: 'GLOBSEC', url: 'https://www.globsec.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Europe-East', language: 'en', requires_auth: false },
  { id: 'eu-cei-events', organization: 'Central European Initiative', url: 'https://www.cei.int/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17, 8], region: 'Europe-East', language: 'en', requires_auth: false },
  { id: 'eu-ceu-events', organization: 'Central European University', url: 'https://www.ceu.edu/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4, 16], region: 'Europe-East', language: 'en', requires_auth: false },
  { id: 'eu-visegrad-events', organization: 'Visegrad Group', url: 'https://www.visegradgroup.eu/calendar', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17, 16], region: 'Europe-East', language: 'en', requires_auth: false },
  { id: 'eu-eap-events', organization: 'Eastern Partnership', url: 'https://www.eap-csf.eu/news/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17, 16], region: 'Europe-East', language: 'en', requires_auth: false },

  // ── South Europe / Mediterranean ──────────────────────────────────────────
  { id: 'eu-upm-events', organization: 'Union for the Mediterranean', url: 'https://ufmsecretariat.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Europe-South', language: 'en', requires_auth: false },
  { id: 'eu-med-forum', organization: 'Mediterranean Forum', url: 'https://www.dialoguemediterranee.com/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [17, 16], region: 'Europe-South', language: 'en', requires_auth: false },
  { id: 'eu-iemed-events', organization: 'IEMed', url: 'https://www.iemed.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Europe-South', language: 'en', requires_auth: false },
  { id: 'eu-fieri-events', organization: 'FIERI', url: 'https://www.fieri.it/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10], region: 'Europe-South', language: 'it', requires_auth: false },
  { id: 'eu-cidob-events', organization: 'CIDOB', url: 'https://www.cidob.org/en/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17, 16], region: 'Europe-South', language: 'en', requires_auth: false },
  { id: 'eu-iai-events', organization: 'IAI Italy', url: 'https://www.iai.it/en/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16, 17], region: 'Europe-South', language: 'en', requires_auth: false },
  { id: 'eu-eliamep-events', organization: 'ELIAMEP Greece', url: 'https://www.eliamep.gr/en/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Europe-South', language: 'en', requires_auth: false },

  // ── European NGOs and Civil Society ───────────────────────────────────────
  { id: 'eu-concord-events', organization: 'CONCORD Europe', url: 'https://concordeurope.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17, 1], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-eurodad-events', organization: 'Eurodad', url: 'https://www.eurodad.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-solidar-events', organization: 'SOLIDAR', url: 'https://www.solidar.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10, 8], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-efc-events', organization: 'European Foundation Centre', url: 'https://www.efc.be/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-demo-europe', organization: 'Democracy Reporting International', url: 'https://democracyreporting.international/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-transparency-eu', organization: 'Transparency International EU', url: 'https://www.transparencyinternational.eu/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-epha-events', organization: 'European Public Health Alliance', url: 'https://epha.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-friends-earth', organization: 'Friends of the Earth Europe', url: 'https://friendsoftheearth.eu/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [13, 15], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-wwf-europe', organization: 'WWF Europe', url: 'https://www.wwf.eu/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [15, 13], region: 'Europe', language: 'en', requires_auth: false },

  // ── European Security and Defence ──────────────────────────────────────────
  { id: 'eu-nato-events', organization: 'NATO', url: 'https://www.nato.int/cps/en/natohq/events.htm', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [16], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-iss-eu-events', organization: 'EU Institute for Security Studies', url: 'https://www.iss.europa.eu/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-ecfr-events', organization: 'ECFR', url: 'https://ecfr.eu/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16, 17], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-friends-europe', organization: 'Friends of Europe', url: 'https://www.friendsofeurope.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [17, 16], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-sda-events', organization: 'Security and Defence Agenda', url: 'https://securitydefenceagenda.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Europe', language: 'en', requires_auth: false },

  // ── Science and Innovation ─────────────────────────────────────────────────
  { id: 'eu-esf-events', organization: 'European Science Foundation', url: 'https://www.esf.org/events.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [9, 4], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-horizon-events', organization: 'Horizon Europe', url: 'https://research-and-innovation.ec.europa.eu/events_en', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [9, 17], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-embl-events', organization: 'EMBL', url: 'https://www.embl.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [9, 3], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-esa-events', organization: 'European Space Agency', url: 'https://www.esa.int/About_Us/Events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [9], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-tu-delft-events', organization: 'TU Delft', url: 'https://www.tudelft.nl/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [9, 4], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-imperial-events', organization: 'Imperial College London', url: 'https://www.imperial.ac.uk/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [9, 3], region: 'Europe', language: 'en', requires_auth: false },

  // ── Climate and Environment – European ────────────────────────────────────
  { id: 'eu-eea-events', organization: 'European Environment Agency', url: 'https://www.eea.europa.eu/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [13, 15], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-ener-events', organization: 'EU Energy Agency', url: 'https://energy.ec.europa.eu/events_en', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [7, 13], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-ecm-climate-eu', organization: 'European Climate Foundation', url: 'https://europeanclimate.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [13], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-e3g-events', organization: 'E3G', url: 'https://www.e3g.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [13], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'eu-sandbag-events', organization: 'Sandbag Climate', url: 'https://sandbag.be/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [13], region: 'Europe', language: 'en', requires_auth: false },
];
