import type { ScraperSource } from './types';

export const SOURCES_FOOD_AGRICULTURE: ScraperSource[] = [

  // ── FAO ─────────────────────────────────────────────────────────────────────
  { id: 'agr-fao-events', organization: 'FAO', url: 'https://www.fao.org/events/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [2, 15], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-fao-council', organization: 'FAO Council', url: 'https://www.fao.org/fao-who-codexalimentarius/meetings/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-fao-coag', organization: 'FAO COAG', url: 'https://www.fao.org/agriculture/meetings/coag/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-fao-cropsites', organization: 'FAO Crop Prospects', url: 'https://www.fao.org/giews/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-fao-africa', organization: 'FAO Africa', url: 'https://www.fao.org/africa/news/detail-news/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'agr-fao-asia', organization: 'FAO Asia-Pacific', url: 'https://www.fao.org/asiapacific/news/detail-news/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Asia-Pacific', language: 'en', requires_auth: false },
  { id: 'agr-fao-latin', organization: 'FAO Latin America', url: 'https://www.fao.org/americas/noticias/ver/es/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'agr-fao-near-east', organization: 'FAO Near East', url: 'https://www.fao.org/neareast/news/detail-news/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Middle-East', language: 'en', requires_auth: false },
  { id: 'agr-fao-codex', organization: 'Codex Alimentarius', url: 'https://www.fao.org/fao-who-codexalimentarius/meetings/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },

  // ── IFAD and WFP ────────────────────────────────────────────────────────────
  { id: 'agr-ifad-events', organization: 'IFAD', url: 'https://www.ifad.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [2, 1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-ifad-governing', organization: 'IFAD Governing Council', url: 'https://www.ifad.org/en/governing-council', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-wfp-events', organization: 'WFP', url: 'https://www.wfp.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-wfp-africa', organization: 'WFP Africa', url: 'https://www.wfp.org/regions/africa', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Africa', language: 'en', requires_auth: false },

  // ── CGIAR ───────────────────────────────────────────────────────────────────
  { id: 'agr-cgiar-events', organization: 'CGIAR', url: 'https://www.cgiar.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 15], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-irri-events', organization: 'IRRI', url: 'https://www.irri.org/news-and-events/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'agr-cimmyt-events', organization: 'CIMMYT', url: 'https://www.cimmyt.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-cip-events', organization: 'CIP', url: 'https://cipotato.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Americas-Latin', language: 'en', requires_auth: false },
  { id: 'agr-iita-events', organization: 'IITA', url: 'https://www.iita.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'agr-icarda-events', organization: 'ICARDA', url: 'https://www.icarda.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Middle-East', language: 'en', requires_auth: false },
  { id: 'agr-worldagroforestry', organization: 'World Agroforestry', url: 'https://www.worldagroforestry.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 15], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-iwmi-events', organization: 'IWMI', url: 'https://www.iwmi.cgiar.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 6], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-ciat-events', organization: 'Alliance of Bioversity-CIAT', url: 'https://alliancebioversityciat.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 15], region: 'Americas-Latin', language: 'en', requires_auth: false },
  { id: 'agr-icraf-events', organization: 'ICRAF', url: 'https://www.worldagroforestry.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 15], region: 'Africa', language: 'en', requires_auth: false },

  // ── Food Security ──────────────────────────────────────────────────────────
  { id: 'agr-cfs-events', organization: 'UN Committee on World Food Security', url: 'https://www.fao.org/cfs/sessions/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-fsin-events', organization: 'Food Security Information Network', url: 'https://www.fsinplatform.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-ipc-food', organization: 'IPC Platform', url: 'https://www.ipcinfo.org/ipcinfo-website/events/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-sofa-report', organization: 'State of Food Security', url: 'https://www.fao.org/publications/sofi/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-gsf-events', organization: 'Global Soil Forum', url: 'https://www.globalsoilpartnership.org/en/pillars/soil-information/global-soil-week/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 15], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-grain-events', organization: 'GRAIN', url: 'https://grain.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-agrifood-economics', organization: 'AgriFood Economics', url: 'https://agrifood.net/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 8], region: 'Global', language: 'en', requires_auth: false },

  // ── Sustainable Agriculture ────────────────────────────────────────────────
  { id: 'agr-ifoam-events', organization: 'IFOAM Organics', url: 'https://www.ifoam.bio/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 12], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-agroecology', organization: 'Agroecology Fund', url: 'https://www.agroecologyfund.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 15], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-conservation-agr', organization: 'Conservation Agriculture', url: 'https://www.fao.org/conservation-agriculture/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 15], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-groundswell-intl', organization: 'Groundswell International', url: 'https://www.groundswellinternational.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-acdi-voca', organization: 'ACDI/VOCA', url: 'https://www.acdivoca.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-fwr-events', organization: 'Future Food Institute', url: 'https://www.futurefoodinstitute.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 12], region: 'Global', language: 'en', requires_auth: false },

  // ── Agriculture Conferences ────────────────────────────────────────────────
  { id: 'agr-gfar-events', organization: 'GFAR', url: 'https://www.gfar.net/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-agrisem-events', organization: 'AGRISEM', url: 'https://www.agrisem.eu/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'agr-world-agri-tech', organization: 'World Agri-Tech Summit', url: 'https://worldagritechsummit.com/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 9], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-euragri-events', organization: 'European Agricultural Economics', url: 'https://www.eaae.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'agr-iaae-events', organization: 'IAAE', url: 'https://www.iaae-agecon.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-nyas-food', organization: 'NYAS Food Sustainability', url: 'https://www.nyas.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'agr-terra-food', organization: 'Terra Madre Salone del Gusto', url: 'https://www.slowfood.com/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 12], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'agr-ifama-events', organization: 'IFAMA', url: 'https://ifama.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 8], region: 'Global', language: 'en', requires_auth: false },

  // ── Land and Biodiversity ──────────────────────────────────────────────────
  { id: 'agr-unccd-events', organization: 'UNCCD', url: 'https://www.unccd.int/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [15, 2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-cbd-sbstta', organization: 'CBD SBSTTA', url: 'https://www.cbd.int/meetings/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [15, 2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-ipbes-events', organization: 'IPBES', url: 'https://ipbes.net/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [15, 2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-iucn-food', organization: 'IUCN Food & Agriculture', url: 'https://www.iucn.org/events?theme=food-agriculture', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [15, 2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-land-coalition', organization: 'International Land Coalition', url: 'https://www.landcoalition.org/en/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-iiasa-events', organization: 'IIASA Food', url: 'https://iiasa.ac.at/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 15], region: 'Europe', language: 'en', requires_auth: false },

  // ── Regional Agriculture ────────────────────────────────────────────────────
  { id: 'agr-caadp-events', organization: 'CAADP', url: 'https://www.nepad.org/caadp/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'agr-agra-events', organization: 'AGRA', url: 'https://agra.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'agr-fanrpan-events', organization: 'FANRPAN', url: 'https://www.fanrpan.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Africa-Southern', language: 'en', requires_auth: false },
  { id: 'agr-aatf-events', organization: 'AATF Africa', url: 'https://www.aatf-africa.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'agr-asareca-events', organization: 'ASARECA', url: 'https://www.asareca.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'agr-coraf-events', organization: 'CORAF', url: 'https://www.coraf.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Africa-West', language: 'en', requires_auth: false },
  { id: 'agr-apec-food', organization: 'APEC Food Security', url: 'https://www.apec.org/Groups/SOM-Steering-Committee-on-Economic-and-Technical-Cooperation/Working-Groups/Agricultural-Technical-Cooperation', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Asia-Pacific', language: 'en', requires_auth: false },
  { id: 'agr-saarc-agri', organization: 'SAARC Agriculture', url: 'https://www.saarc-sec.org/Agriculture/3/5', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'agr-procasur-events', organization: 'PROCASUR', url: 'https://procasur.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Americas-Latin', language: 'es', requires_auth: false },

  // ── Nutrition ──────────────────────────────────────────────────────────────
  { id: 'agr-sun-events', organization: 'SUN Movement', url: 'https://scalingupnutrition.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-nutrition-intl', organization: 'Nutrition International', url: 'https://www.nutritionintl.org/news-events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-who-nutrition', organization: 'WHO Nutrition', url: 'https://www.who.int/activities/nutrition', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-icn3-events', organization: 'International Conference on Nutrition', url: 'https://www.fao.org/nutrition/policies-programmes/icn2/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-iuns-events', organization: 'International Union of Nutritional Sciences', url: 'https://www.iuns.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-gain-events', organization: 'GAIN', url: 'https://www.gainhealth.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 3], region: 'Global', language: 'en', requires_auth: false },

  // ── Fisheries and Aquaculture ───────────────────────────────────────────────
  { id: 'agr-fao-cofi', organization: 'FAO COFI', url: 'https://www.fao.org/fishery/en/body/cofi', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [14, 2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-worldfish-events', organization: 'WorldFish', url: 'https://www.worldfishcenter.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [14, 2], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'agr-eaa-events', organization: 'European Aquaculture Society', url: 'https://www.was.org/meetings/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [14, 2], region: 'Global', language: 'en', requires_auth: false },

  // ── Forestry ───────────────────────────────────────────────────────────────
  { id: 'agr-unff-events', organization: 'UN Forum on Forests', url: 'https://www.un.org/esa/forests/events/index.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [15, 13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-iufro-events', organization: 'IUFRO', url: 'https://www.iufro.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [15], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-tropenbos-events', organization: 'Tropenbos International', url: 'https://www.tropenbos.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [15], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-cifor-events', organization: 'CIFOR', url: 'https://www.cifor.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [15, 13], region: 'Asia-Southeast', language: 'en', requires_auth: false },

  // ── National Agriculture Ministries – Africa ──────────────────────────────
  { id: 'agr-ke-agri', organization: 'Kenya State Department of Agriculture', url: 'https://kilimo.go.ke/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'agr-tz-agri', organization: 'Tanzania Ministry of Agriculture', url: 'https://www.mkulima.go.tz/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Africa-East', language: 'sw', requires_auth: false },
  { id: 'agr-ug-agri', organization: 'Uganda Ministry of Agriculture', url: 'https://www.maaif.go.ug/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'agr-et-agri', organization: 'Ethiopia Ministry of Agriculture', url: 'https://www.moa.gov.et/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'agr-gh-agri', organization: 'Ghana Ministry of Food and Agriculture', url: 'https://mofa.gov.gh/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Africa-West', language: 'en', requires_auth: false },
  { id: 'agr-ng-agri', organization: 'Nigeria Federal Ministry of Agriculture', url: 'https://fmard.gov.ng/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Africa-West', language: 'en', requires_auth: false },
  { id: 'agr-sn-agri', organization: 'Senegal Ministère de l Agriculture', url: 'https://www.agriculture.gouv.sn/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Africa-West', language: 'fr', requires_auth: false },
  { id: 'agr-rw-agri', organization: 'Rwanda Ministry of Agriculture', url: 'https://www.minagri.gov.rw/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'agr-za-agri', organization: 'South Africa Department of Agriculture', url: 'https://www.dalrrd.gov.za/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Africa-Southern', language: 'en', requires_auth: false },
  { id: 'agr-mz-agri', organization: 'Mozambique Ministry of Agriculture', url: 'https://www.masa.gov.mz/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Africa-Southern', language: 'pt', requires_auth: false },
  { id: 'agr-ma-agri', organization: 'Morocco Ministry of Agriculture', url: 'https://www.agriculture.gov.ma/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Africa-North', language: 'ar', requires_auth: false },
  { id: 'agr-eg-agri', organization: 'Egypt Ministry of Agriculture', url: 'https://www.agr.gov.eg/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Africa-North', language: 'ar', requires_auth: false },
  { id: 'agr-zm-agri', organization: 'Zambia Ministry of Agriculture', url: 'https://www.moa.gov.zm/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Africa-Southern', language: 'en', requires_auth: false },
  { id: 'agr-ml-agri', organization: 'Mali Ministère de l Agriculture', url: 'https://www.mali.gouv.ml/agriculture/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Africa-West', language: 'fr', requires_auth: false },

  // ── National Agriculture Ministries – Asia ───────────────────────────────
  { id: 'agr-in-agri', organization: 'India Ministry of Agriculture', url: 'https://agricoop.nic.in/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'agr-bd-agri', organization: 'Bangladesh Ministry of Agriculture', url: 'https://www.moa.gov.bd/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'agr-pk-agri', organization: 'Pakistan Ministry of National Food Security', url: 'https://www.mnfsr.gov.pk/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'agr-id-agri', organization: 'Indonesia Ministry of Agriculture', url: 'https://www.pertanian.go.id/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Asia-Southeast', language: 'id', requires_auth: false },
  { id: 'agr-ph-agri', organization: 'Philippines Department of Agriculture', url: 'https://www.da.gov.ph/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'agr-th-agri', organization: 'Thailand Ministry of Agriculture', url: 'https://www.moac.go.th/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Asia-Southeast', language: 'th', requires_auth: false },
  { id: 'agr-vn-agri', organization: 'Vietnam Ministry of Agriculture', url: 'https://www.mard.gov.vn/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Asia-Southeast', language: 'vi', requires_auth: false },
  { id: 'agr-np-agri', organization: 'Nepal Ministry of Agriculture', url: 'https://www.moald.gov.np/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'agr-kh-agri', organization: 'Cambodia Ministry of Agriculture', url: 'https://www.maff.gov.kh/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'agr-mm-agri', organization: 'Myanmar Ministry of Agriculture', url: 'https://www.moali.gov.mm/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Asia-Southeast', language: 'en', requires_auth: false },

  // ── Regional Food Security Bodies ─────────────────────────────────────────
  { id: 'agr-igad-food', organization: 'IGAD Food Security', url: 'https://igad.int/divisions/agricultural-and-environment/food-security/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'agr-sadc-food', organization: 'SADC Food Agriculture', url: 'https://www.sadc.int/themes/agriculture/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Africa-Southern', language: 'en', requires_auth: false },
  { id: 'agr-ecowas-agri', organization: 'ECOWAS Agriculture', url: 'https://www.ecowas.int/ecowas-sectors/agriculture/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Africa-West', language: 'en', requires_auth: false },
  { id: 'agr-au-caadp', organization: 'AU CAADP', url: 'https://au.int/en/ti/caadp/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 17], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'agr-asean-food', organization: 'ASEAN Food Security', url: 'https://asean.org/asean-economic-community/sectoral-bodies-under-the-purview-of-aem/food-agriculture-forestry/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'agr-saarc-food', organization: 'SAARC Agriculture', url: 'https://www.saarc-sec.org/activities/technical-committees/agriculture/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'agr-oecs-food', organization: 'OECS Agriculture', url: 'https://www.oecs.org/our-work/knowledge/agriculture', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Americas-Caribbean', language: 'en', requires_auth: false },
  { id: 'agr-caricom-food', organization: 'CARICOM Food Security', url: 'https://caricom.org/sectors/agriculture/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Americas-Caribbean', language: 'en', requires_auth: false },
  { id: 'agr-mercosur-agri', organization: 'MERCOSUR Agriculture', url: 'https://www.mercosur.int/en/sectors-food-and-agriculture/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Americas-Latin', language: 'es', requires_auth: false },
  { id: 'agr-celac-food', organization: 'CELAC Food Security', url: 'https://www.cepal.org/en/cepal-celac-initiatives', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Americas-Latin', language: 'es', requires_auth: false },

  // ── Global Agriculture Research ─────────────────────────────────────────
  { id: 'agr-cgiar-events', organization: 'CGIAR', url: 'https://www.cgiar.org/news-events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-cimmyt-events', organization: 'CIMMYT', url: 'https://www.cimmyt.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-irri-events', organization: 'IRRI', url: 'https://www.irri.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'agr-ilri-events', organization: 'ILRI', url: 'https://www.ilri.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 15], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'agr-icrisat-events', organization: 'ICRISAT', url: 'https://www.icrisat.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 13], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'agr-cip-events', organization: 'CIP Potato Center', url: 'https://cipotato.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Americas-Latin', language: 'en', requires_auth: false },
  { id: 'agr-iita-events', organization: 'IITA', url: 'https://www.iita.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2], region: 'Africa-West', language: 'en', requires_auth: false },
  { id: 'agr-bioversity-events', organization: 'Bioversity International', url: 'https://www.bioversityinternational.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 15], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-ciat-events', organization: 'CIAT Colombia', url: 'https://alliancebioversityciat.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 13], region: 'Americas-Latin', language: 'en', requires_auth: false },
  { id: 'agr-iwmi-events', organization: 'IWMI Water Management', url: 'https://www.iwmi.cgiar.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 6], region: 'Global', language: 'en', requires_auth: false },

  // ── Livestock and Animal Health ──────────────────────────────────────────
  { id: 'agr-oie-events', organization: 'WOAH Animal Health', url: 'https://www.woah.org/en/what-we-offer/conferences-meetings/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-garc-events', organization: 'Global Alliance for Rabies Control', url: 'https://rabiesalliance.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-asas-events', organization: 'American Society of Animal Science', url: 'https://www.asas.org/meetings/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Americas-North', language: 'en', requires_auth: false },
  { id: 'agr-eaap-events', organization: 'EAAP Animal Production', url: 'https://www.eaap.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'agr-wcvp-events', organization: 'World Congress Veterinary', url: 'https://www.wavma.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-pan-livestock', organization: 'Pan African Livestock', url: 'https://www.au-ibar.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Africa', language: 'en', requires_auth: false },

  // ── Soil Health and Land Use ─────────────────────────────────────────────
  { id: 'agr-gspf-events', organization: 'Global Soil Partnership FAO', url: 'https://www.fao.org/global-soil-partnership/events/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 15], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-isss-events', organization: 'International Soil Science Society', url: 'https://www.iuss.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 15], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-gldc-events', organization: 'Global Land Data Commons', url: 'https://www.globallandtoolsnetwork.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 15], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-unccd-events', organization: 'UNCCD Land', url: 'https://www.unccd.int/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [15, 2], region: 'Global', language: 'en', requires_auth: false },

  // ── Smallholder and Agroecology ──────────────────────────────────────────
  { id: 'agr-agroecology-events', organization: 'Agroecology Fund', url: 'https://agroecologyfund.org/news/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-wfto-events', organization: 'WFTO Fair Trade', url: 'https://wfto.com/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8, 2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-via-campesina', organization: 'La Via Campesina', url: 'https://viacampesina.org/en/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-ifad-smallholder', organization: 'IFAD Smallholder', url: 'https://www.ifad.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-fao-agroeco', organization: 'FAO Agroecology', url: 'https://www.fao.org/agroecology/events/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-gfar-events', organization: 'GFAR Agricultural Research', url: 'https://www.gfar.net/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-agrf-events', organization: 'Africa Food Systems Forum', url: 'https://agrf.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 8], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'agr-africasoilhealth', organization: 'Africa Soil Health Consortium', url: 'https://africasoilhealth.cabi.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 15], region: 'Africa', language: 'en', requires_auth: false },

  // ── Food Policy and Conferences ──────────────────────────────────────────
  { id: 'agr-worldfoodforum', organization: 'World Food Forum', url: 'https://www.worldfoodforum.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-unfss-events', organization: 'UN Food Systems Summit', url: 'https://www.un.org/en/food-systems-summit', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-iftc-events', organization: 'IFPRI Events', url: 'https://www.ifpri.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-glopan-events', organization: 'Global Panel Food and Nutrition', url: 'https://www.glopan.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-nutrition4growth', organization: 'Nutrition for Growth', url: 'https://nutritionforgrowth.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-fao-n4g', organization: 'FAO Nutrition', url: 'https://www.fao.org/nutrition/events/en/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-protein2food', organization: 'Protein for the Future', url: 'https://www.hivos.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-seeds-events', organization: 'Seed Systems Events', url: 'https://www.bioversityinternational.org/theme/seeds/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 15], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-food-planet-prize', organization: 'Food Planet Prize', url: 'https://foodplanetprize.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-ipbes-events', organization: 'IPBES Biodiversity', url: 'https://www.ipbes.net/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [15, 2], region: 'Global', language: 'en', requires_auth: false },

  // ── Market Access and Value Chains ───────────────────────────────────────
  { id: 'agr-agritrade-events', organization: 'Agri-Trade Events ITC', url: 'https://www.intracen.org/news-and-events/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [8, 2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-imtfe-events', organization: 'International Money Transfer Forum Agriculture', url: 'https://www.ifpri.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [8, 2], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-technoserve-events', organization: 'TechnoServe', url: 'https://www.technoserve.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 8], region: 'Global', language: 'en', requires_auth: false },
  { id: 'agr-meda-events', organization: 'MEDA Agricultural Markets', url: 'https://www.meda.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [2, 8], region: 'Global', language: 'en', requires_auth: false },
];
