import type { ScraperSource } from './types';

export const SOURCES_HUMANITARIAN: ScraperSource[] = [

  // ── OCHA and UN Coordination ────────────────────────────────────────────────
  { id: 'hum-ocha-events', organization: 'OCHA', url: 'https://www.unocha.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [1, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-ocha-africa', organization: 'OCHA Africa', url: 'https://www.unocha.org/africa', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [1], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'hum-ocha-asia', organization: 'OCHA Asia-Pacific', url: 'https://www.unocha.org/asia-pacific', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1], region: 'Asia-Pacific', language: 'en', requires_auth: false },
  { id: 'hum-ocha-mena', organization: 'OCHA MENA', url: 'https://www.unocha.org/middle-east-north-africa', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [1], region: 'Middle-East', language: 'en', requires_auth: false },
  { id: 'hum-ocha-reliefweb', organization: 'ReliefWeb Events', url: 'https://reliefweb.int/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [1, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-iasc-events', organization: 'IASC', url: 'https://interagencystandingcommittee.org/about/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1], region: 'Global', language: 'en', requires_auth: false },

  // ── UNHCR ───────────────────────────────────────────────────────────────────
  { id: 'hum-unhcr-events', organization: 'UNHCR', url: 'https://www.unhcr.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [1, 10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-unhcr-africa', organization: 'UNHCR Africa', url: 'https://www.unhcr.org/africa', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'hum-unhcr-asia', organization: 'UNHCR Asia', url: 'https://www.unhcr.org/asia', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1], region: 'Asia-Pacific', language: 'en', requires_auth: false },
  { id: 'hum-unhcr-mena', organization: 'UNHCR MENA', url: 'https://www.unhcr.org/middle-east-north-africa', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [1], region: 'Middle-East', language: 'en', requires_auth: false },
  { id: 'hum-unhcr-americas', organization: 'UNHCR Americas', url: 'https://www.unhcr.org/americas', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1], region: 'Americas', language: 'en', requires_auth: false },
  { id: 'hum-globalcompact-refugees', organization: 'Global Compact on Refugees', url: 'https://www.unhcr.org/global-compact-on-refugees.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1, 10], region: 'Global', language: 'en', requires_auth: false },

  // ── ICRC ────────────────────────────────────────────────────────────────────
  { id: 'hum-icrc-events', organization: 'ICRC', url: 'https://www.icrc.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-icrc-africa', organization: 'ICRC Africa', url: 'https://www.icrc.org/en/where-we-work/africa', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'hum-icrc-asia', organization: 'ICRC Asia-Pacific', url: 'https://www.icrc.org/en/where-we-work/asia-pacific', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Asia-Pacific', language: 'en', requires_auth: false },
  { id: 'hum-ifrc-events', organization: 'IFRC', url: 'https://www.ifrc.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 1], region: 'Global', language: 'en', requires_auth: false },

  // ── MSF ─────────────────────────────────────────────────────────────────────
  { id: 'hum-msf-events', organization: 'MSF', url: 'https://www.msf.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-msf-access', organization: 'MSF Access Campaign', url: 'https://msfaccess.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Global', language: 'en', requires_auth: false },

  // ── NGO Cluster / INGOs ────────────────────────────────────────────────────
  { id: 'hum-save-children-events', organization: 'Save the Children', url: 'https://www.savethechildren.net/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-oxfam-events', organization: 'Oxfam', url: 'https://www.oxfam.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-care-events', organization: 'CARE', url: 'https://www.care.org/news-and-stories/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 5], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-mercy-corps', organization: 'Mercy Corps', url: 'https://www.mercycorps.org/blog/news', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-nrc-events', organization: 'Norwegian Refugee Council', url: 'https://www.nrc.no/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-irc-events', organization: 'International Rescue Committee', url: 'https://www.rescue.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-worldvision-events', organization: 'World Vision', url: 'https://www.wvi.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-caritas-events', organization: 'Caritas Internationalis', url: 'https://www.caritas.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-islamic-relief', organization: 'Islamic Relief', url: 'https://www.islamic-relief.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-church-world', organization: 'Church World Service', url: 'https://cwsglobal.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-brac-events', organization: 'BRAC', url: 'https://www.brac.net/news-and-events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 4], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'hum-acf-events', organization: 'Action Against Hunger', url: 'https://www.actionagainsthunger.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-intersos-events', organization: 'INTERSOS', url: 'https://www.intersos.org/en/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1, 3], region: 'Global', language: 'en', requires_auth: false },

  // ── Disaster Risk Reduction ────────────────────────────────────────────────
  { id: 'hum-undrr-events', organization: 'UNDRR', url: 'https://www.undrr.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [11, 13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-wcdrr-events', organization: 'WCDRR', url: 'https://www.undrr.org/news/wcdrr', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-gpdrr-events', organization: 'GPDRR', url: 'https://www.undrr.org/gpdrr', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-sendai-events', organization: 'Sendai Framework', url: 'https://www.undrr.org/implementing-sendai-framework/what-sendai-framework', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11, 13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-predrr-events', organization: 'PreventionWeb', url: 'https://www.preventionweb.net/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [11, 13], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-cdac-events', organization: 'CDAC Network', url: 'https://www.cdacnetwork.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [11], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-gfdrr-events', organization: 'GFDRR', url: 'https://www.gfdrr.org/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [11, 13], region: 'Global', language: 'en', requires_auth: false },

  // ── Humanitarian Funding ────────────────────────────────────────────────────
  { id: 'hum-cerf-events', organization: 'CERF', url: 'https://cerf.un.org/news-and-resources/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-chf-events', organization: 'Common Humanitarian Funds', url: 'https://www.unocha.org/united-nations-humanitarian-fund', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-dgo-events', organization: 'Development and Humanitarian Alliance', url: 'https://devinit.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1], region: 'Global', language: 'en', requires_auth: false },

  // ── Humanitarian Policy ────────────────────────────────────────────────────
  { id: 'hum-alnap-events', organization: 'ALNAP', url: 'https://www.alnap.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-hpg-events', organization: 'Humanitarian Policy Group', url: 'https://odi.org/en/about/our-work/hpg/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-gha-events', organization: 'Global Humanitarian Assistance', url: 'https://devinit.org/topics/humanitarian-assistance/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-sphere-events', organization: 'Sphere Standards', url: 'https://spherestandards.org/news/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-start-network', organization: 'Start Network', url: 'https://startnetwork.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-elrha-events', organization: 'Elrha', url: 'https://www.elrha.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3, 1], region: 'Global', language: 'en', requires_auth: false },

  // ── Health Emergencies ─────────────────────────────────────────────────────
  { id: 'hum-who-emergencies', organization: 'WHO Health Emergencies', url: 'https://www.who.int/teams/health-emergency-preparedness-and-response/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-goarn-events', organization: 'GOARN', url: 'https://extranet.who.int/goarn/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-hse-forum', organization: 'Humanitarian Health Forum', url: 'https://www.healthcluster.who.int/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-paho-emergency', organization: 'PAHO Emergency', url: 'https://www.paho.org/en/topics/emergencies-disasters', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Americas-Latin', language: 'en', requires_auth: false },

  // ── Water and Sanitation in Emergencies ────────────────────────────────────
  { id: 'hum-wash-cluster', organization: 'WASH Cluster', url: 'https://www.washcluster.net/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [6], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-unicef-wash', organization: 'UNICEF WASH', url: 'https://www.unicef.org/wash', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [6, 3], region: 'Global', language: 'en', requires_auth: false },

  // ── Accountability and Protection ──────────────────────────────────────────
  { id: 'hum-icva-events', organization: 'ICVA', url: 'https://www.icvanetwork.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16, 1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-protection-cluster', organization: 'Global Protection Cluster', url: 'https://www.globalprotectioncluster.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-sgbv-aor', organization: 'GBV AoR', url: 'https://gbvaor.net/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [5, 16], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-cpwg-events', organization: 'Child Protection Working Group', url: 'https://www.cpwg.net/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [16, 1], region: 'Global', language: 'en', requires_auth: false },

  // ── Displacement and Migration ─────────────────────────────────────────────
  { id: 'hum-iom-events', organization: 'IOM', url: 'https://www.iom.int/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [10, 1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-mixed-migration', organization: 'Mixed Migration Centre', url: 'https://mixedmigration.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-idmc-events', organization: 'IDMC', url: 'https://www.internal-displacement.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 11], region: 'Global', language: 'en', requires_auth: false },

  // ── National Disaster Management Agencies – Africa ────────────────────────
  { id: 'hum-ke-ndoc', organization: 'Kenya National Disaster Operations Centre', url: 'https://www.ndoc.go.ke/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11, 13], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'hum-tz-domd', organization: 'Tanzania Disaster Management Department', url: 'https://www.domd.go.tz/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11], region: 'Africa-East', language: 'sw', requires_auth: false },
  { id: 'hum-ug-opa', organization: 'Uganda Office of the Prime Minister Disaster', url: 'https://www.opm.go.ug/relief-disaster-preparedness/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'hum-et-dppb', organization: 'Ethiopia Disaster Prevention', url: 'https://www.dppb.gov.et/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11, 13], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'hum-gh-nadmo', organization: 'Ghana NADMO', url: 'https://www.nadmo.gov.gh/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11], region: 'Africa-West', language: 'en', requires_auth: false },
  { id: 'hum-ng-nema', organization: 'Nigeria NEMA', url: 'https://www.nema.gov.ng/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11], region: 'Africa-West', language: 'en', requires_auth: false },
  { id: 'hum-sn-dgpc', organization: 'Senegal Direction Générale Protection Civile', url: 'https://www.interieur.gouv.sn/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11], region: 'Africa-West', language: 'fr', requires_auth: false },
  { id: 'hum-mz-ingd', organization: 'Mozambique INGD', url: 'https://www.ingd.gov.mz/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11, 13], region: 'Africa-Southern', language: 'pt', requires_auth: false },
  { id: 'hum-za-ndmc', organization: 'South Africa NDMC', url: 'https://www.ndmc.gov.za/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11], region: 'Africa-Southern', language: 'en', requires_auth: false },
  { id: 'hum-ma-dpc', organization: 'Morocco Direction Protection Civile', url: 'https://www.protection-civile.ma/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11], region: 'Africa-North', language: 'ar', requires_auth: false },

  // ── National Disaster Management Agencies – Asia ──────────────────────────
  { id: 'hum-in-ndma', organization: 'India NDMA', url: 'https://ndma.gov.in/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11, 13], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'hum-bd-ddm', organization: 'Bangladesh DDM', url: 'https://www.ddm.gov.bd/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11, 13], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'hum-pk-ndma', organization: 'Pakistan NDMA', url: 'https://www.ndma.gov.pk/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'hum-np-nasc', organization: 'Nepal NASC', url: 'https://www.ndrrma.gov.np/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'hum-id-bnpb', organization: 'Indonesia BNPB', url: 'https://www.bnpb.go.id/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11, 13], region: 'Asia-Southeast', language: 'id', requires_auth: false },
  { id: 'hum-ph-ndrrmc', organization: 'Philippines NDRRMC', url: 'https://ndrrmc.gov.ph/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11, 13], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'hum-th-ddpm', organization: 'Thailand DDPM', url: 'https://www.disaster.go.th/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11], region: 'Asia-Southeast', language: 'th', requires_auth: false },
  { id: 'hum-vn-ccfsc', organization: 'Vietnam Flood and Storm Control', url: 'https://phongchongthientai.mard.gov.vn/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11, 13], region: 'Asia-Southeast', language: 'vi', requires_auth: false },
  { id: 'hum-mm-ridkm', organization: 'Myanmar Relief and Resettlement', url: 'https://www.moswrr.gov.mm/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11], region: 'Asia-Southeast', language: 'en', requires_auth: false },

  // ── Regional Humanitarian Bodies ─────────────────────────────────────────
  { id: 'hum-asean-ahacentre', organization: 'ASEAN AHA Centre', url: 'https://ahacentre.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [11, 13], region: 'Asia-Southeast', language: 'en', requires_auth: false },
  { id: 'hum-igad-humanitarian', organization: 'IGAD Humanitarian Affairs', url: 'https://igad.int/divisions/health-and-humanitarian-affairs/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1, 11], region: 'Africa-East', language: 'en', requires_auth: false },
  { id: 'hum-au-social', organization: 'AU Department Social Affairs', url: 'https://au.int/en/directorates/humanitarian-affairs-refugees-displaced-persons', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1, 11], region: 'Africa', language: 'en', requires_auth: false },
  { id: 'hum-ecowas-hum', organization: 'ECOWAS Humanitarian', url: 'https://www.ecowas.int/ecowas-sectors/humanitarian/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1, 11], region: 'Africa-West', language: 'en', requires_auth: false },
  { id: 'hum-saarc-drr', organization: 'SAARC Disaster Management', url: 'https://www.saarc-sec.org/activities/technical-committees/disaster-management/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11, 13], region: 'Asia-South', language: 'en', requires_auth: false },
  { id: 'hum-reliefweb-events', organization: 'ReliefWeb Events', url: 'https://reliefweb.int/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [1, 11], region: 'Global', language: 'en', requires_auth: false },

  // ── Cash and Voucher Assistance ───────────────────────────────────────────
  { id: 'hum-cash-learning', organization: 'Cash Learning Partnership', url: 'https://www.calpnetwork.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 11], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-cvtf-events', organization: 'Cash and Voucher Transfer Forum', url: 'https://www.mobileforhumanity.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1, 11], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-gsma-mobile-money', organization: 'GSMA Mobile Money Humanitarian', url: 'https://www.gsma.com/mobile-for-development/resources/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1, 8], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-findex-events', organization: 'Global Findex Financial Inclusion', url: 'https://www.worldbank.org/en/topic/financialinclusion/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1, 8], region: 'Global', language: 'en', requires_auth: false },

  // ── Humanitarian Logistics ────────────────────────────────────────────────
  { id: 'hum-log-cluster', organization: 'Logistics Cluster', url: 'https://logcluster.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 11], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-wfp-logistics', organization: 'WFP Logistics', url: 'https://www.wfp.org/logistics', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [2, 1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-humlog-events', organization: 'Humanitarian Logistics', url: 'https://www.humlogistics.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1, 11], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-fleet-forum', organization: 'Fleet Forum Humanitarian', url: 'https://www.fleetforum.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1, 11], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-network-events', organization: 'NetHope Digital Humanitarian', url: 'https://nethope.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1, 9], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-drc-logistics', organization: 'DRC Logistics', url: 'https://www.drc.ngo/our-work/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 11], region: 'Global', language: 'en', requires_auth: false },

  // ── Mental Health and Psychosocial Support ────────────────────────────────
  { id: 'hum-iasc-mhpss', organization: 'IASC Mental Health', url: 'https://interagencystandingcommittee.org/iasc-reference-group-mental-health-and-psychosocial-support-emergency-settings', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-mhpss-net', organization: 'MHPSS Network', url: 'https://mhpss.net/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-wvi-mhpss', organization: 'World Vision MHPSS', url: 'https://www.wvi.org/mental-health-and-psychosocial-support', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-unhcr-mhpss', organization: 'UNHCR MHPSS', url: 'https://www.unhcr.org/mental-health-and-psychosocial-support.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-tpf-events', organization: 'Trauma Prevention Foundation', url: 'https://www.traumapreventionfoundation.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-heartstep-events', organization: 'HeartStep Humanitarian MHPSS', url: 'https://www.heartstepsinternational.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [3], region: 'Global', language: 'en', requires_auth: false },

  // ── Shelter and NFI ───────────────────────────────────────────────────────
  { id: 'hum-shelter-cluster', organization: 'Global Shelter Cluster', url: 'https://www.sheltercluster.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 11], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-ifrc-shelter', organization: 'IFRC Shelter', url: 'https://www.ifrc.org/our-work/shelter-and-settlement', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1, 11], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-nrc-shelter', organization: 'NRC Shelter', url: 'https://www.nrc.no/themes/shelter/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1, 11], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-unhabitat-hum', organization: 'UN-Habitat Emergency', url: 'https://unhabitat.org/topic/humanitarian-action', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [11, 1], region: 'Global', language: 'en', requires_auth: false },

  // ── Education in Emergencies ──────────────────────────────────────────────
  { id: 'hum-ecw-events', organization: 'Education Cannot Wait', url: 'https://www.educationcannotwait.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-inee-events', organization: 'INEE Education in Emergencies', url: 'https://inee.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-save-edu-emerg', organization: 'Save the Children Education Emergencies', url: 'https://www.savethechildren.org/us/what-we-do/emergency-response/education/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [4], region: 'Global', language: 'en', requires_auth: false },

  // ── Coordination Mechanisms ───────────────────────────────────────────────
  { id: 'hum-isc-events', organization: 'Inter-Agency Standing Committee', url: 'https://interagencystandingcommittee.org/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-donor-forum', organization: 'Good Humanitarian Donorship', url: 'https://www.ghdinitiative.org/ghd/gns/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1, 17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-dac-events', organization: 'OECD DAC Humanitarian', url: 'https://www.oecd.org/dac/humanitarian-donors/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1, 17], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-hiik-events', organization: 'Heidelberg Conflict Barometer', url: 'https://hiik.de/en/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [16], region: 'Europe', language: 'en', requires_auth: false },
  { id: 'hum-global-hum-forum', organization: 'Global Humanitarian Forum', url: 'https://www.ghf-ge.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [1, 17], region: 'Global', language: 'en', requires_auth: false },

  // ── Refugees and Forced Displacement ─────────────────────────────────────
  { id: 'hum-grf-events', organization: 'Global Refugee Forum', url: 'https://www.unhcr.org/global-refugee-forum.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10, 1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-unhcr-events', organization: 'UNHCR Events', url: 'https://www.unhcr.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'daily', primary_sdg_goals: [10, 1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-gc-migration', organization: 'Global Compact Migration Forum', url: 'https://www.iom.int/global-compact-migration', source_type: 'website', scrape_method: 'html', scrape_frequency: 'monthly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-rmp-events', organization: 'Refugee Response Platform', url: 'https://data.unhcr.org/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-nrc-events', organization: 'Norwegian Refugee Council', url: 'https://www.nrc.no/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [10, 1], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-rescue-events', organization: 'IRC International Rescue Committee', url: 'https://www.rescue.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-mercy-corps-events', organization: 'Mercy Corps', url: 'https://www.mercycorps.org/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 10], region: 'Global', language: 'en', requires_auth: false },
  { id: 'hum-care-emergencies', organization: 'CARE Emergencies', url: 'https://www.care.org/our-work/disaster-response/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', primary_sdg_goals: [1, 10], region: 'Global', language: 'en', requires_auth: false },
];
