import type { ScraperSource } from './types';

// Chunk 1 of 3: US + Canada government sources.
// Defaults applied: source_type=website, scrape_method=html,
// scrape_frequency=weekly, requires_auth=false, language=en.

export const NORTH_AMERICA_GOVERNMENT_SOURCES: ScraperSource[] = [
  // ── UNITED STATES GOVERNMENT ──────────────────────────────────────────────
  { id: 'usaid-events', organization: 'USAID Events', url: 'https://www.usaid.gov/news-information/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [17], region: 'Americas-North' },
  { id: 'state-dept-events', organization: 'US State Department Events', url: 'https://www.state.gov/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [16, 17], region: 'Americas-North' },
  { id: 'us-epa-events', organization: 'US EPA Events', url: 'https://www.epa.gov/newsevents/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [13, 15], region: 'Americas-North' },
  { id: 'us-education-events', organization: 'US Department of Education Events', url: 'https://www.ed.gov/news/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [4], region: 'Americas-North' },
  { id: 'us-labor-events', organization: 'US Department of Labor Events', url: 'https://www.dol.gov/newsroom/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [8], region: 'Americas-North' },
  { id: 'us-agriculture-events', organization: 'USDA Agriculture Events', url: 'https://www.usda.gov/media/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [2], region: 'Americas-North' },
  { id: 'us-energy-events', organization: 'US Department of Energy Events', url: 'https://www.energy.gov/newsroom/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [7], region: 'Americas-North' },
  { id: 'us-treasury-events', organization: 'US Treasury Events', url: 'https://home.treasury.gov/news/press-releases', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [8, 17], region: 'Americas-North' },
  { id: 'mcc-events', organization: 'Millennium Challenge Corporation Events', url: 'https://www.mcc.gov/news-and-events/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [17], region: 'Americas-North' },
  { id: 'peacecorps-events', organization: 'Peace Corps Events', url: 'https://www.peacecorps.gov/news/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [17], region: 'Americas-North' },
  { id: 'dfc-events', organization: 'US DFC Events', url: 'https://www.dfc.gov/newsroom/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [8, 17], region: 'Americas-North' },
  { id: 'cdc-global-events', organization: 'CDC Global Health Events', url: 'https://www.cdc.gov/globalhealth/newsroom/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [3], region: 'Americas-North' },
  { id: 'nih-fogarty-events', organization: 'NIH Fogarty International Events', url: 'https://www.fic.nih.gov/Events/Pages/default.aspx', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [3, 4], region: 'Americas-North' },
  { id: 'nsf-international-events', organization: 'NSF International Events', url: 'https://www.nsf.gov/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [9, 4], region: 'Americas-North' },
  { id: 'us-hhs-global-events', organization: 'HHS Global Health Events', url: 'https://www.hhs.gov/about/news/index.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [3], region: 'Americas-North' },
  { id: 'us-commerce-events', organization: 'US Commerce Department Events', url: 'https://www.commerce.gov/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [8, 9], region: 'Americas-North' },
  { id: 'us-interior-events', organization: 'US Interior Department Events', url: 'https://www.doi.gov/news/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [15], region: 'Americas-North' },
  { id: 'us-transport-events', organization: 'US Transportation Events', url: 'https://www.transportation.gov/news/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [11], region: 'Americas-North' },
  { id: 'us-housing-events', organization: 'HUD Housing Events', url: 'https://www.hud.gov/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [11], region: 'Americas-North' },
  { id: 'us-justice-events', organization: 'US Justice Department Events', url: 'https://www.justice.gov/news', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [16], region: 'Americas-North' },

  // ── CANADA ────────────────────────────────────────────────────────────────
  { id: 'canada-gap-events', organization: 'Global Affairs Canada Events', url: 'https://www.international.gc.ca/world-monde/events-evenements/index.aspx', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [17], region: 'Americas-North' },
  { id: 'canada-environment-events', organization: 'Canada Environment Events', url: 'https://www.canada.ca/en/environment-climate-change/news/events.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [13], region: 'Americas-North' },
  { id: 'canada-immigration-events', organization: 'Canada Immigration Events', url: 'https://www.canada.ca/en/immigration-refugees-citizenship/news/events.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [10], region: 'Americas-North' },
  { id: 'canada-agriculture-events', organization: 'Agriculture Canada Events', url: 'https://www.canada.ca/en/agriculture-agri-food/news/events.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [2], region: 'Americas-North' },
  { id: 'idrc-events', organization: 'IDRC Canada Events', url: 'https://www.idrc.ca/en/events', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [17], region: 'Americas-North' },
  { id: 'canada-status-women-events', organization: 'Canada Status of Women Events', url: 'https://www.canada.ca/en/status-women/news/events.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [5], region: 'Americas-North' },
  { id: 'canada-indigenous-events', organization: 'Canada Indigenous Affairs Events', url: 'https://www.rcaanc-cirnac.gc.ca/eng/1100100010002/1533321160986', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [10], region: 'Americas-North' },
  { id: 'canada-natural-resources-events', organization: 'Canada Natural Resources Events', url: 'https://www.nrcan.gc.ca/news/events/', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [7, 15], region: 'Americas-North' },
  { id: 'canada-justice-events', organization: 'Canada Justice Events', url: 'https://www.justice.gc.ca/eng/news-nouv/events.html', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'en', primary_sdg_goals: [16], region: 'Americas-North' },
];

// Chunk 2 of 3: Brazil + Mexico government sources.
// Defaults: source_type=website, scrape_method=html, scrape_frequency=weekly,
// requires_auth=false. Language: pt for Brazil, es for Mexico.

export const LATIN_AMERICA_GOVERNMENT_SOURCES_PART1: ScraperSource[] = [
  // ── BRAZIL ────────────────────────────────────────────────────────────────
  { id: 'brazil-mre-events', organization: 'Brazil Foreign Ministry Events', url: 'https://www.gov.br/mre/pt-br/assuntos/eventos', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'brazil-mma-events', organization: 'Brazil Environment Ministry', url: 'https://www.gov.br/mma/pt-br/assuntos/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [13, 15], region: 'Americas-Latin' },
  { id: 'brazil-mec-events', organization: 'Brazil Education Ministry', url: 'https://www.gov.br/mec/pt-br/assuntos/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [4], region: 'Americas-Latin' },
  { id: 'brazil-mds-events', organization: 'Brazil Social Development Ministry', url: 'https://www.gov.br/mds/pt-br/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [1, 10], region: 'Americas-Latin' },
  { id: 'brazil-agriculture-events', organization: 'Brazil Agriculture Ministry', url: 'https://www.gov.br/agricultura/pt-br/assuntos/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [2], region: 'Americas-Latin' },
  { id: 'brazil-energy-events', organization: 'Brazil Energy Ministry', url: 'https://www.gov.br/mme/pt-br/assuntos/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [7], region: 'Americas-Latin' },
  { id: 'brazil-women-events', organization: 'Brazil Women Ministry', url: 'https://www.gov.br/mulheres/pt-br/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [5], region: 'Americas-Latin' },
  { id: 'brazil-indigenous-events', organization: 'Brazil FUNAI Indigenous Affairs', url: 'https://www.gov.br/funai/pt-br/assuntos/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [10], region: 'Americas-Latin' },
  { id: 'abc-brazil-events', organization: 'ABC Brazil South-South Cooperation', url: 'https://www.gov.br/abc/pt-br/assuntos/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'brazil-health-events', organization: 'Brazil Health Ministry', url: 'https://www.gov.br/saude/pt-br/assuntos/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [3], region: 'Americas-Latin' },
  { id: 'brazil-justice-events', organization: 'Brazil Justice Ministry', url: 'https://www.gov.br/mj/pt-br/assuntos/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [16], region: 'Americas-Latin' },
  { id: 'brazil-labor-events', organization: 'Brazil Labor Ministry', url: 'https://www.gov.br/trabalho/pt-br/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [8], region: 'Americas-Latin' },
  { id: 'brazil-cities-events', organization: 'Brazil Cities Ministry', url: 'https://www.gov.br/cidades/pt-br/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [11], region: 'Americas-Latin' },
  { id: 'brazil-science-events', organization: 'Brazil Science Technology Ministry', url: 'https://www.gov.br/mcti/pt-br/assuntos/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [9], region: 'Americas-Latin' },
  { id: 'brazil-human-rights-events', organization: 'Brazil Human Rights Ministry', url: 'https://www.gov.br/mdh/pt-br/assuntos/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [10, 16], region: 'Americas-Latin' },
  { id: 'brazil-racial-equality-events', organization: 'Brazil Racial Equality Ministry', url: 'https://www.gov.br/igualdaderacial/pt-br/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'pt', primary_sdg_goals: [10], region: 'Americas-Latin' },

  // ── MEXICO ────────────────────────────────────────────────────────────────
  { id: 'mexico-sre-events', organization: 'Mexico Foreign Ministry', url: 'https://www.gob.mx/sre/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'mexico-semarnat-events', organization: 'Mexico Environment Ministry', url: 'https://www.gob.mx/semarnat/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [13, 15], region: 'Americas-Latin' },
  { id: 'mexico-sep-events', organization: 'Mexico Education Ministry', url: 'https://www.gob.mx/sep/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [4], region: 'Americas-Latin' },
  { id: 'mexico-agriculture-events', organization: 'Mexico Agriculture Ministry', url: 'https://www.gob.mx/sader/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [2], region: 'Americas-Latin' },
  { id: 'mexico-energy-events', organization: 'Mexico Energy Ministry', url: 'https://www.gob.mx/sener/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [7], region: 'Americas-Latin' },
  { id: 'mexico-women-events', organization: 'Mexico Women Institute', url: 'https://www.gob.mx/inmujeres/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [5], region: 'Americas-Latin' },
  { id: 'amexcid-events', organization: 'AMEXCID Mexico Cooperation Agency', url: 'https://www.gob.mx/amexcid/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [17], region: 'Americas-Latin' },
  { id: 'mexico-health-events', organization: 'Mexico Health Ministry', url: 'https://www.gob.mx/salud/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [3], region: 'Americas-Latin' },
  { id: 'mexico-labor-events', organization: 'Mexico Labor Ministry', url: 'https://www.gob.mx/stps/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [8], region: 'Americas-Latin' },
  { id: 'mexico-social-events', organization: 'Mexico Social Welfare Ministry', url: 'https://www.gob.mx/bienestar/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [1, 10], region: 'Americas-Latin' },
  { id: 'mexico-indigenous-events', organization: 'Mexico Indigenous Peoples Institute', url: 'https://www.gob.mx/inpi/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [10], region: 'Americas-Latin' },
  { id: 'mexico-water-events', organization: 'Mexico Water Commission', url: 'https://www.gob.mx/conagua/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [6], region: 'Americas-Latin' },
  { id: 'mexico-housing-events', organization: 'Mexico Urban Development Ministry', url: 'https://www.gob.mx/sedatu/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [11], region: 'Americas-Latin' },
  { id: 'mexico-justice-events', organization: 'Mexico Justice Ministry', url: 'https://www.gob.mx/sspc/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [16], region: 'Americas-Latin' },
  { id: 'mexico-science-events', organization: 'Mexico Science Council CONAHCYT', url: 'https://www.gob.mx/conahcyt/noticias', source_type: 'website', scrape_method: 'html', scrape_frequency: 'weekly', requires_auth: false, language: 'es', primary_sdg_goals: [9], region: 'Americas-Latin' },
];
